/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:43 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ActionLogInfo : NSObject {
	unsigned eventid; 
	unsigned begin_time; 
	unsigned end_time; 
	unsigned log_count; 
	NSString* action_path; 
}
@property (nonatomic,retain) NSString* action_path; 
@property (assign,nonatomic) unsigned log_count; 
@property (assign,nonatomic) unsigned end_time; 
@property (assign,nonatomic) unsigned begin_time; 
@property (assign,nonatomic) unsigned eventid; 
-(void)setEventid:(unsigned long)arg1;
-(void)setLog_count:(unsigned long)arg1;
-(void)setBegin_time:(unsigned long)arg1;
-(void)setEnd_time:(unsigned long)arg1;
-(void)setAction_path:(id)arg1;
-(id)init;
-(void)dealloc;
@end