/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:38:58 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MMActionSheetDelegate.h>

@interface ActionSheetTestViewController : UIViewController <MMActionSheetDelegate> {
	MMActionSheet* actionSheet; 
	UILabel* testLabel; 
	UITextField* textField; 
}
-(void)actionSheet:(id)arg1 didSelectWithItem:(id)arg2;
-(void)buttonTapped:(id)arg1;
-(void)didReceiveMemoryWarning;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(void)viewDidLoad;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)dealloc;
@end