/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:24 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AddMsg : PBGeneratedMessage {
	unsigned int hasMsgId:1; 
	unsigned int hasMsgType:1; 
	unsigned int hasMsgSource:1; 
	unsigned int hasPushContent:1; 
	unsigned int hasFromUserName:1; 
	unsigned int hasToUserName:1; 
	unsigned int hasContent:1; 
	unsigned int hasImgBuf:1; 
	unsigned int hasStatus:1; 
	unsigned int hasImgStatus:1; 
	unsigned int hasCreateTime:1; 
	int msgId; 
	int msgType; 
	NSString* msgSource; 
	NSString* pushContent; 
	SKBuiltinString_t* fromUserName; 
	SKBuiltinString_t* toUserName; 
	SKBuiltinString_t* content; 
	SKBuiltinBuffer_t* imgBuf; 
	unsigned status; 
	unsigned imgStatus; 
	unsigned createTime; 
}
@property (retain) NSString* pushContent; 
@property (assign) BOOL hasPushContent; 
@property (retain) NSString* msgSource; 
@property (assign) BOOL hasMsgSource; 
@property (assign) unsigned createTime; 
@property (assign) BOOL hasCreateTime; 
@property (retain) SKBuiltinBuffer_t* imgBuf; 
@property (assign) BOOL hasImgBuf; 
@property (assign) unsigned imgStatus; 
@property (assign) BOOL hasImgStatus; 
@property (assign) unsigned status; 
@property (assign) BOOL hasStatus; 
@property (retain) SKBuiltinString_t* content; 
@property (assign) BOOL hasContent; 
@property (assign) int msgType; 
@property (assign) BOOL hasMsgType; 
@property (retain) SKBuiltinString_t* toUserName; 
@property (assign) BOOL hasToUserName; 
@property (retain) SKBuiltinString_t* fromUserName; 
@property (assign) BOOL hasFromUserName; 
@property (assign) int msgId; 
@property (assign) BOOL hasMsgId; 
+(id)parseFromData:(id)arg1;
-(id)SetContent:(id)arg1;
-(id)SetToUserName:(id)arg1;
-(int)serializedSize;
-(void)setCreateTime:(unsigned)arg1;
-(id)SetStatus:(unsigned)arg1;
-(void)setHasImgStatus:(BOOL)arg1;
-(id)SetImgStatus:(unsigned)arg1;
-(void)setImgStatus:(unsigned)arg1;
-(void)setHasCreateTime:(BOOL)arg1;
-(id)SetCreateTime:(unsigned)arg1;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasPushContent:(BOOL)arg1;
-(void)setHasMsgSource:(BOOL)arg1;
-(void)setHasMsgType:(BOOL)arg1;
-(void)setHasToUserName:(BOOL)arg1;
-(void)setHasFromUserName:(BOOL)arg1;
-(void)setHasMsgId:(BOOL)arg1;
-(id)SetPushContent:(id)arg1;
-(id)SetMsgSource:(id)arg1;
-(id)SetMsgType:(int)arg1;
-(id)SetFromUserName:(id)arg1;
-(id)SetMsgId:(int)arg1;
-(void)setMsgType:(int)arg1;
-(void)setMsgId:(int)arg1;
-(void)setPushContent:(id)arg1;
-(void)setMsgSource:(id)arg1;
-(void)setToUserName:(id)arg1;
-(void)setFromUserName:(id)arg1;
-(void)setHasImgBuf:(BOOL)arg1;
-(id)SetImgBuf:(id)arg1;
-(void)setImgBuf:(id)arg1;
-(void)setHasContent:(BOOL)arg1;
-(void)setStatus:(unsigned)arg1;
-(void)setHasStatus:(BOOL)arg1;
-(id)init;
-(void)dealloc;
-(void)setContent:(id)arg1;
@end