/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:13 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WCFacadeExt.h>

@interface AlbumContactInfoAssist : CBaseContactInfoAssist <WCFacadeExt> {
}
-(void)onWCGroupUpdatedReturn:(BOOL)arg1;
-(void)initHeaderView;
-(void)makeCell:(id)arg1 row:(unsigned)arg2 section:(unsigned long)arg3;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)dealloc;
@end