/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:17 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IAPPEmoticonDownloadExt.h>

@interface AppEmoticonMessageNodeView : BaseMessageNodeView <IAPPEmoticonDownloadExt> {
	MMEmoticonView* m_oImageView; 
	UIButton* m_oDownloadButton; 
}
+(BOOL)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
-(id)initWithMessageWrap:(id)arg1 Contact:(id)arg2 ChatContact:(id)arg3;
-(void)onClick;
-(void)onAppEmoticonDownloadFinished:(id)arg1;
-(void)onTouchCancel;
-(void)onTouchDownRepeat;
-(void)onTouchDown;
-(void)onTouchUpInside;
-(void)onLongTouch;
-(void)layoutSubviewsInternal;
-(CGSize)sizeForFrame:(CGRect)arg1;
-(void)onMenuItemWillHide;
-(void)onForward:(id)arg1;
-(void)onClearResource;
-(void)onDisappear;
-(void)showOperations;
-(void)SaveEmoticon:(id)arg1;
-(void)updateEmoticonView;
-(void)updateStatus:(id)arg1;
-(void)dealloc;
@end