/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:09 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AppMsg : PBGeneratedMessage {
	unsigned int hasSource:1; 
	unsigned int hasRemindId:1; 
	unsigned int hasFromUserName:1; 
	unsigned int hasAppId:1; 
	unsigned int hasToUserName:1; 
	unsigned int hasContent:1; 
	unsigned int hasClientMsgId:1; 
	unsigned int hasThumb:1; 
	unsigned int hasSdkVersion:1; 
	unsigned int hasType:1; 
	unsigned int hasCreateTime:1; 
	int source; 
	int remindId; 
	NSString* fromUserName; 
	NSString* appId; 
	NSString* toUserName; 
	NSString* content; 
	NSString* clientMsgId; 
	SKBuiltinBuffer_t* thumb; 
	unsigned sdkVersion; 
	unsigned type; 
	unsigned createTime; 
}
@property (assign) int remindId; 
@property (assign) BOOL hasRemindId; 
@property (assign) int source; 
@property (assign) BOOL hasSource; 
@property (retain) SKBuiltinBuffer_t* thumb; 
@property (assign) BOOL hasThumb; 
@property (retain) NSString* clientMsgId; 
@property (assign) BOOL hasClientMsgId; 
@property (assign) unsigned createTime; 
@property (assign) BOOL hasCreateTime; 
@property (retain) NSString* content; 
@property (assign) BOOL hasContent; 
@property (assign) unsigned type; 
@property (assign) BOOL hasType; 
@property (retain) NSString* toUserName; 
@property (assign) BOOL hasToUserName; 
@property (assign) unsigned sdkVersion; 
@property (assign) BOOL hasSdkVersion; 
@property (retain) NSString* appId; 
@property (assign) BOOL hasAppId; 
@property (retain) NSString* fromUserName; 
@property (assign) BOOL hasFromUserName; 
+(id)parseFromData:(id)arg1;
-(id)SetType:(unsigned)arg1;
-(id)SetContent:(id)arg1;
-(id)SetAppId:(id)arg1;
-(id)SetToUserName:(id)arg1;
-(int)serializedSize;
-(void)setCreateTime:(unsigned)arg1;
-(void)setHasCreateTime:(BOOL)arg1;
-(id)SetCreateTime:(unsigned)arg1;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasRemindId:(BOOL)arg1;
-(id)SetRemindId:(int)arg1;
-(void)setRemindId:(int)arg1;
-(void)setHasAppId:(BOOL)arg1;
-(void)setHasSdkVersion:(BOOL)arg1;
-(id)SetSdkVersion:(unsigned)arg1;
-(void)setSdkVersion:(unsigned)arg1;
-(void)setHasClientMsgId:(BOOL)arg1;
-(id)SetClientMsgId:(id)arg1;
-(void)setClientMsgId:(id)arg1;
-(void)setHasThumb:(BOOL)arg1;
-(id)SetThumb:(id)arg1;
-(void)setHasToUserName:(BOOL)arg1;
-(void)setHasFromUserName:(BOOL)arg1;
-(id)SetFromUserName:(id)arg1;
-(void)setToUserName:(id)arg1;
-(void)setFromUserName:(id)arg1;
-(void)setHasSource:(BOOL)arg1;
-(id)SetSource:(int)arg1;
-(void)setHasContent:(BOOL)arg1;
-(void)setType:(unsigned)arg1;
-(void)setThumb:(id)arg1;
-(void)setSource:(int)arg1;
-(void)setHasType:(BOOL)arg1;
-(void)setAppId:(id)arg1;
-(id)init;
-(void)dealloc;
-(void)setContent:(id)arg1;
@end