/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:23 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AppTextMessageNodeView : TextMessageNodeView {
}
+(BOOL)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
-(id)patternText;
-(id)titleText;
@end