/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:06 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AshaRegRequest : PBGeneratedMessage {
	unsigned int hasNid:1; 
	unsigned int hasBaseRequest:1; 
	NSString* nid; 
	BaseRequest* baseRequest; 
}
@property (retain) NSString* nid; 
@property (assign) BOOL hasNid; 
@property (retain) BaseRequest* baseRequest; 
@property (assign) BOOL hasBaseRequest; 
+(id)parseFromData:(id)arg1;
-(id)SetBaseRequest:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasNid:(BOOL)arg1;
-(id)SetNid:(id)arg1;
-(void)setNid:(id)arg1;
-(void)setHasBaseRequest:(BOOL)arg1;
-(void)setBaseRequest:(id)arg1;
-(id)init;
-(void)dealloc;
@end