/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:29 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BaseResponse : PBGeneratedMessage {
	unsigned int hasRet:1; 
	unsigned int hasErrMsg:1; 
	int ret; 
	SKBuiltinString_t* errMsg; 
}
@property (retain) SKBuiltinString_t* errMsg; 
@property (assign) BOOL hasErrMsg; 
@property (assign) int ret; 
@property (assign) BOOL hasRet; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasErrMsg:(BOOL)arg1;
-(void)setHasRet:(BOOL)arg1;
-(id)SetErrMsg:(id)arg1;
-(id)SetRet:(int)arg1;
-(void)setRet:(int)arg1;
-(void)setErrMsg:(id)arg1;
-(id)init;
-(void)dealloc;
@end