/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:05 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <EmoticonSelectorViewDelegate.h>
#import <EmoticonSelectorViewDataSource.h>

@interface BaseEmoticonViewController : MMUIViewController <EmoticonSelectorViewDelegate, EmoticonSelectorViewDataSource> {
	id<BaseEmoticonViewDelegate> m_delegate; 
	BOOL _bLongPressShow; 
}
@property (assign,nonatomic) id<BaseEmoticonViewDelegate> m_delegate; 
-(void)setM_delegate:(id)arg1;
-(void)onTopBarFrameChanged;
-(void)my_viewWillUnload;
-(void)my_viewDidUnload;
-(int)longPressModeAtIndex:(unsigned long)arg1;
-(void)didReleaseLongPressEmoticonAtIndex:(unsigned long)arg1;
-(void)didSelectEmoticonAtIndex:(unsigned long)arg1;
-(id)getMenuItemArray;
-(id)scrollViewBackground;
-(id)descriptionForEmoticonAtIndex:(unsigned long)arg1;
-(id)viewForEmoticonAtIndex:(unsigned long)arg1;
-(unsigned long)numberOfCols;
-(unsigned long)numberOfEmoticons;
-(BOOL)enableForButtonAtIndex:(unsigned long)arg1;
-(void)disappearFromTabbar;
-(void)emoticonPreviewShow:(BOOL)arg1;
-(void)hideEmoticonPreview;
-(void)didReceiveMemoryWarning;
-(unsigned long)numberOfRows;
-(void)viewDidLoad;
-(void)viewDidUnload;
@end