/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:17 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BizBottleInfo : PBGeneratedMessage {
	unsigned int hasBottleId:1; 
	unsigned int hasFromUserName:1; 
	unsigned int hasMsgType:1; 
	NSString* bottleId; 
	NSString* fromUserName; 
	unsigned msgType; 
}
@property (retain) NSString* fromUserName; 
@property (assign) BOOL hasFromUserName; 
@property (assign) unsigned msgType; 
@property (assign) BOOL hasMsgType; 
@property (retain) NSString* bottleId; 
@property (assign) BOOL hasBottleId; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasBottleId:(BOOL)arg1;
-(id)SetBottleId:(id)arg1;
-(void)setBottleId:(id)arg1;
-(void)setHasMsgType:(BOOL)arg1;
-(void)setHasFromUserName:(BOOL)arg1;
-(id)SetMsgType:(unsigned)arg1;
-(id)SetFromUserName:(id)arg1;
-(void)setMsgType:(unsigned)arg1;
-(void)setFromUserName:(id)arg1;
-(id)init;
-(void)dealloc;
@end