/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:15 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <LocationRetrieveDelegate.h>
#import <PBMessageObserverDelegate.h>

@interface BrandServiceEnterConversationLogic : NSObject <LocationRetrieveDelegate, PBMessageObserverDelegate> {
	unsigned m_eventID; 
	LocationRetriever* m_locationRetriever; 
	CContact* m_contact; 
}
@property (nonatomic,retain) CContact* m_contact; 
@property (nonatomic,retain) LocationRetriever* m_locationRetriever; 
-(void)setM_contact:(id)arg1;
-(void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
-(void)onRetrieveLocationTimeOut:(id)arg1;
-(void)onRetrieveLocationOK:(id)arg1;
-(void)onRetrieveLocationError:(int)arg1;
-(void)startReportEnterConversationForContact:(id)arg1 HasSetLocation:(BOOL)arg2;
-(void)reportEnterConversationNOLocation;
-(void)reportEnterConversationWithLocation:(id)arg1 ErrorCode:(int)arg2;
-(void)clickCommandReportInfo:(id)arg1;
-(void)setM_locationRetriever:(id)arg1;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
-(id)init;
-(void)dealloc;
@end