/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:03 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIAlertViewDelegate.h>

@interface BrandUserContactInfoAssist : CBaseContactInfoAssist <UIAlertViewDelegate> {
	UIButton* _viewMsgBtn; 
	UIButton* _followBtn; 
	BOOL _isChanged; 
	MMBrandHeadImageView* m_brandHeadView; 
	NSMutableArray* m_rowsData; 
	id<chatRoomSettingDelegate> m_chatRoomDelegate; 
}
@property (assign,nonatomic) id<chatRoomSettingDelegate> m_chatRoomDelegate; 
@property (nonatomic,retain) NSMutableArray* m_rowsData; 
-(void)canNotFollowContact:(id)arg1;
-(float)getTextFieldTopMarginVerifyLogic:(id)arg1;
-(id)getAlertMessageForVerifyLogic:(id)arg1;
-(id)getAlertTitleForVerifyLogic:(id)arg1;
-(void)contactVerifyOk:(id)arg1 opCode:(unsigned long)arg2;
-(void)makeSignatureCell:(id)arg1;
-(void)initHDHeadImage;
-(void)initHeaderView;
-(void)initFooterView;
-(void)initNickNameLabel;
-(void)initHeadImage;
-(void)updateNickNameLabel;
-(void)onContactUpdated;
-(void)reloadTableView;
-(void)setM_chatRoomDelegate:(id)arg1;
-(id)initWithContact:(id)arg1 andVerify:(unsigned long)arg2 delegate:(id)arg3;
-(void)reloadRowData;
-(void)setM_rowsData:(id)arg1;
-(void)onDelete:(id)arg1;
-(void)makeCell:(id)arg1 row:(unsigned)arg2 section:(unsigned long)arg3;
-(void)checkIsChanged;
-(void)clearContent;
-(void)enterWebView:(id)arg1;
-(void)makeCell:(id)arg1 withText:(id)arg2;
-(void)makeShowMessageCell:(id)arg1;
-(void)makeAllowPositionCell:(id)arg1;
-(void)makeHideFromProfileCell:(id)arg1;
-(void)makeBlockMessageNotifyCell:(id)arg1;
-(void)makeVerifySourceCell:(id)arg1;
-(void)onAllowPositionChanged:(id)arg1;
-(void)onShowSwitchChanged:(id)arg1;
-(void)onBlockSwitchChanged:(id)arg1;
-(BOOL)isInCustomAlertMode;
-(void)onViewMsgBtnClick:(id)arg1;
-(BOOL)isContactExpired;
-(void)onAction;
-(int)calVerifySourceCellHeight;
-(int)calSignatureCellHeight;
-(void)updateNavigationBarRightButton;
-(id)urlConfigAtIndex:(int)arg1;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)dealloc;
-(void)updateFooterView;
@end