/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:07 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BrandServiceDeleteAdviceMsg : NSObject {
	NSString* title; 
	NSMutableArray* brandServiceNameList; 
}
@property (nonatomic,retain) NSMutableArray* brandServiceNameList; 
@property (nonatomic,copy) NSString* title; 
-(BOOL)fromXml:(struct XmlReaderNode_t*)arg1;
-(void)setBrandServiceNameList:(id)arg1;
-(void)setTitle:(id)arg1;
-(void)dealloc;
@end