/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:48 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <chatRoomSettingDelegate.h>

@interface BrandCommModeLogicController : WeixinContentLogicController <chatRoomSettingDelegate> {
	BrandServiceEnterConversationLogic* m_enterConversationLogic; 
	BrandServiceContinueLocationReportLogic* m_continueLocationReporter; 
}
@property (nonatomic,retain) BrandServiceContinueLocationReportLogic* m_continueLocationReporter; 
@property (nonatomic,retain) BrandServiceEnterConversationLogic* m_enterConversationLogic; 
-(BOOL)canAutoplayWhenMessageDownloaded;
-(BOOL)CanRemoteRecord;
-(id)GetRightBarButtonImage;
-(void)ViewDidInit;
-(void)ViewWillInit;
-(void)CustomToolViewEX:(id)arg1;
-(void)OpenContactInfo:(id)arg1;
-(void)OpenDetailInfo;
-(BOOL)isShowHeadImage:(id)arg1;
-(void)clearAllMsg;
-(void)updateContactFromServer;
-(id)GetPossibleContactByName:(id)arg1;
-(void)setM_enterConversationLogic:(id)arg1;
-(void)setM_continueLocationReporter:(id)arg1;
-(id)getCurContact;
-(void)dealloc;
@end