/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:13 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <ILinkEventExt.h>

@interface BrandQAMessageNodeView : BaseMessageNodeView <ILinkEventExt> {
	UIImageView* m_oBkgImageView; 
}
+(BOOL)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
-(id)genCommentButton;
-(void)onTouchCancel;
-(void)onTouchDownRepeat;
-(void)onTouchDown;
-(void)onTouchUpInside;
-(void)onLongTouch;
-(void)layoutSubviewsInternal;
-(CGSize)sizeForFrame:(CGRect)arg1;
-(void)onMenuItemWillHide;
-(void)calculateLeftRightMargin;
-(void)updateBkgImage:(BOOL)arg1;
-(void)onTapReply:(id)arg1;
-(id)richTextViewFromMessageWrap:(id)arg1 referContent:(id)arg2 TextColor:(id)arg3;
-(void)makeNodeWithMsgWrap:(id)arg1 Frame:(CGRect)arg2 BackgroundImage:(id)arg3;
-(void)updateNodeWithMsgWrap:(id)arg1;
-(void)dealloc;
@end