/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:00 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <CustomMenuToolViewDelegate.h>
#import <CustomSubMenuFloatViewDelegate.h>
#import <IBrandUserUIExt.h>
#import <IUiUtilExt.h>

@interface BrandCustomModeContentLogicController : WeixinContentLogicController <CustomMenuToolViewDelegate, CustomSubMenuFloatViewDelegate, IBrandUserUIExt, IUiUtilExt> {
	CustomMenuToolView* m_menuToolView; 
	CustomSubMenuFloatView* m_subMenuFloatView; 
	MMBizMenuInfo* m_menuData; 
	BrandServiceEnterConversationLogic* m_enterConversationLogic; 
	BrandServiceContinueLocationReportLogic* m_continueLocationReporter; 
	BOOL m_isInCustomMode; 
	BOOL m_hasInit; 
}
@property (nonatomic,retain) BrandServiceContinueLocationReportLogic* m_continueLocationReporter; 
@property (nonatomic,retain) BrandServiceEnterConversationLogic* m_enterConversationLogic; 
-(BOOL)canAutoplayWhenMessageDownloaded;
-(BOOL)CanRemoteRecord;
-(void)OnAddMsg:(id)arg1 MsgWrap:(id)arg2;
-(BOOL)canReloadViewIfMemoryWarning;
-(id)GetRightBarButtonImage;
-(void)ViewDidAppear;
-(void)ViewDidInit;
-(void)ViewWillInit;
-(void)CustomToolViewEX:(id)arg1;
-(void)OpenContactInfo:(id)arg1;
-(void)OpenDetailInfo;
-(BOOL)isShowHeadImage:(id)arg1;
-(BOOL)shouldHideToolView:(id)arg1;
-(void)afterToolViewHeightUpdate:(id)arg1;
-(void)beforeToolViewHeightUpdate:(id)arg1;
-(float)getBizChangeInputBtnWidth;
-(void)onTopBarFrameChanged;
-(void)updateContactFromServer;
-(void)OnClickCommand:(id)arg1 CustomMenuButton:(id)arg2;
-(void)onChangeToExchang:(id)arg1;
-(void)onJumpToWebView:(id)arg1;
-(void)onClickCommandBtn:(id)arg1;
-(void)onSubMenuPresentWithIndex:(int)arg1 ArrowX:(float)arg2;
-(void)onSubMenuDismiss;
-(void)changeToInputMode;
-(id)GetPossibleContactByName:(id)arg1;
-(void)setM_enterConversationLogic:(id)arg1;
-(void)setM_continueLocationReporter:(id)arg1;
-(id)getCurContact;
-(void)finishedChangeToInputMode;
-(void)swichToolViewToCustomView;
-(void)finishedChangeToMenuMode;
-(void)AdjustModeButtonPosition;
-(void)changeToMenuMode;
-(id)buttonListFromArr:(id)arg1;
-(void)updataFloatContentView;
-(id)getSubMenuInfoByIndex:(int)arg1;
-(void)stopReceiveMsg;
-(void)startReceiveMsg;
-(id)GetInnerToolView;
-(id)getMenuInfo;
-(void)createMenuToolView;
-(void)loadMenuData;
-(id)init;
-(void)dealloc;
@end