/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:54 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PopupTextEditViewControllerDelegate.h>
#import <BrandStoryMgrExt.h>
#import <QAConfirmViewControllerDelegate.h>
#import <BrandQAInputToolViewDelegate.h>

@interface BrandQAModeContentLogicController : WeixinContentLogicController <PopupTextEditViewControllerDelegate, BrandStoryMgrExt, QAConfirmViewControllerDelegate, BrandQAInputToolViewDelegate> {
	BrandQAInputToolView* m_toolView; 
	int m_canAskCount; 
	int m_canAnswerCount; 
	int m_lastGetQuestionEvent; 
}
-(BOOL)CanRemoteRecord;
-(id)GetRightBarButtonImage;
-(void)ViewDidInit;
-(void)ViewWillInit;
-(void)CustomToolViewEX:(id)arg1;
-(void)OpenContactInfo:(id)arg1;
-(void)OpenDetailInfo;
-(void)replyBrandQAMessage:(id)arg1;
-(BOOL)isShowHeadImage:(id)arg1;
-(void)initToolView;
-(void)updateContactFromServer;
-(void)handleToolView;
-(void)onGetQuestionFinishedWithResult:(int)arg1 Xml:(id)arg2 EventID:(int)arg3;
-(void)onBrandQAInfoUpdate:(id)arg1 Ret:(int)arg2;
-(void)OnCancel:(id)arg1;
-(void)onTapAnswerBtn:(id)arg1;
-(void)onTapQuestionBtn:(id)arg1;
-(void)onEditOk:(id)arg1 WithTextEdit:(id)arg2;
-(void)onEditCancelWithTextEdit:(id)arg1;
-(void)OnOk:(id)arg1;
-(id)GetPossibleContactByName:(id)arg1;
-(id)getCurContact;
-(void)beginAnswerQuestion:(id)arg1;
-(void)AddReceivedQuestion:(id)arg1;
-(void)markMessageAsReplied:(id)arg1;
-(void)SendReplyReplyWithContent:(id)arg1 Question:(id)arg2;
-(void)SendQuestionReplyWithContent:(id)arg1 Question:(id)arg2;
-(void)SendQuestionWithContent:(id)arg1;
-(void)updateToolView;
-(void)dealloc;
@end