/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:20 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BuiltinIPList : PBGeneratedMessage {
	unsigned int hasLongConnectIpcount:1; 
	unsigned int hasShortConnectIpcount:1; 
	unsigned int hasSeq:1; 
	unsigned longConnectIpcount; 
	unsigned shortConnectIpcount; 
	unsigned seq; 
	NSMutableArray* mutableLongConnectIplistList; 
	NSMutableArray* mutableShortConnectIplistList; 
}
@property (retain) NSMutableArray* mutableShortConnectIplistList; 
@property (retain) NSMutableArray* mutableLongConnectIplistList; 
@property (assign) unsigned seq; 
@property (assign) BOOL hasSeq; 
@property (assign) unsigned shortConnectIpcount; 
@property (assign) BOOL hasShortConnectIpcount; 
@property (assign) unsigned longConnectIpcount; 
@property (assign) BOOL hasLongConnectIpcount; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(id)shortConnectIplistList;
-(id)longConnectIplistList;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasSeq:(BOOL)arg1;
-(void)setHasShortConnectIpcount:(BOOL)arg1;
-(void)setHasLongConnectIpcount:(BOOL)arg1;
-(id)SetSeq:(unsigned)arg1;
-(id)addShortConnectIplist:(id)arg1;
-(id)addLongConnectIplist:(id)arg1;
-(id)SetShortConnectIpcount:(unsigned)arg1;
-(id)SetLongConnectIpcount:(unsigned)arg1;
-(void)setSeq:(unsigned)arg1;
-(void)setShortConnectIpcount:(unsigned)arg1;
-(void)setLongConnectIpcount:(unsigned)arg1;
-(void)setMutableShortConnectIplistList:(id)arg1;
-(void)setMutableLongConnectIplistList:(id)arg1;
-(id)addShortConnectIplistFromArray:(id)arg1;
-(id)addLongConnectIplistFromArray:(id)arg1;
-(id)init;
-(void)dealloc;
@end