/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:31 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NotifyFromMainCtrlDelegate.h>

@interface CAppObserverCenter : NSObject <NotifyFromMainCtrlDelegate> {
	NSMutableDictionary* m_eventObserverDic; 
	NSMutableDictionary* m_messageObserverDic; 
	NSMutableDictionary* m_pbEventObserverDic; 
}
@property (nonatomic,copy) NSMutableDictionary* m_messageObserverDic; 
-(void)removeEventObserverListItem:(unsigned long)arg1 andValue:(id)arg2;
-(void)removeEventObserverListItemByObject:(id)arg1;
-(void)addEventObserverListItem:(unsigned long)arg1 andValue:(id)arg2;
-(void)NotifyFromMainCtrl:(unsigned long)arg1 MessageInfo:(id)arg2 Event:(unsigned long)arg3;
-(void)removePBEventObserverListItemByObject:(id)arg1;
-(void)removePBEventObserverListItem:(unsigned long)arg1 andValue:(id)arg2;
-(void)addPBEventObserverListItem:(unsigned long)arg1 andValue:(id)arg2;
-(void)removeMessageObserverListItem:(unsigned long)arg1 andValue:(id)arg2;
-(void)addMessageObserverListItem:(unsigned long)arg1 andValue:(id)arg2;
-(void)NotifyFromMainCtrl:(id)arg1 Event:(unsigned long)arg2;
-(void)removeAllPBEventObserverListItem;
-(void)removeAllMessageObserverListItem;
-(void)removeAllEventObserverListItem;
-(id)init;
-(void)dealloc;
@end