/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:13 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CardType : PBGeneratedMessage {
	unsigned int hasStyleType:1; 
	unsigned int hasSubType:1; 
	unsigned int hasCustomizeType:1; 
	unsigned styleType; 
	unsigned subType; 
	unsigned customizeType; 
}
@property (assign) unsigned customizeType; 
@property (assign) BOOL hasCustomizeType; 
@property (assign) unsigned subType; 
@property (assign) BOOL hasSubType; 
@property (assign) unsigned styleType; 
@property (assign) BOOL hasStyleType; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasCustomizeType:(BOOL)arg1;
-(void)setHasSubType:(BOOL)arg1;
-(void)setHasStyleType:(BOOL)arg1;
-(id)SetCustomizeType:(unsigned)arg1;
-(id)SetSubType:(unsigned)arg1;
-(id)SetStyleType:(unsigned)arg1;
-(void)setCustomizeType:(unsigned)arg1;
-(void)setSubType:(unsigned)arg1;
-(void)setStyleType:(unsigned)arg1;
-(id)init;
-(void)dealloc;
@end