/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:50 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CBaseFile : NSObject {
	NSFileHandle* m_fhFile; 
	NSString* m_nsFilePath; 
	unsigned m_uiMode; 
	BOOL m_bOpen; 
}
@property (nonatomic,retain) NSFileHandle* m_fhFile; 
@property (nonatomic,retain) NSString* m_nsFilePath; 
+(BOOL)FileExist:(id)arg1;
+(BOOL)CopyFile:(id)arg1 To:(id)arg2;
+(long)GetFiLeModifyTime:(id)arg1;
+(BOOL)RemoveFile:(id)arg1;
+(long long)GetFileSize:(id)arg1;
+(id)LoadDataFromPath:(id)arg1 Offset:(unsigned long)arg2 Len:(unsigned long)arg3;
+(id)SubFoldersName:(r*)arg1;
+(BOOL)RenameFile:(id)arg1 To:(id)arg2;
+(BOOL)WriteDataToPath:(id)arg1 Offset:(unsigned long)arg2 Data:(id)arg3;
+(BOOL)OverWriteDataToPath:(id)arg1 Data:(id)arg2;
+(BOOL)CreateFile:(id)arg1;
+(void)ClearPath:(id)arg1;
+(BOOL)CreatePath:(id)arg1;
+(void)clearPathUseC:(r*)arg1;
+(long long)FolderSizeAtPath:(r*)arg1;
+(BOOL)SysAppendData:(id)arg1 toPath:(id)arg2;
+(BOOL)SysOverWriteDataToPath:(id)arg1 Data:(id)arg2;
+(BOOL)AppendData:(id)arg1 toPath:(id)arg2;
+(id)LoadDataFromPathEx:(id)arg1 Offset:(unsigned long)arg2 MaxLen:(unsigned long)arg3;
+(BOOL)CreateSymbolLink:(id)arg1 LinkName:(id)arg2;
+(void)ClearPath:(id)arg1 WithOut:(id)arg2;
+(id)SubFilesName:(r*)arg1;
+(BOOL)deleteFileUseC:(r*)arg1;
+(long long)GetFiLeSize:(id)arg1;
-(void)Close;
-(BOOL)Open;
-(BOOL)SetFileInfo:(id)arg1 Mode:(unsigned long)arg2;
-(BOOL)WriteLargeData:(id)arg1;
-(BOOL)WriteData:(id)arg1;
-(unsigned long long)SeekToEndOfFile;
-(BOOL)ReadData:(id)arg1 Len:(unsigned long)arg2;
-(BOOL)Seek:(long long)arg1;
-(void)setM_fhFile:(id)arg1;
-(void)setM_nsFilePath:(id)arg1;
-(BOOL)SetFileSize:(long long)arg1;
-(BOOL)IsOpen;
-(id)init;
-(void)dealloc;
@end