/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:23 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CControlUtil : NSObject {
}
+(float)labelWidth:(id)arg1 maxWidth:(int)arg2 font:(id)arg3;
+(void)makeLabelShadow:(id)arg1;
+(id)showAlert:(id)arg1 message:(id)arg2 delegate:(id)arg3 cancelButtonTitle:(id)arg4;
+(void)showActionSheet:(id)arg1 inView:(id)arg2;
+(id)showAlertEx:(id)arg1 message:(id)arg2 delegate:(id)arg3 cancelButtonTitle:(id)arg4 otherButtonTitle:(id)arg5;
+(float)labelHeight:(id)arg1 maxWidth:(int)arg2 font:(id)arg3;
+(CGSize)labelSizeOfLabel:(id)arg1;
+(id)showAlertEx:(id)arg1 message:(id)arg2 delegate:(id)arg3 confirmButtonTitle:(id)arg4 cancelButtonTitle:(id)arg5;
+(CGRect)autoFitRectForLableAllowMultipleLines:(id)arg1;
+(CGRect)autoFitRectForLable:(id)arg1;
+(_Bool)pointInRect:(CGRect)arg1 point:(CGPoint)arg2 error:(float)arg3;
+(CGSize)labelSizeOfLabel:(id)arg1 maxWidth:(int)arg2;
+(void)showReceiveMemoryWarningAlert;
@end