/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:19 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MessageObserverDelegate.h>
#import <UITextFieldDelegate.h>
#import <UIAlertViewDelegate.h>

@interface CContactVerifyLogic : NSObject <MessageObserverDelegate, UITextFieldDelegate, UIAlertViewDelegate> {
	NSArray* m_arrVerifyContactWrap; 
	UIView* m_parentView; 
	NSString* m_nsVerifyValue; 
	MMLoadingView* m_loadingView; 
	unsigned m_uiOpCode; 
	BOOL m_bFromChatRoom; 
	unsigned m_uiFriendScene; 
	id<contactVerifyLogicDelegate> m_delegate; 
}
@property (assign,nonatomic) id<contactVerifyLogicDelegate> m_delegate; 
-(void)setM_delegate:(id)arg1;
-(void)startWithVerifyContactWrap:(id)arg1 opCode:(unsigned long)arg2 parentView:(id)arg3 fromChatRoom:(BOOL)arg4;
-(void)MessageReturn:(unsigned long)arg1 MessageInfo:(id)arg2 Event:(unsigned long)arg3;
-(id)getAlertMessage;
-(id)getAlertTitle;
-(void)stopLoadingAndShowOK;
-(void)showVerifyAlert;
-(id)getLoadingText;
-(void)handleVerifyOk:(id)arg1;
-(id)getErrorTitle;
-(void)SaveToLocalDB;
-(void)onSendContactVerify:(id)arg1;
-(void)doVerifyByAlertView:(id)arg1;
-(BOOL)doVerify:(id)arg1;
-(BOOL)needSaveToLocalDB;
-(id)getLoadingOkText;
-(float)getTextFieldTopMargin;
-(void)startLoading;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
-(void)stopLoading;
-(void)willPresentAlertView:(id)arg1;
-(id)filterString:(id)arg1;
-(id)init;
-(void)dealloc;
-(void)reset;
@end