/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:37 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CDNDnsInfo : PBGeneratedMessage {
	unsigned int hasFrontId:1; 
	unsigned int hasFrontIpcount:1; 
	unsigned int hasZoneId:1; 
	unsigned int hasZoneIpcount:1; 
	unsigned int hasZoneDomain:1; 
	unsigned int hasAuthKey:1; 
	unsigned int hasVer:1; 
	unsigned int hasUin:1; 
	unsigned int hasExpireTime:1; 
	int frontId; 
	int frontIpcount; 
	int zoneId; 
	int zoneIpcount; 
	NSString* zoneDomain; 
	SKBuiltinBuffer_t* authKey; 
	unsigned ver; 
	unsigned uin; 
	unsigned expireTime; 
	NSMutableArray* mutableFrontIplistList; 
	NSMutableArray* mutableZoneIplistList; 
}
@property (retain) NSMutableArray* mutableZoneIplistList; 
@property (assign) int zoneIpcount; 
@property (assign) BOOL hasZoneIpcount; 
@property (assign) int zoneId; 
@property (assign) BOOL hasZoneId; 
@property (retain) SKBuiltinBuffer_t* authKey; 
@property (assign) BOOL hasAuthKey; 
@property (retain) NSString* zoneDomain; 
@property (assign) BOOL hasZoneDomain; 
@property (retain) NSMutableArray* mutableFrontIplistList; 
@property (assign) int frontIpcount; 
@property (assign) BOOL hasFrontIpcount; 
@property (assign) int frontId; 
@property (assign) BOOL hasFrontId; 
@property (assign) unsigned expireTime; 
@property (assign) BOOL hasExpireTime; 
@property (assign) unsigned uin; 
@property (assign) BOOL hasUin; 
@property (assign) unsigned ver; 
@property (assign) BOOL hasVer; 
+(id)parseFromData:(id)arg1;
-(id)addZoneIplist:(id)arg1;
-(id)SetZoneIpcount:(int)arg1;
-(id)SetZoneId:(int)arg1;
-(id)SetAuthKey:(id)arg1;
-(id)SetZoneDomain:(id)arg1;
-(id)addFrontIplist:(id)arg1;
-(id)SetFrontIpcount:(int)arg1;
-(id)SetFrontId:(int)arg1;
-(id)SetExpireTime:(unsigned)arg1;
-(id)SetVer:(unsigned)arg1;
-(id)SetUin:(unsigned)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasZoneIpcount:(BOOL)arg1;
-(void)setHasZoneId:(BOOL)arg1;
-(void)setHasAuthKey:(BOOL)arg1;
-(void)setHasZoneDomain:(BOOL)arg1;
-(void)setHasFrontIpcount:(BOOL)arg1;
-(void)setHasFrontId:(BOOL)arg1;
-(void)setHasExpireTime:(BOOL)arg1;
-(void)setHasVer:(BOOL)arg1;
-(id)zoneIplistList;
-(id)frontIplistList;
-(void)setZoneIpcount:(int)arg1;
-(void)setZoneId:(int)arg1;
-(void)setFrontIpcount:(int)arg1;
-(void)setFrontId:(int)arg1;
-(void)setExpireTime:(unsigned)arg1;
-(void)setVer:(unsigned)arg1;
-(void)setMutableZoneIplistList:(id)arg1;
-(void)setAuthKey:(id)arg1;
-(void)setZoneDomain:(id)arg1;
-(void)setMutableFrontIplistList:(id)arg1;
-(void)setHasUin:(BOOL)arg1;
-(void)setUin:(unsigned)arg1;
-(id)addZoneIplistFromArray:(id)arg1;
-(id)addFrontIplistFromArray:(id)arg1;
-(id)init;
-(void)dealloc;
@end