/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:04 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CdnProgressInfo : NSObject {
	NSString* m_nsClientMsgID; 
	int m_nTotalLength; 
	int m_nFinishedLegth; 
	int m_nStatus; 
}
@property (assign,nonatomic) int m_nStatus; 
@property (assign,nonatomic) int m_nFinishedLegth; 
@property (assign,nonatomic) int m_nTotalLength; 
@property (nonatomic,retain) NSString* m_nsClientMsgID; 
-(void)setM_nsClientMsgID:(id)arg1;
-(void)setM_nStatus:(long)arg1;
-(void)setM_nFinishedLegth:(long)arg1;
-(void)setM_nTotalLength:(long)arg1;
-(id)init;
-(void)dealloc;
@end