/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:08 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CdnTaskInfo : NSObject {
	NSString* m_nsClientMsgID; 
	CMessageWrap* m_wrapMsg; 
	NSString* m_nsChatName; 
	unsigned m_uiThumbSize; 
	BOOL m_bHD; 
	unsigned m_uiFinishedLen; 
	unsigned m_uiTotalLen; 
	unsigned long long m_ui64StartTime; 
	int m_nRetCode; 
	BOOL m_bUpload; 
	NSString* m_nsCdnStatInfo; 
}
@property (nonatomic,retain) NSString* m_nsCdnStatInfo; 
@property (assign,nonatomic) BOOL m_bUpload; 
@property (assign,nonatomic) int m_nRetCode; 
@property (assign,nonatomic) unsigned long long m_ui64StartTime; 
@property (assign,nonatomic) unsigned m_uiTotalLen; 
@property (assign,nonatomic) unsigned m_uiFinishedLen; 
@property (assign,nonatomic) BOOL m_bHD; 
@property (assign,nonatomic) unsigned m_uiThumbSize; 
@property (nonatomic,retain) NSString* m_nsChatName; 
@property (nonatomic,retain) CMessageWrap* m_wrapMsg; 
@property (nonatomic,retain) NSString* m_nsClientMsgID; 
-(void)setM_wrapMsg:(id)arg1;
-(void)setM_nsChatName:(id)arg1;
-(void)setM_uiTotalLen:(unsigned long)arg1;
-(void)setM_nRetCode:(int)arg1;
-(id)GetStatInfo;
-(void)setM_ui64StartTime:(unsigned long long)arg1;
-(void)setM_nsClientMsgID:(id)arg1;
-(void)setM_nsCdnStatInfo:(id)arg1;
-(void)setM_uiThumbSize:(unsigned long)arg1;
-(void)setM_bUpload:(BOOL)arg1;
-(void)setM_uiFinishedLen:(unsigned long)arg1;
-(void)setM_bHD:(BOOL)arg1;
-(id)init;
-(void)dealloc;
@end