/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:17 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CdnUploadTaskInfo : NSObject {
	NSString* m_nsClientMsgID; 
	NSString* m_nsFileId; 
	NSString* m_nsAesKey; 
	int m_nFileLength; 
	int m_nMidimgLength; 
	NSString* m_nsTransInfo; 
	int m_nRetCode; 
	NSString* m_nsChatName; 
}
@property (nonatomic,retain) NSString* m_nsChatName; 
@property (assign,nonatomic) int m_nRetCode; 
@property (nonatomic,retain) NSString* m_nsTransInfo; 
@property (assign,nonatomic) int m_nMidimgLength; 
@property (assign,nonatomic) int m_nFileLength; 
@property (nonatomic,retain) NSString* m_nsAesKey; 
@property (nonatomic,retain) NSString* m_nsFileId; 
@property (nonatomic,retain) NSString* m_nsClientMsgID; 
-(void)setM_nsChatName:(id)arg1;
-(void)setM_nRetCode:(long)arg1;
-(void)setM_nsClientMsgID:(id)arg1;
-(void)setM_nMidimgLength:(long)arg1;
-(void)setM_nFileLength:(long)arg1;
-(void)setM_nsAesKey:(id)arg1;
-(void)setM_nsFileId:(id)arg1;
-(void)setM_nsTransInfo:(id)arg1;
-(id)init;
-(void)dealloc;
@end