/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:46 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IMMFacebookMgrExt.h>

@interface CFriendAssistContactInfoAssist : CBaseContactInfoAssist <IMMFacebookMgrExt> {
	struct map<unsigned int,unsigned int,stdless<unsigned int>,stdallocator<stdpair<const unsigned int, unsigned int> > > m_mapCellType; 
	struct map<unsigned int,unsigned int,stdless<unsigned int>,stdallocator<stdpair<const unsigned int, unsigned int> > > m_mapSectionType; 
}
-(void)initTableView;
-(void)onUnBindFacebookFinish:(unsigned long)arg1;
-(void)onBindFacebookFinish:(unsigned long)arg1;
-(void)showBindView;
-(void)initHeaderView;
-(void)initFooterView;
-(void)recommendPhoneChanged:(id)arg1;
-(void)recommendQQChanged:(id)arg1;
-(void)makeCell:(id)arg1 row:(unsigned)arg2 section:(unsigned long)arg3;
-(void)makeRecommendCell:(id)arg1 row:(unsigned)arg2;
-(void)doSetPluginConfig:(unsigned long)arg1 on:(BOOL)arg2 bitset:(unsigned long)arg3;
-(void)recommendFacebookChanged:(id)arg1;
-(void)reloadData;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
-(void)dealloc;
-(void).cxx_destruct;
-(id).cxx_construct;
@end