/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:09 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CGroupDB : NSObject {
	CMMDB* m_oMMDB; 
	NSRecursiveLock* m_oLock; 
	NSString* m_nsDocPath; 
}
-(BOOL)QuitGroup:(id)arg1 withUsrName:(id)arg2;
-(BOOL)AddGroupMember:(id)arg1 withMemberList:(id)arg2;
-(BOOL)SetGroupTopic:(id)arg1 withTopic:(id)arg2;
-(BOOL)DeleteGroupMember:(id)arg1 withMemberList:(id)arg2;
-(void)initDB:(id)arg1 withLock:(id)arg2;
-(id)GetGroupMember:(id)arg1;
-(id)GetMMDB;
-(id)init;
-(void)dealloc;
@end