/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:47 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CmdItem : PBGeneratedMessage {
	unsigned int hasCmdId:1; 
	unsigned int hasCmdBuf:1; 
	int cmdId; 
	SKBuiltinBuffer_t* cmdBuf; 
}
@property (retain) SKBuiltinBuffer_t* cmdBuf; 
@property (assign) BOOL hasCmdBuf; 
@property (assign) int cmdId; 
@property (assign) BOOL hasCmdId; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasCmdBuf:(BOOL)arg1;
-(void)setHasCmdId:(BOOL)arg1;
-(id)SetCmdBuf:(id)arg1;
-(id)SetCmdId:(int)arg1;
-(void)setCmdId:(int)arg1;
-(void)setCmdBuf:(id)arg1;
-(id)init;
-(void)dealloc;
@end