/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:52 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol PBMessageObserverDelegate
@required
-(void)MessageReturn(id):arg1 Event(unsigned long):arg2 ;
-(void)MessageReturn(id):arg1 Event(unsigned long):arg2 ;
@end

@protocol CNetworkStatusExt
@required
-(void)ReachabilityChange(unsigned long):arg1 ;
-(void)ReachabilityChange(unsigned long):arg1 ;
@end
