/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:45 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MMService.h>
#import <MessageObserverDelegate.h>
#import <IAudioToMessageExt.h>
#import <CNetworkStatusExt.h>
#import <IEmoticonDownloadExt.h>

@interface CNetworkStatusMgr : MMService <MMService, MessageObserverDelegate, IAudioToMessageExt, CNetworkStatusExt, IEmoticonDownloadExt> {
	BOOL m_bConnecting; 
	BOOL m_bConnected; 
	BOOL m_bReadToGettingData; 
	unsigned m_uiMsgIdForVoiceMsgToDownload; 
	BOOL m_bDownloadingEmoticon; 
	BOOL m_bReadOnceAgain; 
	unsigned m_uiConnnectType; 
	unsigned m_uiShortChannelFailCount; 
	unsigned m_uiLastReportTime; 
	struct timeval m_tvLastGettingDataTime; 
	CNetworkStatusReportArchive* m_reportArchive; 
	struct vector<long unsigned int,stdallocator<long unsigned int> > m_vecMesssageIdToListen; 
	int m_eNetworkStatusType; 
	COOBData* m_dtOOB; 
}
-(void)MessageReturn:(unsigned long)arg1 MessageInfo:(id)arg2 Event:(unsigned long)arg3;
-(void)onServiceTerminate;
-(void)onServiceEnterBackground;
-(unsigned long)getNetworkStatusType;
-(void)initMessageIdToListen;
-(void)unListenMessageId;
-(void)unregExt;
-(void)regExt;
-(id)GetOOBData;
-(id)GetOOBUrl;
-(void)setReadToGettingData;
-(void)ReachabilityChange:(unsigned long)arg1;
-(void)doReportIpxx:(id)arg1;
-(void)OnErrorByReceiver:(id)arg1 ErrNo:(int)arg2;
-(void)OnAddMessageByReceiver:(id)arg1;
-(void)OnEmoticonDownload:(unsigned long)arg1;
-(void)zeroEmocticonDownloadingStatus;
-(void)handleVoiceDowdload:(id)arg1 error:(BOOL)arg2;
-(void)handleReportLongUnConnectCount;
-(void)handleSyncBegin;
-(void)handleNetworkStatusChange:(unsigned long)arg1;
-(void)loadNetworkStatusReportArchive;
-(void)zeroVoiceMsgToDownload;
-(void)handleSyncEnd;
-(void)checkCallStatusChangedExt;
-(void)callDisconnectStatusChangedExt;
-(void)handleReport:(int)arg1;
-(void)translateStatus;
-(void)translateStatusLongConnect;
-(BOOL)isDuringSync;
-(void)handleReportDisconnected:(int)arg1;
-(void)handleReportGettingData:(int)arg1;
-(void)realCalDisconnected;
-(void)doReportNetworkStatus;
-(struct timeval)getCurTimeVal;
-(BOOL)isNeedReport;
-(void)translateStatusLongUnConnect;
-(id)init;
-(void)dealloc;
-(void).cxx_destruct;
-(id).cxx_construct;
@end