/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:15 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WCSelectorViewDelegate.h>
#import <WCSelectorViewDataSource.h>
#import <WCSelectContactDelegate.h>
#import <WCEditMemberPannelDelegate.h>
#import <WCEditMemberPannelDataSource.h>
#import <WCContactItemDeleteViewDelegate.h>

@interface ContactsSelectorController : NSObject <WCSelectorViewDelegate, WCSelectorViewDataSource, WCSelectContactDelegate, WCEditMemberPannelDelegate, WCEditMemberPannelDataSource, WCContactItemDeleteViewDelegate> {
	NSMutableArray* _arrFilteredContacts; 
	NSMutableArray* _arrContacts; 
	WCSelectorView* _selectorView; 
	WCEditMemberPannel* _editMemberPannel; 
	NSMutableDictionary* _dicContactItemDeleteView; 
	UINavigationController* _navigationController; 
	id<SelectorControllerDelegate> _delegate; 
	id<ContactsSelectorControllerDelegate> _selectDelegate; 
}
@property (assign,nonatomic) id<ContactsSelectorControllerDelegate> selectDelegate; 				//@synthesize selectDelegate=_selectDelegate - In the implementation block
@property (assign,nonatomic) id<SelectorControllerDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) UINavigationController* navigationController; 				//@synthesize navigationController=_navigationController - In the implementation block
@property (nonatomic,retain) WCEditMemberPannel* editMemberPannel; 				//@synthesize editMemberPannel=_editMemberPannel - In the implementation block
@property (nonatomic,retain) WCSelectorView* selectorView; 				//@synthesize selectorView=_selectorView - In the implementation block
@property (nonatomic,retain) NSMutableArray* arrContacts; 				//@synthesize arrContacts=_arrContacts - In the implementation block
@property (nonatomic,retain) NSMutableArray* arrFilteredContacts; 				//@synthesize arrFilteredContacts=_arrFilteredContacts - In the implementation block
-(id)getViewController;
-(void)setNavigationController:(id)arg1;
-(void)setArrContacts:(id)arg1;
-(void)OnWCSelectUsrNameList:(id)arg1;
-(void)onClickWholeView;
-(BOOL)shouldShowDeleteView;
-(unsigned)numbersOfViews;
-(CGSize)sizeForViews;
-(void)setArrFilteredContacts:(id)arg1;
-(void)setSelectDelegate:(id)arg1;
-(void)setEditMemberPannel:(id)arg1;
-(void)setSelectorView:(id)arg1;
-(unsigned)numberOfItems:(id)arg1;
-(id)editMemberPannel:(id)arg1 viewForItem:(unsigned)arg2;
-(void)onClickAddButton:(id)arg1;
-(void)onClickDeleteButton:(id)arg1 withContact:(id)arg2;
-(void)onClickHeadImage:(id)arg1 withContact:(id)arg2;
-(void)removeContact:(id)arg1;
-(id)viewAtIndex:(unsigned)arg1;
-(id)init;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
@end