/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:13 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IContactMgrExt.h>
#import <PluginUtilExt.h>

@interface ContactsDataLogic : NSObject <IContactMgrExt, PluginUtilExt> {
	id<ContactsDataLogicDelegate> m_delegate; 
	NSMutableDictionary* m_dicAllContacts; 
	NSMutableArray* m_arrAllKey; 
	NSMutableArray* m_arrFilteredContacts; 
	unsigned m_uiScene; 
	BOOL m_bHasNormalContact; 
	BOOL m_bSort; 
	BOOL m_bNeedReload; 
}
@property (assign,nonatomic) BOOL m_bSort; 
@property (nonatomic,copy) BOOL m_bHasNormalContact; 
@property (assign,nonatomic) unsigned m_uiScene; 
@property (assign,nonatomic) id<ContactsDataLogicDelegate> m_delegate; 
-(void)setM_delegate:(id)arg1;
-(void)setM_uiScene:(unsigned long)arg1;
-(id)addSectionKey:(id)arg1;
-(void)deleteContact:(id)arg1 deleteInDB:(BOOL)arg2;
-(void)onContactListUpdate:(unsigned long)arg1;
-(void)onDeleteContact:(id)arg1;
-(void)onModifyContact:(id)arg1;
-(id)getFilteredContacts;
-(void)doSearch:(id)arg1 Pre:(BOOL)arg2;
-(id)initWithScene:(unsigned long)arg1 delegate:(id)arg2;
-(id)getContactsArrayWith:(id)arg1;
-(id)getKeysArray;
-(id)initWithScene:(unsigned long)arg1 delegate:(id)arg2 sort:(BOOL)arg3;
-(void)pluginsChanged;
-(void)filterOnlyWeixinContact:(id)arg1;
-(void)filterMutilSelectWithBakChatFilter:(id)arg1;
-(void)filterSelectWithVerifyedContacts:(id)arg1;
-(void)filterSelectWithBrandContacts:(id)arg1;
-(void)filterHistoryGroupContacts:(id)arg1;
-(void)filterGroupContacts:(id)arg1;
-(void)filterMultiSelectContacts:(id)arg1;
-(void)filterSelectContacts:(id)arg1;
-(void)filterContactsViewContacts:(id)arg1;
-(id)addHiddenSectionKey:(id)arg1;
-(void)processOnModifyContact;
-(void)unInstallPlugin:(id)arg1;
-(BOOL)reloadContacts;
-(void)onUnInstallPlugin:(int)arg1;
-(void)onInstallPlugin:(int)arg1;
-(void)setM_bSort:(BOOL)arg1;
-(BOOL)shouldShowBrandGroup;
-(void)addContact:(id)arg1;
-(void)sort;
-(void)dealloc;
@end