/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:07 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ContactsItemCell : MMTableViewCell {
}
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
@end