/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:43 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CQQContactInfoAssist : CBaseContactInfoAssist {
	struct map<unsigned int,unsigned int,stdless<unsigned int>,stdallocator<stdpair<const unsigned int, unsigned int> > > m_mapCellToCellType; 
}
-(void)initHeaderView;
-(void)updateInstallView;
-(void)makeCell:(id)arg1 row:(unsigned)arg2 section:(unsigned long)arg3;
-(void)installPlugin;
-(void)makeReadMsgCell:(id)arg1;
-(void)makeShowWeixinOnline:(id)arg1;
-(void)makeShowInContactCell:(id)arg1 row:(unsigned long)arg2;
-(void)makeSendQQMsgCell:(id)arg1;
-(void)showWeixinOnline:(id)arg1;
-(void)setQQOfflineMsgOpen:(BOOL)arg1 configType:(unsigned long)arg2 status:(unsigned long)arg3;
-(void)reloadQQOfflineMap;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void).cxx_destruct;
-(id).cxx_construct;
@end