/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:27 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>

@interface CrashReportInfo : NSObject <NSCoding> {
	unsigned m_uiVersion; 
	unsigned m_uiReportCount; 
	unsigned m_uiReportSuccessCount; 
}
@property (assign,nonatomic) unsigned m_uiReportSuccessCount; 
@property (assign,nonatomic) unsigned m_uiReportCount; 
@property (assign,nonatomic) unsigned m_uiVersion; 
-(void)setM_uiReportSuccessCount:(unsigned long)arg1;
-(void)setM_uiReportCount:(unsigned long)arg1;
-(void)setM_uiVersion:(unsigned long)arg1;
-(void)preInit;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)init;
-(void)dealloc;
@end