/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:42 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol crashReportConnectionDelegate
@required
-(void)onUploadCrashCompleted(BOOL):arg1 CrashWrap(id):arg2 ;
-(void)onUploadCrashCompleted(BOOL):arg1 CrashWrap(id):arg2 ;
@end
