/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:08 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CSXContactInfoAssist : CBaseContactInfoAssist {
}
-(void)initHeaderView;
-(void)makeCellInfoInternal:(id)arg1 col:(id)arg2 value:(id)arg3 valueGray:(BOOL)arg4;
-(void)pushPrivateMsgSwitchChanged:(id)arg1;
-(void)makeCell:(id)arg1 row:(unsigned)arg2 section:(unsigned long)arg3;
-(void)installPlugin;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
@end