/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:06 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>

@interface CUpdateInfo : NSObject <NSCoding> {
	unsigned m_uiNewVersion; 
	NSString* m_nsDescription; 
	BOOL m_bShowInTab; 
	BOOL m_bShowInSetting; 
	unsigned m_uiLastShowAlertTime; 
	unsigned m_uiNewVersionUpdateTime; 
	unsigned m_uiSysNoticeVersion; 
	unsigned m_uiSysNoticeCount; 
	BOOL m_bSysNoticeShowInTab; 
}
@property (assign,nonatomic) BOOL m_bSysNoticeShowInTab; 
@property (assign,nonatomic) unsigned m_uiSysNoticeCount; 
@property (assign,nonatomic) unsigned m_uiSysNoticeVersion; 
@property (assign,nonatomic) unsigned m_uiNewVersionUpdateTime; 
@property (assign,nonatomic) unsigned m_uiLastShowAlertTime; 
@property (assign,nonatomic) BOOL m_bShowInTab; 
@property (assign,nonatomic) BOOL m_bShowInSetting; 
@property (nonatomic,retain) NSString* m_nsDescription; 
@property (assign,nonatomic) unsigned m_uiNewVersion; 
+(void)updateSysNotice:(id)arg1;
-(void)setM_bSysNoticeShowInTab:(BOOL)arg1;
-(void)setM_bShowInTab:(BOOL)arg1;
-(void)setM_uiSysNoticeCount:(unsigned long)arg1;
-(void)setM_uiLastShowAlertTime:(unsigned long)arg1;
-(void)setM_nsDescription:(id)arg1;
-(void)setM_uiNewVersionUpdateTime:(unsigned long)arg1;
-(void)setM_bShowInSetting:(BOOL)arg1;
-(void)setM_uiNewVersion:(unsigned long)arg1;
-(void)copyFromUpdateInfo:(id)arg1;
-(void)setM_uiSysNoticeVersion:(unsigned long)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)init;
-(void)dealloc;
@end