/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:07 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CustomizedInfo : PBGeneratedMessage {
	unsigned int hasExternalInfo:1; 
	unsigned int hasBrandInfo:1; 
	unsigned int hasBrandIconUrl:1; 
	unsigned int hasBrandFlag:1; 
	NSString* externalInfo; 
	NSString* brandInfo; 
	NSString* brandIconUrl; 
	unsigned brandFlag; 
}
@property (retain) NSString* brandIconUrl; 
@property (assign) BOOL hasBrandIconUrl; 
@property (retain) NSString* brandInfo; 
@property (assign) BOOL hasBrandInfo; 
@property (retain) NSString* externalInfo; 
@property (assign) BOOL hasExternalInfo; 
@property (assign) unsigned brandFlag; 
@property (assign) BOOL hasBrandFlag; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)setHasBrandIconUrl:(BOOL)arg1;
-(void)setHasExternalInfo:(BOOL)arg1;
-(id)SetBrandIconUrl:(id)arg1;
-(id)SetExternalInfo:(id)arg1;
-(void)setBrandIconUrl:(id)arg1;
-(void)setExternalInfo:(id)arg1;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasBrandInfo:(BOOL)arg1;
-(void)setHasBrandFlag:(BOOL)arg1;
-(id)SetBrandInfo:(id)arg1;
-(id)SetBrandFlag:(unsigned)arg1;
-(void)setBrandFlag:(unsigned)arg1;
-(void)setBrandInfo:(id)arg1;
-(id)init;
-(void)dealloc;
@end