/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:00 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol CustomMenuToolViewDelegate
@required
-(void)onChangeToExchang(id):arg1 ;
-(void)onJumpToWebView(id):arg1 ;
-(void)onClickCommandBtn(id):arg1 ;
-(void)onSubMenuPresentWithIndex(int):arg1 ArrowX(float):arg2 ;
-(void)changeToInputMode;
-(void)onSubMenuDismiss;
-(void)onChangeToExchang(id):arg1 ;
-(void)onJumpToWebView(id):arg1 ;
-(void)onClickCommandBtn(id):arg1 ;
-(void)onSubMenuPresentWithIndex(int):arg1 ArrowX(float):arg2 ;
-(void)changeToInputMode;
-(void)onSubMenuDismiss;
@end
