/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:35 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIHorizontalTableViewDelegate.h>
#import <UIHorizontalTableViewDataSource.h>
#import <UIScrollViewDelegate.h>

@interface CustomMenuToolView : UIView <UIHorizontalTableViewDelegate, UIHorizontalTableViewDataSource, UIScrollViewDelegate> {
	id<CustomMenuToolViewDelegate> m_delegate; 
	UIHorizontalTableView* m_tableView; 
	NSMutableArray* m_menuList; 
	NSMutableArray* m_tableDatas; 
	int lastClickMenuIndex; 
}
@property (assign,nonatomic) id<CustomMenuToolViewDelegate> m_delegate; 
-(void)setM_delegate:(id)arg1;
-(float)getFontSize;
-(float)horizontalTableView:(id)arg1 widthForColumnAtIndex:(unsigned)arg2;
-(int)capacityForTableView;
-(void)reloadHorizontalTableViewData;
-(BOOL)isMenusNumerous;
-(void)changeToInputMode;
-(void)loadEmptyImageView;
-(void)loadSeparateLine;
-(void)loadSubView;
-(void)horizontalTableView:(id)arg1 didSelectColumnAtIndex:(unsigned)arg2;
-(id)horizontalTableView:(id)arg1 viewForColumnAtIndex:(unsigned)arg2;
-(unsigned)numberOfColumnsInHorizontalTableView:(id)arg1;
-(int)getVisibleMenuCount;
-(void)resetLastClickMenuIndex;
-(id)initWithMenuList:(id)arg1;
-(void)scrollViewDidScroll:(id)arg1;
-(void)dealloc;
@end