/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:15 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CustomMenuButton : UIButton {
	NSString* m_btnId; 
	NSString* m_btnKey; 
	NSString* m_btnName; 
	NSString* m_btnValue; 
	int m_btnType; 
}
@property (assign,nonatomic) int m_btnType; 
@property (nonatomic,retain) NSString* m_btnValue; 
@property (nonatomic,retain) NSString* m_btnName; 
@property (nonatomic,retain) NSString* m_btnKey; 
@property (nonatomic,retain) NSString* m_btnId; 
+(int)localCustomType2ServerType:(int)arg1;
-(void)setM_btnName:(id)arg1;
-(void)setM_btnValue:(id)arg1;
-(void)setM_btnKey:(id)arg1;
-(void)setM_btnId:(id)arg1;
-(void)setM_btnType:(int)arg1;
-(id)init;
-(void)dealloc;
@end