/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:52 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface DisturbSetting : PBGeneratedMessage {
	unsigned int hasNightTime:1; 
	unsigned int hasAllDayTime:1; 
	unsigned int hasNightSetting:1; 
	unsigned int hasAllDaySetting:1; 
	DisturbTimeSpan* nightTime; 
	DisturbTimeSpan* allDayTime; 
	unsigned nightSetting; 
	unsigned allDaySetting; 
}
@property (retain) DisturbTimeSpan* allDayTime; 
@property (assign) BOOL hasAllDayTime; 
@property (assign) unsigned allDaySetting; 
@property (assign) BOOL hasAllDaySetting; 
@property (retain) DisturbTimeSpan* nightTime; 
@property (assign) BOOL hasNightTime; 
@property (assign) unsigned nightSetting; 
@property (assign) BOOL hasNightSetting; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasAllDayTime:(BOOL)arg1;
-(void)setHasAllDaySetting:(BOOL)arg1;
-(void)setHasNightTime:(BOOL)arg1;
-(void)setHasNightSetting:(BOOL)arg1;
-(id)SetAllDayTime:(id)arg1;
-(id)SetAllDaySetting:(unsigned)arg1;
-(id)SetNightTime:(id)arg1;
-(id)SetNightSetting:(unsigned)arg1;
-(void)setAllDaySetting:(unsigned)arg1;
-(void)setNightSetting:(unsigned)arg1;
-(void)setAllDayTime:(id)arg1;
-(void)setNightTime:(id)arg1;
-(id)init;
-(void)dealloc;
@end