/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:16 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface DownloadImageInfo : NSObject {
	CMessageWrap* m_wrapMsg; 
	unsigned m_uiTotalLen; 
	unsigned m_uiStartPos; 
	BOOL m_bDownloadHD; 
	NSString* m_nsChatName; 
	CUploadImgWrap* m_wrapDownload; 
	unsigned m_uiNotifyPartLen; 
	unsigned m_uiNotifyTotalLen; 
	unsigned long long m_ui64StartTime; 
	int m_nRetCode; 
}
@property (assign,nonatomic) int m_nRetCode; 
@property (assign,nonatomic) unsigned long long m_ui64StartTime; 
@property (assign,nonatomic) unsigned m_uiNotifyTotalLen; 
@property (assign,nonatomic) unsigned m_uiNotifyPartLen; 
@property (nonatomic,retain) NSString* m_nsChatName; 
@property (assign,nonatomic) BOOL m_bDownloadHD; 
@property (assign,nonatomic) unsigned m_uiStartPos; 
@property (assign,nonatomic) unsigned m_uiTotalLen; 
@property (nonatomic,retain) CMessageWrap* m_wrapMsg; 
-(void)setM_wrapMsg:(id)arg1;
-(void)setM_nsChatName:(id)arg1;
-(void)setM_uiStartPos:(unsigned long)arg1;
-(void)setM_uiTotalLen:(unsigned long)arg1;
-(void)SetTotalLen:(unsigned long)arg1;
-(void)NotifyPartLen:(unsigned long)arg1 TotalLen:(unsigned long)arg2;
-(void)setM_nRetCode:(int)arg1;
-(id)GetStatInfo;
-(void)NotifyOffset;
-(id)GenDownloadInfo;
-(void)setM_ui64StartTime:(unsigned long long)arg1;
-(void)UpdateInfo;
-(void)setM_bDownloadHD:(BOOL)arg1;
-(BOOL)IsSameInfo:(id)arg1;
-(void)setM_uiNotifyPartLen:(unsigned long)arg1;
-(void)setM_uiNotifyTotalLen:(unsigned long)arg1;
-(id)init;
-(void)dealloc;
@end