/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:05 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface DownloadMediaWrap : NSObject {
	WCMediaItem* mediaItem; 
	int downloadType; 
	NSString* downloadID; 
	int downloadSource; 
	BOOL isDownloading; 
	UIImage* resultImage; 
}
@property (nonatomic,copy) NSString* downloadID; 
@property (nonatomic,retain) UIImage* resultImage; 
@property (assign,nonatomic) BOOL isDownloading; 
@property (nonatomic,copy) int downloadSource; 
@property (assign,nonatomic) int downloadType; 
@property (nonatomic,retain) WCMediaItem* mediaItem; 
-(void)setResultImage:(id)arg1;
-(void)setIsDownloading:(BOOL)arg1;
-(id)initWithMediaItem:(id)arg1 downloadType:(int)arg2;
-(void)setDownloadType:(int)arg1;
-(void)setMediaItem:(id)arg1;
-(void)dealloc;
@end