/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:21 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MMTransparentButtonDelegate.h>

@interface EmojiEmoticonViewController : BaseEmoticonViewController <MMTransparentButtonDelegate> {
	NSArray* _arrEmojiDescriptions; 
	int _iCurSelection; 
}
-(void)MMTransparentButton_touchesEnded:(id)arg1 withEvent:(id)arg2;
-(void)MMTransparentButton_touchesMoved:(id)arg1 withEvent:(id)arg2;
-(int)longPressModeAtIndex:(unsigned long)arg1;
-(void)onTipsHide;
-(void)didReleaseLongPressEmoticonAtIndex:(unsigned long)arg1;
-(void)didSelectEmoticonAtIndex:(unsigned long)arg1;
-(id)descriptionForEmoticonAtIndex:(unsigned long)arg1;
-(id)viewForEmoticonAtIndex:(unsigned long)arg1;
-(unsigned long)numberOfCols;
-(unsigned long)numberOfEmoticons;
-(void)OnEmoticonClicked:(id)arg1;
-(void)OnEmoticonDelete:(id)arg1;
-(void)sendEmojiEmoticonAtIndex:(unsigned long)arg1;
-(unsigned long)numberOfRows;
-(void)viewDidLoad;
-(id)init;
-(void)dealloc;
@end