/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:39 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IEmoticonMgrExt.h>
#import <EmojiArtPreviewControllerDelegate.h>
#import <IMsgExt.h>

@interface EmojiArtEmoticonViewController : BaseEmoticonViewController <IEmoticonMgrExt, EmojiArtPreviewControllerDelegate, IMsgExt> {
	unsigned _iCurSelection; 
	NSArray* _arrEmojiCatalogs; 
}
-(void)setViews;
-(void)onEmojiCatalogButtonClicked:(id)arg1;
-(void)OnUpdateEmojiCatalog;
-(void)didSelectEmojiArt:(id)arg1;
-(void)viewDidLoad;
-(void)dealloc;
@end