/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:39 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol IEmoticonMgrExt
@optional
-(void)OnUpdateEmojiCatalog;
-(void)OnUpdateEmoticonList;
@end

@protocol EmojiArtPreviewControllerDelegate
@optional
-(void)didSelectEmojiArt(id):arg1 ;
@end
