/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:48 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIScrollViewDelegate.h>
#import <scrollViewDelegate.h>

@interface EmoticonSelectorView : UIView <UIScrollViewDelegate, scrollViewDelegate> {
	id<EmoticonSelectorViewDelegate> _delegate; 
	id<EmoticonSelectorViewDataSource> _dataSource; 
	MMScrollView* _scrollView; 
	UIPageControl* _pageController; 
	UIImageView* m_tipsView; 
	unsigned _iCurSelection; 
	BOOL bPageControlUsed; 
	unsigned iCount; 
	unsigned iRow; 
	unsigned iCol; 
	unsigned iPage; 
	unsigned iTouchBeganTime; 
	BOOL isLayout; 
	BOOL bIsLongPressedCalled; 
	UIImageView* tipsView; 
	BOOL _editing; 
}
@property (assign,nonatomic) BOOL editing; 				//@synthesize editing=_editing - In the implementation block
@property (assign,nonatomic) id<EmoticonSelectorViewDataSource> dataSource; 				//@synthesize dataSource=_dataSource - In the implementation block
@property (assign,nonatomic) id<EmoticonSelectorViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
-(void)touchesCancelled_ScrollView:(id)arg1 withEvent:(id)arg2;
-(void)touchesEnded_ScrollView:(id)arg1 withEvent:(id)arg2;
-(void)touchesMoved_ScrollView:(id)arg1 withEvent:(id)arg2;
-(void)touchesBegan_ScrollView:(id)arg1 withEvent:(id)arg2;
-(void)resetView;
-(unsigned long)calculateEmoticonOrder:(CGPoint)arg1;
-(void)showNoTips;
-(void)onLongPress:(id)arg1;
-(BOOL)pointInScrollView:(CGPoint)arg1;
-(void)showTips;
-(void)showMenuItem;
-(void)showLargeTips;
-(void)showSmallTips;
-(void)onPageControllerChangePage:(id)arg1;
-(void)OnClickDeleteBtn:(id)arg1;
-(CGRect)calculateEmoticonViewFrameAtIndex:(unsigned long)arg1;
-(void)onLocalMemoryWarning;
-(void)scrollToBottom;
-(void)setDataSource:(id)arg1;
-(void)layoutSubviews;
-(void)scrollViewDidScroll:(id)arg1;
-(void)scrollViewWillBeginDragging:(id)arg1;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
-(void)scrollViewDidEndDecelerating:(id)arg1;
-(BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
-(BOOL)canBecomeFirstResponder;
-(void)setEditing:(BOOL)arg1;
-(id)init;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
@end