/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:05 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol EmoticonSelectorViewDelegate
@optional
-(void)commitEditingStyleForRowAtIndex(unsigned long):arg1 ;
-(void)onTipsHide;
-(void)didClickMenuItemAtIndex(unsigned long):arg1 withEmoticonIndex(unsigned long):arg2 ;
-(void)didReleaseLongPressEmoticonAtIndex(unsigned long):arg1 ;
-(void)didLongPressOnEmoticonAtIndex(unsigned long):arg1 ;
-(void)didSelectEmoticonAtIndex(unsigned long):arg1 ;
-(id)getMenuItemArray;
-(id)scrollViewBackground;
@required
-(int)longPressModeAtIndex(unsigned long):arg1 ;
-(int)longPressModeAtIndex(unsigned long):arg1 ;
@end

@protocol EmoticonSelectorViewDataSource
@optional
-(BOOL)canEditEmoticonAtIndex(unsigned long):arg1 ;
-(id)GetEmoticonView;
@required
-(id)descriptionForEmoticonAtIndex(unsigned long):arg1 ;
-(id)viewForEmoticonAtIndex(unsigned long):arg1 ;
-(unsigned long)numberOfCols;
-(unsigned long)numberOfRows;
-(unsigned long)numberOfEmoticons;
-(id)descriptionForEmoticonAtIndex(unsigned long):arg1 ;
-(id)viewForEmoticonAtIndex(unsigned long):arg1 ;
-(unsigned long)numberOfCols;
-(unsigned long)numberOfRows;
-(unsigned long)numberOfEmoticons;
@end
