/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:24 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MMImgageBrowseViewDelegate.h>
#import <UIActionSheetDelegate.h>

@interface EmoticonMsgBrowseViewController : MMUIViewController <MMImgageBrowseViewDelegate, UIActionSheetDelegate> {
	MMImageBrowseView* m_imageView; 
	MMAnimationTipView* m_tipView; 
	CMessageWrap* m_wrapMsg; 
	CEmoticonWrap* m_wrapEmoticon; 
	id m_singleTapOnNav; 
}
@property (nonatomic,retain) id m_singleTapOnNav; 
-(void)initView;
-(void)showStatusBar;
-(void)willAppear;
-(void)hideStatusBar;
-(void)willDisapper;
-(void)initImageView;
-(id)initWithMsgWrap:(id)arg1;
-(void)handleViewWillDisappear;
-(void)handleViewWillAppear;
-(void)initNavigationBar;
-(void)onSaveEmoticon:(id)arg1;
-(void)addNvGestureRecognizer;
-(void)removeNvGestureRecognizer;
-(void)onSingleTapOnNavigationBar:(id)arg1;
-(void)adjustImageViewRect;
-(void)onOperate;
-(void)setM_singleTapOnNav:(id)arg1;
-(void)onSingleTapImageBrowseView;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)viewDidLoad;
-(void)setFullScreen:(BOOL)arg1;
-(void)exitFullScreen;
-(void)dealloc;
@end