/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:06 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <FriendAsistSessionExt.h>

@interface EnterLbsViewController : MMUIViewController <FriendAsistSessionExt> {
	UIButton* m_btnLbs; 
	MMSayHelloButton* m_btnSayHello; 
	UILabel* m_labNoHello; 
}
-(void)initView;
-(void)initData;
-(void)onFriendAssistUnreadCountChanged;
-(void)UpdateView;
-(void)OnOpenLbs;
-(void)OnOpenSayHello;
-(void)viewDidLoad;
-(void)dealloc;
@end