/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:20 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <FBRequestDelegate.h>

@interface Facebook : NSObject <FBRequestDelegate> {
	NSString* _accessToken; 
	NSDate* _expirationDate; 
	id<FBSessionDelegate> _sessionDelegate; 
	NSMutableSet* _requests; 
	FBDialog* _fbDialog; 
	NSString* _appId; 
	NSString* _urlSchemeSuffix; 
	NSArray* _permissions; 
	BOOL _isExtendingAccessToken; 
	NSDate* _lastAccessTokenUpdate; 
	NSString* _preventCSRF; 
}
@property (assign,nonatomic) NSString* preventCSRF; 				//@synthesize preventCSRF=_preventCSRF - In the implementation block
@property (nonatomic,copy) NSString* appId; 				//@synthesize appId=_appId - In the implementation block
@property (nonatomic,copy) NSString* urlSchemeSuffix; 				//@synthesize urlSchemeSuffix=_urlSchemeSuffix - In the implementation block
@property (nonatomic,retain) NSArray* permissions; 				//@synthesize permissions=_permissions - In the implementation block
@property (assign,nonatomic) id<FBSessionDelegate> sessionDelegate; 				//@synthesize sessionDelegate=_sessionDelegate - In the implementation block
@property (nonatomic,copy) NSDate* expirationDate; 				//@synthesize expirationDate=_expirationDate - In the implementation block
@property (nonatomic,copy) NSString* accessToken; 				//@synthesize accessToken=_accessToken - In the implementation block
-(void)dialog:(id)arg1 andParams:(id)arg2 andDelegate:(id)arg3;
-(id)requestWithGraphPath:(id)arg1 andParams:(id)arg2 andHttpMethod:(id)arg3 andDelegate:(id)arg4;
-(id)openUrl:(id)arg1 params:(id)arg2 httpMethod:(id)arg3 delegate:(id)arg4;
-(id)requestWithMethodName:(id)arg1 andParams:(id)arg2 andHttpMethod:(id)arg3 andDelegate:(id)arg4;
-(void)fbDialogLogin:(id)arg1 expirationDate:(id)arg2;
-(void)fbDialogNotLogin:(BOOL)arg1;
-(id)parseURLParams:(id)arg1;
-(void)extendAccessToken;
-(BOOL)shouldExtendAccessToken;
-(id)requestWithParams:(id)arg1 andDelegate:(id)arg2;
-(void)authorizeWithFBAppAuth:(BOOL)arg1 safariAuth:(BOOL)arg2;
-(id)getOwnBaseUrl;
-(void)invalidateSession;
-(void)extendAccessTokenIfNeeded;
-(BOOL)isSessionValid;
-(void)setUrlSchemeSuffix:(id)arg1;
-(void)setSessionDelegate:(id)arg1;
-(id)initWithAppId:(id)arg1 urlSchemeSuffix:(id)arg2 andDelegate:(id)arg3;
-(void)request:(id)arg1 didLoadRawResponse:(id)arg2;
-(void)request:(id)arg1 didLoad:(id)arg2;
-(void)request:(id)arg1 didReceiveResponse:(id)arg2;
-(void)requestLoading:(id)arg1;
-(void)setPreventCSRF:(id)arg1;
-(void)dialog:(id)arg1 andDelegate:(id)arg2;
-(id)requestWithGraphPath:(id)arg1 andParams:(id)arg2 andDelegate:(id)arg3;
-(id)requestWithGraphPath:(id)arg1 andDelegate:(id)arg2;
-(void)logout:(id)arg1;
-(BOOL)handleOpenURL:(id)arg1;
-(void)authorize:(id)arg1;
-(id)getCustomAppendQuery;
-(id)initWithAppId:(id)arg1 andDelegate:(id)arg2;
-(void)setPermissions:(id)arg1;
-(void)setExpirationDate:(id)arg1;
-(void)request:(id)arg1 didFailWithError:(id)arg2;
-(void)setAccessToken:(id)arg1;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
-(void)logout;
-(void)setAppId:(id)arg1;
-(void)dealloc;
-(id)description;
@end