/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:37 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IMMFacebookMgrExt.h>

@interface FacebookContactInfoAssist : CBaseContactInfoAssist <IMMFacebookMgrExt> {
	struct map<long unsigned int,long unsigned int,stdless<long unsigned int>,stdallocator<stdpair<const long unsigned int, long unsigned int> > > m_mapSectionIndexType; 
	struct stWeixinEntryRow* m_ShareInfo; 
}
-(void)initTableView;
-(void)onUnBindFacebookFinish:(unsigned long)arg1;
-(void)onBindFacebookFinish:(unsigned long)arg1;
-(void)showBindView;
-(void)initHeaderView;
-(void)updateInstallView;
-(id)initWithContact:(id)arg1 andVerify:(unsigned long)arg2 delegate:(id)arg3;
-(void)makeCell:(id)arg1 row:(unsigned)arg2 section:(unsigned long)arg3;
-(void)showShareView;
-(void)initFacebookContactData;
-(void)showFriendListView;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)dealloc;
-(void).cxx_destruct;
-(id).cxx_construct;
@end