/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:14 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FacebookInfo : PBGeneratedMessage {
	unsigned int hasUid:1; 
	unsigned int hasName:1; 
	unsigned int hasToken:1; 
	unsigned long long uid; 
	NSString* name; 
	NSString* token; 
}
@property (retain) NSString* token; 
@property (assign) BOOL hasToken; 
@property (retain) NSString* name; 
@property (assign) BOOL hasName; 
@property (assign) unsigned long long uid; 
@property (assign) BOOL hasUid; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasToken:(BOOL)arg1;
-(void)setHasName:(BOOL)arg1;
-(void)setHasUid:(BOOL)arg1;
-(id)SetToken:(id)arg1;
-(id)SetUid:(unsigned long long)arg1;
-(id)SetName:(id)arg1;
-(void)setUid:(unsigned long long)arg1;
-(id)init;
-(void)dealloc;
-(void)setName:(id)arg1;
-(void)setToken:(id)arg1;
@end