/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:20 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol FBRequestDelegate
@optional
-(void)request(id):arg1 didLoadRawResponse(id):arg2 ;
-(void)request(id):arg1 didLoad(id):arg2 ;
-(void)request(id):arg1 didFailWithError(id):arg2 ;
-(void)request(id):arg1 didReceiveResponse(id):arg2 ;
-(void)requestLoading(id):arg1 ;
@end
