/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:55 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBRequest : NSObject {
	id<FBRequestDelegate> _delegate; 
	NSString* _url; 
	NSString* _httpMethod; 
	NSMutableDictionary* _params; 
	NSURLConnection* _connection; 
	NSMutableData* _responseText; 
	unsigned _state; 
	NSError* _error; 
	BOOL _sessionDidExpire; 
}
@property (nonatomic,retain) NSError* error; 				//@synthesize error=_error - In the implementation block
@property (assign,nonatomic) BOOL sessionDidExpire; 				//@synthesize sessionDidExpire=_sessionDidExpire - In the implementation block
@property (assign,nonatomic) unsigned state; 				//@synthesize state=_state - In the implementation block
@property (nonatomic,retain) NSMutableData* responseText; 				//@synthesize responseText=_responseText - In the implementation block
@property (nonatomic,retain) NSURLConnection* connection; 				//@synthesize connection=_connection - In the implementation block
@property (nonatomic,retain) NSMutableDictionary* params; 				//@synthesize params=_params - In the implementation block
@property (nonatomic,copy) NSString* httpMethod; 				//@synthesize httpMethod=_httpMethod - In the implementation block
@property (nonatomic,copy) NSString* url; 				//@synthesize url=_url - In the implementation block
@property (assign,nonatomic) id<FBRequestDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
+(id)serializeURL:(id)arg1 params:(id)arg2;
+(id)getRequestWithParams:(id)arg1 httpMethod:(id)arg2 delegate:(id)arg3 requestURL:(id)arg4;
+(id)serializeURL:(id)arg1 params:(id)arg2 httpMethod:(id)arg3;
-(void)handleResponseData:(id)arg1;
-(id)generatePostBody;
-(id)parseJsonResponse:(id)arg1 error:(id*)arg2;
-(void)setSessionDidExpire:(BOOL)arg1;
-(id)formError:(int)arg1 userInfo:(id)arg2;
-(void)utfAppendBody:(id)arg1 data:(id)arg2;
-(void)setResponseText:(id)arg1;
-(void)setParams:(id)arg1;
-(id)connection:(id)arg1 willCacheResponse:(id)arg2;
-(void)setError:(id)arg1;
-(BOOL)loading;
-(void)setState:(unsigned)arg1;
-(void)setUrl:(id)arg1;
-(void)connection:(id)arg1 didFailWithError:(id)arg2;
-(void)connection:(id)arg1 didReceiveData:(id)arg2;
-(void)connectionDidFinishLoading:(id)arg1;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2;
-(void)setConnection:(id)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(void)failWithError:(id)arg1;
-(void)setHttpMethod:(id)arg1;
@end