/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:09 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FeatureLogInfo : NSObject {
	unsigned logid; 
	unsigned begin_time; 
	unsigned end_time; 
	unsigned log_count; 
	NSString* log_ext; 
}
@property (nonatomic,retain) NSString* log_ext; 
@property (assign,nonatomic) unsigned log_count; 
@property (assign,nonatomic) unsigned end_time; 
@property (assign,nonatomic) unsigned begin_time; 
@property (assign,nonatomic) unsigned logid; 
-(void)setLog_count:(unsigned long)arg1;
-(void)setBegin_time:(unsigned long)arg1;
-(void)setEnd_time:(unsigned long)arg1;
-(void)setLogid:(unsigned long)arg1;
-(void)setLog_ext:(id)arg1;
-(id)init;
-(void)dealloc;
@end