/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:05 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ForwardMessageToBrandLogicController : NSObject {
	id<ForwardMessageToBrandLogicControllerDelegate> m_delegate; 
}
@property (assign,nonatomic) id<ForwardMessageToBrandLogicControllerDelegate> m_delegate; 
-(void)setM_delegate:(id)arg1;
-(void)forwardMessage:(id)arg1 toContact:(id)arg2;
-(id)init;
-(void)dealloc;
@end