/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:06 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol FriendAsistSessionExt
@optional
-(void)onFriendAssistRelpyMsg(id):arg1 ;
-(void)onFriendAssistAddMsg(id):arg1 ;
-(void)onFriendAssistClearMsg(id):arg1 ;
-(void)onFriendAssistUnreadCountChanged;
@end
