/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:38:52 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface GetAppInfoResponse : PBGeneratedMessage {
	unsigned int hasBaseResponse:1; 
	unsigned int hasAppInfo:1; 
	BaseResponse* baseResponse; 
	OpenAppInfo* appInfo; 
}
@property (retain) OpenAppInfo* appInfo; 
@property (assign) BOOL hasAppInfo; 
@property (retain) BaseResponse* baseResponse; 
@property (assign) BOOL hasBaseResponse; 
+(id)parseFromData:(id)arg1;
-(void)setAppInfo:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasAppInfo:(BOOL)arg1;
-(id)SetAppInfo:(id)arg1;
-(void)setHasBaseResponse:(BOOL)arg1;
-(id)SetBaseResponse:(id)arg1;
-(void)setBaseResponse:(id)arg1;
-(id)init;
-(void)dealloc;
@end