/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:00 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface GetAppInfoRequest : PBGeneratedMessage {
	unsigned int hasAppId:1; 
	unsigned int hasBaseRequest:1; 
	unsigned int hasIconType:1; 
	NSString* appId; 
	BaseRequest* baseRequest; 
	unsigned iconType; 
}
@property (assign) unsigned iconType; 
@property (assign) BOOL hasIconType; 
@property (retain) NSString* appId; 
@property (assign) BOOL hasAppId; 
@property (retain) BaseRequest* baseRequest; 
@property (assign) BOOL hasBaseRequest; 
+(id)parseFromData:(id)arg1;
-(id)SetAppId:(id)arg1;
-(id)SetBaseRequest:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasIconType:(BOOL)arg1;
-(id)SetIconType:(unsigned)arg1;
-(void)setIconType:(unsigned)arg1;
-(void)setHasAppId:(BOOL)arg1;
-(void)setHasBaseRequest:(BOOL)arg1;
-(void)setBaseRequest:(id)arg1;
-(void)setAppId:(id)arg1;
-(id)init;
-(void)dealloc;
@end