/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:21 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface GetContactEventHandler : ProtobufEventHandler {
}
-(void)OnProtocolReturn:(id)arg1 shouldContinue:(_Bool*)arg2;
-(void)HandleMemContact:(id)arg1;
@end