/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:18 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface GetCDNDnsRequest : PBGeneratedMessage {
	unsigned int hasClientIp:1; 
	unsigned int hasBaseRequest:1; 
	NSString* clientIp; 
	BaseRequest* baseRequest; 
}
@property (retain) NSString* clientIp; 
@property (assign) BOOL hasClientIp; 
@property (retain) BaseRequest* baseRequest; 
@property (assign) BOOL hasBaseRequest; 
+(id)parseFromData:(id)arg1;
-(id)SetBaseRequest:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasClientIp:(BOOL)arg1;
-(id)SetClientIp:(id)arg1;
-(void)setClientIp:(id)arg1;
-(void)setHasBaseRequest:(BOOL)arg1;
-(void)setBaseRequest:(id)arg1;
-(id)init;
-(void)dealloc;
@end