/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:12 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface GetCertRequest : PBGeneratedMessage {
	unsigned int hasBaseRequest:1; 
	unsigned int hasRandomEncryKey:1; 
	unsigned int hasCurrentCertVersion:1; 
	BaseRequest* baseRequest; 
	SKBuiltinBuffer_t* randomEncryKey; 
	unsigned currentCertVersion; 
}
@property (assign) unsigned currentCertVersion; 
@property (assign) BOOL hasCurrentCertVersion; 
@property (retain) SKBuiltinBuffer_t* randomEncryKey; 
@property (assign) BOOL hasRandomEncryKey; 
@property (retain) BaseRequest* baseRequest; 
@property (assign) BOOL hasBaseRequest; 
+(id)parseFromData:(id)arg1;
-(id)SetRandomEncryKey:(id)arg1;
-(id)SetBaseRequest:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasCurrentCertVersion:(BOOL)arg1;
-(id)SetCurrentCertVersion:(unsigned)arg1;
-(void)setCurrentCertVersion:(unsigned)arg1;
-(void)setHasRandomEncryKey:(BOOL)arg1;
-(void)setRandomEncryKey:(id)arg1;
-(void)setHasBaseRequest:(BOOL)arg1;
-(void)setBaseRequest:(id)arg1;
-(id)init;
-(void)dealloc;
@end