/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:57 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface GetLocationResponse : PBGeneratedMessage {
	unsigned int hasLongitude:1; 
	unsigned int hasLatitude:1; 
	unsigned int hasBaseResponse:1; 
	int longitude; 
	int latitude; 
	BaseResponse* baseResponse; 
}
@property (assign) int latitude; 
@property (assign) BOOL hasLatitude; 
@property (assign) int longitude; 
@property (assign) BOOL hasLongitude; 
@property (retain) BaseResponse* baseResponse; 
@property (assign) BOOL hasBaseResponse; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasLatitude:(BOOL)arg1;
-(void)setHasLongitude:(BOOL)arg1;
-(id)SetLatitude:(int)arg1;
-(id)SetLongitude:(int)arg1;
-(void)setHasBaseResponse:(BOOL)arg1;
-(id)SetBaseResponse:(id)arg1;
-(void)setBaseResponse:(id)arg1;
-(void)setLatitude:(int)arg1;
-(void)setLongitude:(int)arg1;
-(id)init;
-(void)dealloc;
@end