/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:38 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface GetRecommendAppListResponse : PBGeneratedMessage {
	unsigned int hasBaseResponse:1; 
	unsigned int hasTotal:1; 
	unsigned int hasCount:1; 
	BaseResponse* baseResponse; 
	unsigned total; 
	unsigned count; 
	NSMutableArray* mutableAppListList; 
}
@property (retain) NSMutableArray* mutableAppListList; 
@property (assign) unsigned count; 
@property (assign) BOOL hasCount; 
@property (retain) BaseResponse* baseResponse; 
@property (assign) BOOL hasBaseResponse; 
@property (assign) unsigned total; 
@property (assign) BOOL hasTotal; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasTotal:(BOOL)arg1;
-(id)addAppList:(id)arg1;
-(id)SetTotal:(unsigned)arg1;
-(id)appListList;
-(void)setMutableAppListList:(id)arg1;
-(void)setHasBaseResponse:(BOOL)arg1;
-(id)SetBaseResponse:(id)arg1;
-(void)setBaseResponse:(id)arg1;
-(void)setHasCount:(BOOL)arg1;
-(id)SetCount:(unsigned)arg1;
-(id)addAppListFromArray:(id)arg1;
-(void)setCount:(unsigned)arg1;
-(void)setTotal:(unsigned)arg1;
-(id)init;
-(void)dealloc;
@end