/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:26 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface GetWeiBoURLReq : PBGeneratedMessage {
	unsigned int hasUserName:1; 
	unsigned int hasBlogUserName:1; 
	unsigned int hasBaseRequest:1; 
	unsigned int hasA2Key:1; 
	unsigned int hasScene:1; 
	NSString* userName; 
	NSString* blogUserName; 
	BaseRequest* baseRequest; 
	SKBuiltinBuffer_t* a2Key; 
	unsigned scene; 
}
@property (retain) NSString* blogUserName; 
@property (assign) BOOL hasBlogUserName; 
@property (assign) unsigned scene; 
@property (assign) BOOL hasScene; 
@property (retain) NSString* userName; 
@property (assign) BOOL hasUserName; 
@property (retain) SKBuiltinBuffer_t* a2Key; 
@property (assign) BOOL hasA2Key; 
@property (retain) BaseRequest* baseRequest; 
@property (assign) BOOL hasBaseRequest; 
+(id)parseFromData:(id)arg1;
-(id)SetScene:(unsigned)arg1;
-(id)SetUserName:(id)arg1;
-(id)SetA2Key:(id)arg1;
-(id)SetBaseRequest:(id)arg1;
-(int)serializedSize;
-(void)setHasUserName:(BOOL)arg1;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasBlogUserName:(BOOL)arg1;
-(void)setHasA2Key:(BOOL)arg1;
-(id)SetBlogUserName:(id)arg1;
-(void)setBlogUserName:(id)arg1;
-(void)setA2Key:(id)arg1;
-(void)setHasBaseRequest:(BOOL)arg1;
-(void)setBaseRequest:(id)arg1;
-(void)setHasScene:(BOOL)arg1;
-(void)setScene:(unsigned)arg1;
-(void)setUserName:(id)arg1;
-(id)init;
-(void)dealloc;
@end