/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:06 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface GmailInfo : PBGeneratedMessage {
	unsigned int hasGmailAcct:1; 
	unsigned int hasGmailSwitch:1; 
	unsigned int hasGmailErrCode:1; 
	NSString* gmailAcct; 
	unsigned gmailSwitch; 
	unsigned gmailErrCode; 
}
@property (assign) unsigned gmailErrCode; 
@property (assign) BOOL hasGmailErrCode; 
@property (assign) unsigned gmailSwitch; 
@property (assign) BOOL hasGmailSwitch; 
@property (retain) NSString* gmailAcct; 
@property (assign) BOOL hasGmailAcct; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasGmailErrCode:(BOOL)arg1;
-(void)setHasGmailSwitch:(BOOL)arg1;
-(void)setHasGmailAcct:(BOOL)arg1;
-(id)SetGmailErrCode:(unsigned)arg1;
-(id)SetGmailSwitch:(unsigned)arg1;
-(id)SetGmailAcct:(id)arg1;
-(void)setGmailErrCode:(unsigned)arg1;
-(void)setGmailSwitch:(unsigned)arg1;
-(void)setGmailAcct:(id)arg1;
-(id)init;
-(void)dealloc;
@end