/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:39 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface Host : PBGeneratedMessage {
	unsigned int hasOrigin:1; 
	unsigned int hasSubstitute:1; 
	NSString* origin; 
	NSString* substitute; 
}
@property (retain) NSString* substitute; 
@property (assign) BOOL hasSubstitute; 
@property (retain) NSString* origin; 
@property (assign) BOOL hasOrigin; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasSubstitute:(BOOL)arg1;
-(void)setHasOrigin:(BOOL)arg1;
-(id)SetSubstitute:(id)arg1;
-(id)SetOrigin:(id)arg1;
-(void)setSubstitute:(id)arg1;
-(void)setOrigin:(id)arg1;
-(id)init;
-(void)dealloc;
@end