/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:13 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol IContactMgrExt
@optional
-(void)OnChangeNotifyStatus(id):arg1 withStatus(BOOL):arg2 ;
-(void)onContactListUpdate(unsigned long):arg1 ;
-(void)onSyncSXContactEnd;
-(void)onDeleteContact(id):arg1 ;
-(void)onModifyContact(id):arg1 ;
-(void)onModifyContactHeadImage(id):arg1 ;
@end
