/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:45 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol MMService
@optional
-(void)onServiceClearData;
-(BOOL)onServiceMemoryWarning;
-(void)onServiceTerminate;
-(void)onServiceEnterBackground;
-(void)onServiceReloadData;
-(void)onServiceInit;
@end

@protocol MessageObserverDelegate
@required
-(void)MessageReturn(unsigned long):arg1 MessageInfo(id):arg2 Event(unsigned long):arg3 ;
-(void)MessageReturn(unsigned long):arg1 MessageInfo(id):arg2 Event(unsigned long):arg3 ;
@end

@protocol IAudioToMessageExt
@optional
-(void)OnErrorByReceiver(id):arg1 ErrNo(int):arg2 ;
-(void)OnErrorBySender(id):arg1 ErrNo(int):arg2 ;
-(void)OnMessageSentBySender(id):arg1 ;
-(void)OnAddMessageByReceiver(id):arg1 ;
-(void)OnAddMessageBySender(id):arg1 ;
@end

@protocol CNetworkStatusExt
@required
-(void)ReachabilityChange(unsigned long):arg1 ;
-(void)ReachabilityChange(unsigned long):arg1 ;
@end

@protocol IEmoticonDownloadExt
@required
-(void)OnEmoticonDownload(unsigned long):arg1 ;
-(void)OnEmoticonDownload(unsigned long):arg1 ;
@end
