/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:13 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol ILinkEventExt
@optional
-(void)onTextLongPressed(id):arg1 withRect({):arg2 withView(unsigned char):arg3 ;
-(void)onPhoneLongPressed(id):arg1 withRect({):arg2 withView(unsigned char):arg3 ;
-(void)onLinkLongPressed(id):arg1 withRect({):arg2 withView(unsigned char):arg3 ;
-(void)onTextLongPressed(id):arg1 withRect({):arg2 ;
-(void)onPhoneLongPressed(id):arg1 withRect({):arg2 ;
-(void)onPhoneClicked(id):arg1 withRect({):arg2 ;
-(void)onLinkLongPressed(id):arg1 withRect({):arg2 ;
-(void)onLinkClicked(id):arg1 backupUrl(id):arg2 withRect({):arg3 ;
-(void)onLinkClicked(id):arg1 withRect({):arg2 ;
@end
