/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:46 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol IMMFacebookMgrExt
@optional
-(void)onFBCheckPasswordFailed;
-(void)onFBCheckPasswordFinished(BOOL):arg1 ;
-(void)onGetPhotoByIDFailed(id):arg1 error(id):arg2 ;
-(void)facebookCheckAccessTokenValidFinished(BOOL):arg1 ;
-(void)onGetPhotoByIDFinish(id):arg1 ;
-(void)onGetPhotosFinish(id):arg1 ;
-(void)onGetMyAlbumsFinish(id):arg1 ;
-(void)onFBAccountNotMatch(unsigned long):arg1 ;
-(void)onExtendTokenFinish(BOOL):arg1 ;
-(void)onDownloadFacebookFriendFinish(unsigned long):arg1 Message(id):arg2 ;
-(void)onUnBindFacebookFinish(unsigned long):arg1 ;
-(void)onBindFacebookFinish(unsigned long):arg1 ;
-(void)onLoginFacebookFinished(unsigned long):arg1 isAutoReg(BOOL):arg2 Title(id):arg3 Message(id):arg4 ;
-(void)onLoginFacebookBegan;
@end
