/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:20 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ImportFriendsResponse : PBGeneratedMessage {
	unsigned int hasBaseResponse:1; 
	unsigned int hasImportedCount:1; 
	BaseResponse* baseResponse; 
	unsigned importedCount; 
}
@property (assign) unsigned importedCount; 
@property (assign) BOOL hasImportedCount; 
@property (retain) BaseResponse* baseResponse; 
@property (assign) BOOL hasBaseResponse; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasImportedCount:(BOOL)arg1;
-(id)SetImportedCount:(unsigned)arg1;
-(void)setImportedCount:(unsigned)arg1;
-(void)setHasBaseResponse:(BOOL)arg1;
-(id)SetBaseResponse:(id)arg1;
-(void)setBaseResponse:(id)arg1;
-(id)init;
-(void)dealloc;
@end