/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:39 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol IEmoticonMgrExt
@optional
-(void)OnUpdateEmojiCatalog;
-(void)OnUpdateEmoticonList;
@end

@protocol EmojiArtPreviewControllerDelegate
@optional
-(void)didSelectEmojiArt(id):arg1 ;
@end

@protocol IMsgExt
@optional
-(void)OnMsgNotAddDBSession(id):arg1 MsgList(id):arg2 ;
-(void)OnShowPush(id):arg1 ;
-(void)OnAddMsgForSpecialSession(id):arg1 MsgList(id):arg2 ;
-(void)OnMsgNotAddDBNotify(id):arg1 MsgWrap(id):arg2 ;
-(void)OnAddMsgListForSession(id):arg1 NotifyUsrName(id):arg2 ;
-(void)OnUnReadCountChange(id):arg1 ;
-(void)OnDelMsg(id):arg1 MsgWrap(id):arg2 ;
-(void)OnDelMsg(id):arg1 ;
-(void)OnModMsg(id):arg1 MsgWrap(id):arg2 ;
-(void)OnAddMsg(id):arg1 MsgWrap(id):arg2 ;
-(void)OnPreAddMsg(id):arg1 MsgWrap(id):arg2 ;
-(void)OnChangeMsg(id):arg1 OpCode(unsigned long):arg2 ;
@end
