/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:41 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol IVOIPModeSwitchExt
@optional
-(void)OnBothEarMode;
-(void)OnRemoteVideoMode;
-(void)OnRemoteEarMode;
-(void)OnLocalVideoMode;
-(void)OnLocalEarMode;
-(void)OnBothVideoMode;
-(void)OnRemoteEarModeFor2G;
-(void)OnLocalEarModeFor2G;
@end
