/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:06 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol IWXTalkExt
@optional
-(void)onRemoteControlCheckShouldStop;
-(void)onRemoteControlCheckShouldPlay;
-(void)OnSomeOneCloseMode(id):arg1 ;
-(void)OnSomeOneOpenMode(id):arg1 ;
-(void)OnRestart;
-(void)OnPause;
-(void)OnReConnecting;
-(void)OnForceStopWXTalk;
-(void)onKickOutFromWXTalkRoom(id):arg1 ;
-(void)OnMyselfCloseMode(id):arg1 ;
-(void)OnNobodyTalking;
-(void)OnForceStopRecord;
-(void)OnError(id):arg1 ErrNo(int):arg2 ;
-(void)OnRoomMemberChange(id):arg1 ;
-(void)OnSomeoneTalking(id):arg1 ;
-(void)OnGetMicrophoneResult(int):arg1 ;
-(void)OnOpenWXTalkModeOK(id):arg1 ;
@end
