/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:38:52 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MMService.h>

@interface LazyExtensionAgent : MMService <MMService> {
	NSMutableDictionary* m_dicExtensions; 
}
-(void)onServiceInit;
-(void)ensureLazyListenerInitedForExtension:(id)arg1 withSelector:(SEL)arg2;
-(void)registerLazyListener:(Class)arg1 onExtension:(id)arg2;
-(void)addListener:(Class)arg1 toDic:(id)arg2 forMethods:(struct objc_method_description*)arg3 methodCount:(unsigned)arg4;
-(void)dealloc;
@end