/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:27 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LBSClaimerViewController : UIViewController {
	UIButton* m_agreedButton; 
	UILabel* m_claimerTextLabel; 
	UIImageView* m_claimerImage; 
	id<LBSClaimerViewControllerDelegate> m_delegate; 
}
@property (assign,nonatomic) id<LBSClaimerViewControllerDelegate> delegate; 
-(void)onClickAgree:(id)arg1;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
@end