/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:23 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LBSErrorViewController : UIViewController {
	UILabel* errorMessageLabel; 
	UIImageView* m_errorImage; 
}
@property (nonatomic,retain) UILabel* errorMessageLabel; 
-(void)setErrorMessageLabel:(id)arg1;
-(void)setErrorMessage:(id)arg1;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)dealloc;
@end