/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:27 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol PBMessageObserverDelegate
@required
-(void)MessageReturn(id):arg1 Event(unsigned long):arg2 ;
-(void)MessageReturn(id):arg1 Event(unsigned long):arg2 ;
@end

@protocol LocationRetrieveDelegate
@required
-(void)onRetrieveLocationError(int):arg1 ;
-(void)onRetrieveLocationTimeOut(id):arg1 ;
-(void)onRetrieveLocationOK(id):arg1 ;
-(void)onRetrieveLocationError(int):arg1 ;
-(void)onRetrieveLocationTimeOut(id):arg1 ;
-(void)onRetrieveLocationOK(id):arg1 ;
@end
