/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:59 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PBMessageObserverDelegate.h>
#import <MMService.h>
#import <MMKernelExt.h>

@interface LogReportMgr : MMService <PBMessageObserverDelegate, MMService, MMKernelExt> {
	BOOL mIsStart; 
	NSMutableDictionary* mFeatureLogInfos; 
	NSTimer* mFeatureReportCheckTimer; 
	unsigned mFeatureReportIntervalTime; 
	unsigned mFeatureReportFlag; 
	NSMutableDictionary* mActionLogInfos; 
	NSMutableArray* mActionPathPoints; 
	NSTimer* mActionReportCheckTimer; 
	unsigned mActionReportIntervalTime; 
	unsigned mActionReportFlag; 
	NSMutableDictionary* mPerformLogInfos; 
	NSTimer* mPerformReportCheckTimer; 
	unsigned mPerformReportIntervalTime; 
	unsigned mPerformReportFlag; 
}
@property (assign,nonatomic) unsigned mPerformReportFlag; 
@property (assign,nonatomic) unsigned mPerformReportIntervalTime; 
@property (nonatomic,retain) NSTimer* mPerformReportCheckTimer; 
@property (nonatomic,retain) NSMutableDictionary* mPerformLogInfos; 
@property (assign,nonatomic) unsigned mActionReportFlag; 
@property (assign,nonatomic) unsigned mActionReportIntervalTime; 
@property (nonatomic,retain) NSTimer* mActionReportCheckTimer; 
@property (nonatomic,retain) NSMutableArray* mActionPathPoints; 
@property (nonatomic,retain) NSMutableDictionary* mActionLogInfos; 
@property (assign,nonatomic) unsigned mFeatureReportFlag; 
@property (assign,nonatomic) unsigned mFeatureReportIntervalTime; 
@property (nonatomic,retain) NSTimer* mFeatureReportCheckTimer; 
@property (nonatomic,retain) NSMutableDictionary* mFeatureLogInfos; 
-(void)onServiceClearData;
-(void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
-(void)onAuthOK;
-(void)HandleReportClientPerfResp:(id)arg1 Event:(unsigned long)arg2;
-(void)HandleReportActionResp:(id)arg1 Event:(unsigned long)arg2;
-(void)HandleReportKVResp:(id)arg1 Event:(unsigned long)arg2;
-(void)HandleReportStrategyResp:(id)arg1 Event:(unsigned long)arg2;
-(void)StartReport;
-(void)MainThreadAddPerformLog:(id)arg1;
-(void)MainThreadAddActionLog:(id)arg1;
-(void)MainThreadAddFeatureLog:(id)arg1;
-(void)PerformReportTimerCheck;
-(void)setMPerformReportCheckTimer:(id)arg1;
-(void)SendReportRequestWithPerformLogInfo:(id)arg1;
-(void)ActionReportTimerCheck;
-(void)setMActionReportCheckTimer:(id)arg1;
-(void)SendReportRequestWithActionLogInfo:(id)arg1;
-(void)FeatureReportTimerCheck;
-(void)setMFeatureReportCheckTimer:(id)arg1;
-(void)SendReportRequestWithFeatureLogInfo:(id)arg1;
-(void)StopReport;
-(void)setMPerformLogInfos:(id)arg1;
-(void)setMActionPathPoints:(id)arg1;
-(void)setMActionLogInfos:(id)arg1;
-(void)setMFeatureLogInfos:(id)arg1;
-(void)SendReportStrategyRequest;
-(void)setMFeatureReportIntervalTime:(unsigned long)arg1;
-(void)setMFeatureReportFlag:(unsigned long)arg1;
-(void)setMActionReportIntervalTime:(unsigned long)arg1;
-(void)setMActionReportFlag:(unsigned long)arg1;
-(void)setMPerformReportIntervalTime:(unsigned long)arg1;
-(void)setMPerformReportFlag:(unsigned long)arg1;
-(void)AddPerformLogWithEventId:(unsigned long)arg1 Duration:(unsigned long)arg2;
-(void)AddActionLogWithEventId:(unsigned long)arg1 ActionLogType:(unsigned long)arg2;
-(unsigned long)GetFeatureCount;
-(void)AddFeatureLogWithLogId:(unsigned long)arg1 ExtLog:(id)arg2;
-(void)AddFeatureLogWithLogId:(unsigned long)arg1;
-(id)init;
-(void)dealloc;
@end