/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:03 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MainWindow : UIWindow {
	float windowOffset; 
	CGRect mainWindowFrame; 
	float mainWindowX; 
	float mainWindowY; 
	float mainWindowWidth; 
	float mainWindowHeight; 
}
@property (assign,nonatomic) float mainWindowHeight; 
@property (assign,nonatomic) float mainWindowWidth; 
@property (assign,nonatomic) float mainWindowY; 
@property (assign,nonatomic) float mainWindowX; 
@property (assign,nonatomic) CGRect mainWindowFrame; 
@property (assign,nonatomic) float windowOffset; 
-(void)setWindowOffset:(float)arg1;
-(void)setMainWindowHeight:(float)arg1;
-(void)setMainWindowY:(float)arg1;
-(void)setMainWindowFrame:(CGRect)arg1;
-(void)setMainWindowX:(float)arg1;
-(void)setMainWindowWidth:(float)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)setFrame:(CGRect)arg1;
-(void)setX:(float)arg1;
@end