/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:08 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MFSetWechatIDBtn : UIButton {
}
-(void)ButtonTouchUpOutside:(id)arg1;
-(void)ButtonTouchDown:(id)arg1;
-(void)setLabelHighlighted:(BOOL)arg1;
-(id)initWithFrame:(CGRect)arg1;
@end