/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:38 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IWXTalkExt.h>

@interface MFWXTalkStatusBar : UIWindow <IWXTalkExt> {
	UIImageView* _maskView; 
	UIImageView* _iconView; 
	UILabel* _memCountLabel; 
	UIImageView* _backgroundView; 
	UIView* _newView; 
	UIView* _oldView; 
	UILabel* _newLabel; 
	UILabel* _oldLabel; 
	id<mfWXTalkStatusBarDelegate> _myDelegate; 
	int _nowInterfaceOrientation; 
	BOOL _isForceHidden; 
	BOOL _isPrepared; 
	BOOL _isShow; 
	int _forceHiddenRetainCount; 
	BOOL _lastHiddenStatus; 
}
@property (assign,nonatomic) id<mfWXTalkStatusBarDelegate> myDelegate; 				//@synthesize myDelegate=_myDelegate - In the implementation block
@property (assign,nonatomic) BOOL isForceHidden; 				//@synthesize isForceHidden=_isForceHidden - In the implementation block
@property (assign,nonatomic) int nowInterfaceOrientation; 				//@synthesize nowInterfaceOrientation=_nowInterfaceOrientation - In the implementation block
-(void)OnMyselfCloseMode:(id)arg1;
-(void)OnNobodyTalking;
-(void)OnRoomMemberChange:(id)arg1;
-(void)OnSomeoneTalking:(id)arg1;
-(void)OnOpenWXTalkModeOK:(id)arg1;
-(void)setAndTransformInterfaceOritation:(int)arg1;
-(void)forceSetWXTalkStatusBarIsHidden:(BOOL)arg1;
-(CGRect)getOldViewFrame;
-(void)resetStatusBar;
-(CGRect)getNewViewPreFrame;
-(CGRect)getOldViewPreFrame;
-(void)formatLabel:(id)arg1;
-(void)formatImgView:(id)arg1;
-(CGRect)getNewViewFrame;
-(void)updateStatusBar:(id)arg1;
-(void)receivedWillRotateNotification:(id)arg1;
-(void)hideMemberCount;
-(void)showMemberCount;
-(void)forceResetStatusBar;
-(void)setNowInterfaceOrientation:(int)arg1;
-(void)setIsForceHidden:(BOOL)arg1;
-(void)setMyDelegate:(id)arg1;
-(void)showButton:(BOOL)arg1;
-(void)showWithAnimation;
-(void)setHidden:(BOOL)arg1;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2;
-(id)init;
-(void)dealloc;
@end