/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:38:58 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol MMActionSheetDelegate
@optional
-(void)actionSheet(id):arg1 didDismissWithItem(id):arg2 ;
-(void)actionSheet(id):arg1 willDismissWithItem(id):arg2 ;
-(void)didPresentActionSheet(id):arg1 ;
-(void)willPresentActionSheet(id):arg1 ;
-(void)actionSheetCancel(id):arg1 ;
-(void)actionSheet(id):arg1 didSelectWithItem(id):arg2 ;
@end
