/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:19 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIScrollViewDelegate.h>
#import <UIActionSheetDelegate.h>
#import <MMGridViewDataSource.h>
#import <MMGridViewActionDelegate.h>

@interface MMActionSheet : UIActionSheet <UIScrollViewDelegate, UIActionSheetDelegate, MMGridViewDataSource, MMGridViewActionDelegate> {
	id<MMActionSheetDelegate> delegateEx; 
	UIPageControl* pageControl; 
	NSString* cancelButtonTitle; 
	MMGridView* gridView; 
	NSArray* items; 
	MMGridViewLayoutHorizontalPagedLTRStrategy* layoutStrategy; 
}
@property (nonatomic,retain) MMGridViewLayoutHorizontalPagedLTRStrategy* layoutStrategy; 
@property (nonatomic,retain) NSArray* items; 
@property (nonatomic,retain) MMGridView* gridView; 
@property (nonatomic,retain) NSString* cancelButtonTitle; 
@property (nonatomic,retain) UIPageControl* pageControl; 
@property (assign,nonatomic) id<MMActionSheetDelegate> delegateEx; 
+(id)generateTitle:(float)arg1;
-(id)initWithItems:(id)arg1 cancelButtonTitle:(id)arg2 delegate:(id)arg3 landscape:(BOOL)arg4;
-(void)OnCancel:(id)arg1;
-(int)numberOfItemsInMMGridView:(id)arg1;
-(id)MMGridView:(id)arg1 cellForItemAtIndex:(int)arg2;
-(void)MMGridView:(id)arg1 didTapOnItemAtIndex:(int)arg2;
-(CGSize)MMGridView:(id)arg1 sizeForItemsInInterfaceOrientation:(int)arg2;
-(void)setLayoutStrategy:(id)arg1;
-(void)OnPageChanged:(id)arg1;
-(void)setDelegateEx:(id)arg1;
-(void)reloadData;
-(void)scrollViewDidScroll:(id)arg1;
-(void)dismissWithClickedButtonIndex:(int)arg1 animated:(BOOL)arg2;
-(void)willPresentActionSheet:(id)arg1;
-(void)didPresentActionSheet:(id)arg1;
-(void)setItems:(id)arg1;
-(void)showInView:(id)arg1;
-(void)setPageControl:(id)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(void)setGridView:(id)arg1;
-(void)setCancelButtonTitle:(id)arg1;
@end