/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:42 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMActionSheetCell : UIView {
	UILabel* titleLabel; 
	MMActionSheetContentView* contentView; 
	UIImageView* imageView; 
	int index; 
	NSObject* userInfo; 
}
@property (nonatomic,retain) NSObject* userInfo; 
@property (assign,nonatomic) int index; 
@property (nonatomic,retain) UIImageView* imageView; 
@property (nonatomic,retain) MMActionSheetContentView* contentView; 
@property (nonatomic,retain) UILabel* titleLabel; 
-(id)initWithIndex:(int)arg1;
-(void)setTitleLabel:(id)arg1;
-(void)setContentView:(id)arg1;
-(void)setImageView:(id)arg1;
-(void)setUserInfo:(id)arg1;
-(void)setIndex:(int)arg1;
-(id)init;
-(void)dealloc;
@end