/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:59 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol MMImgageBrowseViewDelegate
@optional
-(void)onDoubleTapImageBrowseView;
-(void)onSingleTapImageBrowseView;
@end

@protocol UIActionSheetDelegate
@optional
-(void)actionSheet(id):arg1 clickedButtonAtIndex(int):arg2 ;
-(void)actionSheetCancel(id):arg1 ;
-(void)willPresentActionSheet(id):arg1 ;
-(void)didPresentActionSheet(id):arg1 ;
-(void)actionSheet(id):arg1 willDismissWithButtonIndex(int):arg2 ;
-(void)actionSheet(id):arg1 didDismissWithButtonIndex(int):arg2 ;
@end

@protocol UIAlertViewDelegate
@optional
-(void)alertView(id):arg1 clickedButtonAtIndex(int):arg2 ;
-(void)alertViewCancel(id):arg1 ;
-(void)willPresentAlertView(id):arg1 ;
-(void)didPresentAlertView(id):arg1 ;
-(void)alertView(id):arg1 willDismissWithButtonIndex(int):arg2 ;
-(void)alertView(id):arg1 didDismissWithButtonIndex(int):arg2 ;
-(BOOL)alertViewShouldEnableFirstOtherButton(id):arg1 ;
@end

@protocol MMCameraDelegate
@optional
-(void)mmCameraDidCancel;
-(void)mmCameraDidTakeVideo(id):arg1 ;
-(void)mmCameraDidTakePicture(id):arg1 ;
-(void)mmCameraDidNextStep(id):arg1 withPicture(id):arg2 andMatteOrder(int):arg3 choosed(BOOL):arg4 ;
-(void)mmCameraDidNextStepAlbum(id):arg1 withPictures(id):arg2 andMatteOrder(int):arg3 choosed(BOOL):arg4 isCameraFront(BOOL):arg5 ;
-(id)getNavigationController;
-(id)getViewController;
@end
