/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:38 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMCrashReportWrap : NSObject {
	NSString* m_nsCrashUsrName; 
	unsigned m_uiCrashVersion; 
	NSData* m_dtCrashData; 
}
@property (nonatomic,retain) NSData* m_dtCrashData; 
@property (assign,nonatomic) unsigned m_uiCrashVersion; 
@property (nonatomic,retain) NSString* m_nsCrashUsrName; 
-(void)setM_dtCrashData:(id)arg1;
-(void)setM_nsCrashUsrName:(id)arg1;
-(void)setM_uiCrashVersion:(unsigned long)arg1;
-(id)init;
-(void)dealloc;
@end