/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:46 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMCrashReportConnection : NSObject {
	id<crashReportConnectionDelegate> m_delegate; 
	NSURLConnection* m_ucReport; 
	MMCrashReportWrap* m_wrapCrash; 
	unsigned m_uiRetStatusCode; 
	NSTimer* m_tmCheckTimeOut; 
	int m_eReportType; 
	BOOL m_bTimeOut; 
}
@property (assign,nonatomic) BOOL m_bTimeOut; 
@property (nonatomic,retain) NSTimer* m_tmCheckTimeOut; 
@property (nonatomic,retain) MMCrashReportWrap* m_wrapCrash; 
@property (nonatomic,retain) NSURLConnection* m_ucReport; 
@property (assign,nonatomic) id<crashReportConnectionDelegate> m_delegate; 
-(void)setM_delegate:(id)arg1;
-(BOOL)uploadCrash:(id)arg1 reportType:(int)arg2;
-(void)setM_bTimeOut:(BOOL)arg1;
-(void)ReportTimeOut;
-(id)EncodePack:(id)arg1 Key:(struct basic_string<char,stdchar_traits<char>,stdallocator<char> >*)arg2;
-(void)setM_tmCheckTimeOut:(id)arg1;
-(void)setM_wrapCrash:(id)arg1;
-(void)setM_ucReport:(id)arg1;
-(void)CancelUrlConnection;
-(void)connection:(id)arg1 didSendBodyData:(int)arg2 totalBytesWritten:(int)arg3 totalBytesExpectedToWrite:(int)arg4;
-(void)connection:(id)arg1 didFailWithError:(id)arg2;
-(void)connection:(id)arg1 didReceiveData:(id)arg2;
-(void)connectionDidFinishLoading:(id)arg1;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2;
-(id)init;
-(void)dealloc;
-(BOOL)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2;
-(void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
@end