/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:42 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <crashReportConnectionDelegate.h>

@interface MMCrashReportHandler : NSObject <crashReportConnectionDelegate> {
	MMCrashReportViewController* m_viewController; 
	MMCrashReportConnection* m_crashReportConnection; 
	CrashReportInfo* m_oCrashReportInfo; 
}
@property (nonatomic,retain) CrashReportInfo* m_oCrashReportInfo; 
+(id)shareCrashReportHandler;
+(void)initialize;
-(BOOL)isReachable;
-(void)onUploadCrashCompleted:(BOOL)arg1 CrashWrap:(id)arg2;
-(id)getCrashReportData;
-(void)initCrashView;
-(void)removeCrashView;
-(BOOL)doCrashReport:(int)arg1;
-(void)prepareCrashReportOnRun;
-(BOOL)isNeedCrashReport;
-(void)enableCrashReportHandler;
-(id)GetCrashReportInfoPath;
-(void)setM_oCrashReportInfo:(id)arg1;
-(void)ClearCrashData;
-(void)SaveCrashReportInfo;
-(void)LoadCrashReportInfo;
-(void)disableExceptionHandle;
-(BOOL)tryCrashReportAfterRun;
-(void)cancelReportCrashReportOnRun;
-(void)reportCrashReportOnRun;
-(BOOL)tryCrashReportOnRun;
-(id)init;
-(void)dealloc;
@end