/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:21 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMExtensionObject : NSObject {
	id m_Obj; 
	BOOL m_deleteMark; 
}
@property (assign,nonatomic) BOOL m_deleteMark; 
-(id)getObject;
-(void)setM_deleteMark:(BOOL)arg1;
-(BOOL)isObjectEqual:(id)arg1;
-(void)setObject:(id)arg1;
-(id)initWithObject:(id)arg1;
-(id)description;
@end