/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:38:58 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMExtension : NSObject {
	Protocol* m_extKey; 
	unsigned m_methodCount; 
	struct objc_method_description* m_methods; 
	MMExtensionDictionary* m_dicObserver; 
	MMExtensionDictionary* m_dicKeyObserver; 
}
-(void)unregisterExtension:(id)arg1;
-(BOOL)registerExtension:(id)arg1;
-(BOOL)registerExtension:(id)arg1 forKey:(id)arg2;
-(void)unregisterExtension:(id)arg1 forKey:(id)arg2;
-(void)unregisterKeyExtension:(id)arg1;
-(id)getExtensionListForSelector:(SEL)arg1;
-(id)getKeyExtensionList:(id)arg1;
-(void)cleanUp;
-(void)dealloc;
-(id)description;
-(id)initWithKey:(id)arg1;
@end