/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:35 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMExtensionDictionary : NSObject {
	NSMutableDictionary* m_dic; 
	BOOL m_needCleanUp; 
}
-(BOOL)registerExtension:(id)arg1 forKey:(id)arg2;
-(BOOL)unregisterExtension:(id)arg1 forKey:(id)arg2;
-(BOOL)unregisterKeyExtension:(id)arg1;
-(id)getKeyExtensionList:(id)arg1;
-(void)cleanUp;
-(id)init;
-(void)dealloc;
@end