/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:56 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMGlobalLogTime : NSObject {
	NSMutableDictionary* m_dic; 
	NSMutableDictionary* m_dicProc; 
}
+(id)sharedMMGlobalLogTime;
-(void)needreport:(id)arg1 withEventId:(unsigned long)arg2;
-(void)start:(id)arg1 withStep:(r*)arg2;
-(void)end:(id)arg1;
-(id)init;
-(void)dealloc;
@end