/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:42 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol MMGridViewLayoutStrategy
@required
+(BOOL)requiresEnablingPaging;
-({)rangeOfPositionsInBoundsFromOffset(_):arg1 ;
-(int)itemPositionFromLocation({):arg1 ;
-({)originForItemAtPosition(unsigned char):arg1 ;
-({);
-(void)rebaseWithItemCount(int):arg1 insideOfBounds({):arg2 ;
-(void)setupItemSize({):arg1 andItemSpacingH(unsigned char):arg2 andItemSpacingV(G):arg3 withMinEdgeInsets(unsigned short):arg4 andCenteredGrid(int):arg5 ;
-(int)type;
-({)rangeOfPositionsInBoundsFromOffset(_):arg1 ;
-(int)itemPositionFromLocation({):arg1 ;
-({)originForItemAtPosition(unsigned char):arg1 ;
-({);
-(void)rebaseWithItemCount(int):arg1 insideOfBounds({):arg2 ;
-(void)setupItemSize({):arg1 andItemSpacingH(unsigned char):arg2 andItemSpacingV(G):arg3 withMinEdgeInsets(unsigned short):arg4 andCenteredGrid(int):arg5 ;
-(int)type;
@end
