/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:53 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMGridViewLayoutStrategyBase : NSObject {
	int _type; 
	CGSize _itemSize; 
	int _itemSpacingH; 
	int _itemSpacingV; 
	struct UIEdgeInsets _minEdgeInsets; 
	BOOL _centeredGridH; 
	int _itemCount; 
	struct UIEdgeInsets _edgeInsets; 
	CGRect _gridBounds; 
	CGSize _contentSize; 
}
@property (nonatomic,copy) int itemSpacingV; 				//@synthesize itemSpacingV=_itemSpacingV - In the implementation block
@property (nonatomic,copy) CGSize contentSize; 				//@synthesize contentSize=_contentSize - In the implementation block
@property (nonatomic,copy) CGRect gridBounds; 				//@synthesize gridBounds=_gridBounds - In the implementation block
@property (nonatomic,copy) struct UIEdgeInsets edgeInsets; 				//@synthesize edgeInsets=_edgeInsets - In the implementation block
@property (nonatomic,copy) int itemCount; 				//@synthesize itemCount=_itemCount - In the implementation block
@property (nonatomic,copy) BOOL centeredGridH; 				//@synthesize centeredGridH=_centeredGridH - In the implementation block
@property (nonatomic,copy) struct UIEdgeInsets minEdgeInsets; 				//@synthesize minEdgeInsets=_minEdgeInsets - In the implementation block
@property (nonatomic,copy) int itemSpacingH; 				//@synthesize itemSpacingH=_itemSpacingH - In the implementation block
@property (nonatomic,copy) CGSize itemSize; 				//@synthesize itemSize=_itemSize - In the implementation block
@property (nonatomic,copy) int type; 				//@synthesize type=_type - In the implementation block
-(void)setupItemSize:(CGSize)arg1 andItemSpacingH:(int)arg2 andItemSpacingV:(int)arg3 withMinEdgeInsets:(struct UIEdgeInsets)arg4 andCenteredGrid:(BOOL)arg5;
-(void)setEdgeAndContentSizeFromAbsoluteContentSize:(CGSize)arg1;
@end