/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:31 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIGestureRecognizerDelegate.h>
#import <UIScrollViewDelegate.h>

@interface MMGridView : UIScrollView <UIGestureRecognizerDelegate, UIScrollViewDelegate> {
	UIPanGestureRecognizer* _sortingPanGesture; 
	UILongPressGestureRecognizer* _longPressGesture; 
	UIPinchGestureRecognizer* _pinchGesture; 
	UITapGestureRecognizer* _tapGesture; 
	UIRotationGestureRecognizer* _rotationGesture; 
	UIPanGestureRecognizer* _panGesture; 
	int _numberTotalItems; 
	CGSize _itemSize; 
	NSMutableSet* _reusableCells; 
	MMGridViewCell* _sortMovingItem; 
	int _sortFuturePosition; 
	BOOL _autoScrollActive; 
	CGPoint _minPossibleContentOffset; 
	CGPoint _maxPossibleContentOffset; 
	MMGridViewCell* _transformingItem; 
	float _lastRotation; 
	float _lastScale; 
	BOOL _inFullSizeMode; 
	BOOL _inTransformingState; 
	BOOL _rotationActive; 
	id<MMGridViewSortingDelegate> _sortingDelegate; 
	id<MMGridViewDataSource> _dataSource; 
	id<MMGridViewTransformationDelegate> _transformDelegate; 
	id<MMGridViewActionDelegate> _actionDelegate; 
	UIView* _mainSuperView; 
	id<MMGridViewLayoutStrategy> _layoutStrategy; 
	int _itemSpacingH; 
	int _itemSpacingV; 
	int _style; 
	double minimumPressDuration; 
	BOOL _centerGridH; 
	struct UIEdgeInsets _minEdgeInsets; 
	BOOL showFullSizeViewWithAlphaWhenTransforming; 
	BOOL _editing; 
	BOOL enableEditOnLongPress; 
	BOOL disableEditOnEmptySpaceTap; 
	BOOL _itemsSubviewsCacheIsValid; 
	NSArray* itemSubviewsCache; 
	int _firstPositionLoaded; 
	int _lastPositionLoaded; 
}
@property (nonatomic,copy) UIScrollView* scrollView; 
@property (assign,nonatomic) int lastPositionLoaded; 				//@synthesize lastPositionLoaded=_lastPositionLoaded - In the implementation block
@property (assign,nonatomic) int firstPositionLoaded; 				//@synthesize firstPositionLoaded=_firstPositionLoaded - In the implementation block
@property (nonatomic,retain) NSArray* itemSubviewsCache; 
@property (nonatomic,copy) BOOL itemsSubviewsCacheIsValid; 				//@synthesize itemsSubviewsCacheIsValid=_itemsSubviewsCacheIsValid - In the implementation block
@property (assign,nonatomic) BOOL disableEditOnEmptySpaceTap; 
@property (assign,nonatomic) BOOL enableEditOnLongPress; 
@property (assign,getter=isEditing,nonatomic) BOOL editing; 				//@synthesize editing=_editing - In the implementation block
@property (assign,nonatomic) BOOL showFullSizeViewWithAlphaWhenTransforming; 
@property (assign,nonatomic) struct UIEdgeInsets minEdgeInsets; 				//@synthesize minEdgeInsets=_minEdgeInsets - In the implementation block
@property (assign,nonatomic) BOOL centerGridH; 				//@synthesize centerGridH=_centerGridH - In the implementation block
@property (assign,nonatomic) double minimumPressDuration; 
@property (assign,nonatomic) int style; 				//@synthesize style=_style - In the implementation block
@property (assign,nonatomic) int itemSpacingV; 				//@synthesize itemSpacingV=_itemSpacingV - In the implementation block
@property (assign,nonatomic) int itemSpacingH; 				//@synthesize itemSpacingH=_itemSpacingH - In the implementation block
@property (assign,nonatomic) id<MMGridViewLayoutStrategy> layoutStrategy; 				//@synthesize layoutStrategy=_layoutStrategy - In the implementation block
@property (assign,nonatomic) UIView* mainSuperView; 				//@synthesize mainSuperView=_mainSuperView - In the implementation block
@property (assign,nonatomic) id<MMGridViewActionDelegate> actionDelegate; 				//@synthesize actionDelegate=_actionDelegate - In the implementation block
@property (assign,nonatomic) id<MMGridViewTransformationDelegate> transformDelegate; 				//@synthesize transformDelegate=_transformDelegate - In the implementation block
@property (assign,nonatomic) id<MMGridViewDataSource> dataSource; 				//@synthesize dataSource=_dataSource - In the implementation block
@property (assign,nonatomic) id<MMGridViewSortingDelegate> sortingDelegate; 				//@synthesize sortingDelegate=_sortingDelegate - In the implementation block
-(void)commonInit;
-(void)swapObjectAtIndex:(int)arg1 withObjectAtIndex:(int)arg2 withAnimation:(int)arg3;
-(void)removeObjectAtIndex:(int)arg1 withAnimation:(int)arg2;
-(void)insertObjectAtIndex:(int)arg1 withAnimation:(int)arg2;
-(void)scrollToObjectAtIndex:(int)arg1 atScrollPosition:(int)arg2 animated:(BOOL)arg3;
-(void)reloadObjectAtIndex:(int)arg1 withAnimation:(int)arg2;
-(void)queueReusableCell:(id)arg1;
-(id)newItemSubViewForPosition:(int)arg1;
-(void)setLastPositionLoaded:(int)arg1;
-(void)setFirstPositionLoaded:(int)arg1;
-(void)transformingGestureDidBeginWithGesture:(id)arg1;
-(void)transformingGestureDidFinish;
-(void)setSubviewsCacheAsInvalid;
-(id)cellForItemAtIndex:(int)arg1;
-(void)sortingMoveDidContinueToPoint:(CGPoint)arg1;
-(void)sortingAutoScrollMovementCheck;
-(void)sortingMoveDidStopAtPoint:(CGPoint)arg1;
-(void)sortingMoveDidStartAtPoint:(CGPoint)arg1;
-(int)positionForItemSubview:(id)arg1;
-(BOOL)isInTransformingState;
-(void)cleanupUnseenItems;
-(CGRect)rectForPoint:(CGPoint)arg1 inPaggingMode:(BOOL)arg2;
-(void)applyWithoutAnimation:(id)arg1;
-(void)layoutSubviewsWithAnimation:(int)arg1;
-(void)loadRequiredItems;
-(void)relayoutItemsAnimated:(BOOL)arg1;
-(void)recomputeSizeAnimated:(BOOL)arg1;
-(void)setItemSubviewsCache:(id)arg1;
-(void)receivedWillRotateNotification:(id)arg1;
-(void)receivedMemoryWarningNotification:(id)arg1;
-(void)setMinEdgeInsets:(struct UIEdgeInsets)arg1;
-(void)setShowFullSizeViewWithAlphaWhenTransforming:(BOOL)arg1;
-(void)setItemSpacingV:(int)arg1;
-(void)setItemSpacingH:(int)arg1;
-(void)setMainSuperView:(id)arg1;
-(void)setLayoutStrategy:(id)arg1;
-(void)longPressGestureUpdated:(id)arg1;
-(void)sortingPanGestureUpdated:(id)arg1;
-(void)panGestureUpdated:(id)arg1;
-(void)rotationGestureUpdated:(id)arg1;
-(void)pinchGestureUpdated:(id)arg1;
-(void)tapGestureUpdated:(id)arg1;
-(void)setSortingDelegate:(id)arg1;
-(void)setTransformDelegate:(id)arg1;
-(void)setEnableEditOnLongPress:(BOOL)arg1;
-(void)setDisableEditOnEmptySpaceTap:(BOOL)arg1;
-(void)swapObjectAtIndex:(int)arg1 withObjectAtIndex:(int)arg2 animated:(BOOL)arg3;
-(void)removeObjectAtIndex:(int)arg1 animated:(BOOL)arg2;
-(void)insertObjectAtIndex:(int)arg1 animated:(BOOL)arg2;
-(void)reloadObjectAtIndex:(int)arg1 animated:(BOOL)arg2;
-(id)dequeueReusableCell;
-(void)contentOffset:(CGPoint)arg1;
-(void)setCenterGridH:(BOOL)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(id)initWithCoder:(id)arg1;
-(void)setDataSource:(id)arg1;
-(void)reloadData;
-(void)layoutSubviews;
-(id)dequeueReusableCellWithIdentifier:(id)arg1;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1;
-(void)setStyle:(int)arg1;
-(void)setMinimumPressDuration:(double)arg1;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
-(BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
-(void)setEditing:(BOOL)arg1;
-(void)setActionDelegate:(id)arg1;
-(id)init;
-(void)dealloc;
@end