/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:49 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMGridViewCell : UIView {
	UIView* _contentView; 
	BOOL _editing; 
	BOOL _inShakingMode; 
	CGSize _fullSize; 
	UIView* _fullSizeView; 
	BOOL _inFullSizeMode; 
	unsigned _defaultFullsizeViewResizingMask; 
	UIButton* _deleteButton; 
	id _deleteBlock; 
	UIImage* _deleteButtonIcon; 
	CGPoint deleteButtonOffset; 
	NSString* reuseIdentifier; 
	BOOL highlighted; 
}
@property (assign,getter=isHighlighted,nonatomic) BOOL highlighted; 
@property (nonatomic,retain) NSString* reuseIdentifier; 
@property (assign,nonatomic) CGPoint deleteButtonOffset; 
@property (nonatomic,retain) UIImage* deleteButtonIcon; 				//@synthesize deleteButtonIcon=_deleteButtonIcon - In the implementation block
@property (nonatomic,copy) id deleteBlock; 				//@synthesize deleteBlock=_deleteBlock - In the implementation block
@property (nonatomic,retain) UIButton* deleteButton; 				//@synthesize deleteButton=_deleteButton - In the implementation block
@property (assign,nonatomic) unsigned defaultFullsizeViewResizingMask; 				//@synthesize defaultFullsizeViewResizingMask=_defaultFullsizeViewResizingMask - In the implementation block
@property (getter=isInFullSizeMode,nonatomic,copy) BOOL inFullSizeMode; 				//@synthesize inFullSizeMode=_inFullSizeMode - In the implementation block
@property (nonatomic,retain) UIView* fullSizeView; 				//@synthesize fullSizeView=_fullSizeView - In the implementation block
@property (assign,nonatomic) CGSize fullSize; 				//@synthesize fullSize=_fullSize - In the implementation block
@property (getter=isInShakingMode,nonatomic,copy) BOOL inShakingMode; 				//@synthesize inShakingMode=_inShakingMode - In the implementation block
@property (assign,getter=isEditing,nonatomic) BOOL editing; 				//@synthesize editing=_editing - In the implementation block
@property (nonatomic,retain) UIView* contentView; 				//@synthesize contentView=_contentView - In the implementation block
-(void)setDeleteButton:(id)arg1;
-(void)setFullSizeView:(id)arg1;
-(void)switchToFullSizeMode:(BOOL)arg1;
-(void)stepToFullsizeWithAlpha:(float)arg1;
-(void)shake:(BOOL)arg1;
-(void)setFullSize:(CGSize)arg1;
-(void)setDeleteBlock:(id)arg1;
-(void)setDefaultFullsizeViewResizingMask:(unsigned)arg1;
-(void)actionDelete;
-(void)setDeleteButtonOffset:(CGPoint)arg1;
-(void)setDeleteButtonIcon:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2;
-(void)setContentView:(id)arg1;
-(void)setHighlighted:(BOOL)arg1;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
-(void)prepareForReuse;
-(void)setReuseIdentifier:(id)arg1;
-(void)setEditing:(BOOL)arg1;
-(id)init;
-(void)dealloc;
@end