/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:39 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMGridViewLayoutHorizontalPagedStrategy : MMGridViewLayoutHorizontalStrategy {
	int _numberOfItemsPerRow; 
	int _numberOfItemsPerPage; 
	int _numberOfPages; 
}
@property (nonatomic,copy) int numberOfPages; 				//@synthesize numberOfPages=_numberOfPages - In the implementation block
@property (nonatomic,copy) int numberOfItemsPerRow; 				//@synthesize numberOfItemsPerRow=_numberOfItemsPerRow - In the implementation block
@property (nonatomic,copy) int numberOfItemsPerPage; 				//@synthesize numberOfItemsPerPage=_numberOfItemsPerPage - In the implementation block
+(BOOL)requiresEnablingPaging;
-(struct _NSRange)rangeOfPositionsInBoundsFromOffset:(CGPoint)arg1;
-(void)rebaseWithItemCount:(int)arg1 insideOfBounds:(CGRect)arg2;
-(CGPoint)originForItemAtPosition:(int)arg1;
-(int)itemPositionFromLocation:(CGPoint)arg1;
-(int)positionForItemAtColumn:(int)arg1 row:(int)arg2 page:(int)arg3;
-(CGPoint)originForItemAtColumn:(int)arg1 row:(int)arg2 page:(int)arg3;
-(int)columnForItemAtPosition:(int)arg1;
-(int)rowForItemAtPosition:(int)arg1;
-(int)pageForItemAtIndex:(int)arg1;
@end