/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:44 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIScrollViewDelegate
@optional
-(void)scrollViewDidScroll(id):arg1 ;
-(void)scrollViewDidZoom(id):arg1 ;
-(void)scrollViewWillBeginDragging(id):arg1 ;
-(void)scrollViewWillEndDragging(id):arg1 withVelocity({):arg2 targetContentOffset(unsigned char):arg3 ;
-(void)scrollViewDidEndDragging(id):arg1 willDecelerate(BOOL):arg2 ;
-(void)scrollViewWillBeginDecelerating(id):arg1 ;
-(void)scrollViewDidEndDecelerating(id):arg1 ;
-(void)scrollViewDidEndScrollingAnimation(id):arg1 ;
-(id)viewForZoomingInScrollView(id):arg1 ;
-(void)scrollViewWillBeginZooming(id):arg1 withView(id):arg2 ;
-(void)scrollViewDidEndZooming(id):arg1 withView(id):arg2 atScale(float):arg3 ;
-(BOOL)scrollViewShouldScrollToTop(id):arg1 ;
-(void)scrollViewDidScrollToTop(id):arg1 ;
@end

@protocol MMImageScrollViewHelperDelegate
@property (nonatomic,copy) NSArray* gestureRecognizers; 
@property (assign,nonatomic) float maximumZoomScale; 
@property (assign,nonatomic) float minimumZoomScale; 
@property (assign,nonatomic) float zoomScale; 
@property (assign,nonatomic) CGRect frame; 
@optional
-(void)setFrame({):arg1 ;
-({);
-(void)setZoomScale(float):arg1 ;
-(float)zoomScale;
-(void)setMinimumZoomScale(float):arg1 ;
-(float)minimumZoomScale;
-(void)setMaximumZoomScale(float):arg1 ;
-(float)maximumZoomScale;
-(void)setGestureRecognizers(id):arg1 ;
-(id)gestureRecognizers;
-(void)zoomToRect({):arg1 animated(unsigned char):arg2 ;
-(void)setZoomScale(float):arg1 animated(BOOL):arg2 ;
-(void)removeGestureRecognizer(id):arg1 ;
-(void)addGestureRecognizer(id):arg1 ;
-(void)onDoubleTap(id):arg1 ;
-(void)onSingleTap(id):arg1 ;
-(id)getScrollView;
-(id)viewForZooming;
@end
