/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:26 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextViewDelegate.h>
#import <ISysCallCheckExt.h>
#import <UIActionSheetDelegate.h>
#import <MMGrowTextViewDelegate.h>
#import <BaseEmoticonViewDelegate.h>
#import <MMTransparentButtonDelegate.h>
#import <SelectAttachmentViewControllerDelegate.h>
#import <EmoticonTabbarViewControllerDelegate.h>
#import <VoiceInputViewDelegate.h>

@interface MMInputToolView : UIView <UITextViewDelegate, ISysCallCheckExt, UIActionSheetDelegate, MMGrowTextViewDelegate, BaseEmoticonViewDelegate, MMTransparentButtonDelegate, SelectAttachmentViewControllerDelegate, EmoticonTabbarViewControllerDelegate, VoiceInputViewDelegate> {
	UIButton* _inputModeChangeButton; 
	UIImageView* _toolView; 
	VoiceInputView* _voiceInputView; 
	SelectAttachmentView* _attachmentView; 
	UIView* _expressionView; 
	MMGrowTextView* _textView; 
	UIButton* _attachmentButton; 
	UIButton* _expressionDoneButton; 
	UIView* _recordingTipsView; 
	MMTransparentButton* _recordButton; 
	UIButton* _expressionButton; 
	RecordView* _recordView; 
	UIButton* _sendCaptrueView; 
	int _keyboardHeight; 
	int _inputMode; 
	int _positionMode; 
	int _contentMode; 
	id<MMInputToolViewDelegate> _delegate; 
	SelectAttachmentViewController* m_selectAttachmentViewController; 
	float _fKeyboardAnimationDuration; 
	int iMuteCount; 
	int _recordStatus; 
	id<MMInputToolViewBizDelegate> _uiDelegate; 
	NSURL* _nsLastCaptrueAssetURL; 
	ALAssetsLibrary* _oLibrary; 
	UIImage* _oCapturedImage; 
	BOOL m_bPositioning; 
}
@property (assign,nonatomic) NSString* text; 
@property (assign,nonatomic) BOOL m_bPositioning; 
@property (nonatomic,retain) RecordView* recordView; 				//@synthesize recordView=_recordView - In the implementation block
@property (assign,nonatomic) float fKeyboardAnimationDuration; 				//@synthesize fKeyboardAnimationDuration=_fKeyboardAnimationDuration - In the implementation block
@property (assign,nonatomic) int contentMode; 				//@synthesize contentMode=_contentMode - In the implementation block
@property (assign,nonatomic) int positionMode; 				//@synthesize positionMode=_positionMode - In the implementation block
@property (assign,nonatomic) int inputMode; 				//@synthesize inputMode=_inputMode - In the implementation block
@property (assign,nonatomic) id<MMInputToolViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) int keyboardHeight; 				//@synthesize keyboardHeight=_keyboardHeight - In the implementation block
@property (nonatomic,retain) MMTransparentButton* recordButton; 				//@synthesize recordButton=_recordButton - In the implementation block
@property (nonatomic,retain) UIView* recordingTipsView; 				//@synthesize recordingTipsView=_recordingTipsView - In the implementation block
@property (nonatomic,retain) UIButton* expressionDoneButton; 				//@synthesize expressionDoneButton=_expressionDoneButton - In the implementation block
@property (nonatomic,retain) UIButton* expressionButton; 				//@synthesize expressionButton=_expressionButton - In the implementation block
@property (nonatomic,retain) UIButton* attachmentButton; 				//@synthesize attachmentButton=_attachmentButton - In the implementation block
@property (nonatomic,retain) MMGrowTextView* textView; 				//@synthesize textView=_textView - In the implementation block
@property (nonatomic,retain) UIView* expressionView; 				//@synthesize expressionView=_expressionView - In the implementation block
@property (nonatomic,retain) UIImageView* toolView; 				//@synthesize toolView=_toolView - In the implementation block
@property (nonatomic,retain) UIButton* inputModeChangeButton; 				//@synthesize inputModeChangeButton=_inputModeChangeButton - In the implementation block
-(void)InputIsAvailableChanged:(BOOL)arg1;
-(void)Reset;
-(BOOL)CheckVoiceBtnState;
-(void)SetPeakPower:(float)arg1;
-(void)ShowPreparing;
-(void)ShowRecording;
-(void)ShowTooLongTips;
-(void)ShowTooShortTips;
-(void)HideRecordTips;
-(void)SetButtonHighlighted:(BOOL)arg1;
-(void)setContentMode:(int)arg1 animated:(BOOL)arg2;
-(void)setPoisitionMode:(int)arg1 animated:(BOOL)arg2;
-(void)setInputMode:(int)arg1 animated:(BOOL)arg2;
-(void)resetRecordView;
-(void)hideToolView:(BOOL)arg1;
-(void)insertString:(id)arg1;
-(void)setIsAllowWxTalk:(BOOL)arg1;
-(void)setIsAllowVoiceInput:(BOOL)arg1;
-(void)setIsAllowVoip:(BOOL)arg1 VoiceVoip:(BOOL)arg2;
-(void)setFKeyboardAnimationDuration:(float)arg1;
-(void)setKeyboardHeight:(int)arg1;
-(void)setVoiceEnabled:(BOOL)arg1;
-(void)initToolView;
-(id)initWithUIDelegate:(id)arg1;
-(void)initEmoticonView;
-(void)TextDidChanged:(id)arg1 selectedRange:(struct _NSRange)arg2;
-(void)setToolView:(id)arg1;
-(void)setRecordView:(id)arg1;
-(void)stopRecording:(id)arg1;
-(void)cancelRecording;
-(void)showRecord:(id)arg1;
-(void)showCancel:(id)arg1;
-(BOOL)isPointInRecordButton:(CGPoint)arg1;
-(void)toRecordStautsIdle;
-(void)toRecordStautsTooShortTips;
-(void)toRecordStautsTooLongTips;
-(void)toRecordStautsPerparing;
-(void)toRecordStautsRecording;
-(void)toRecordStautsRecordCancelTips;
-(void)initVoiceInputView;
-(void)initAttachmentView;
-(void)NotifyViewControllerPostionChanged:(BOOL)arg1 Animated:(BOOL)arg2;
-(void)onPositionAnimationEnd;
-(void)asyncStartNetDetect;
-(void)tryShowCaptrueButton;
-(void)showSendCaptrueViewAnimated:(BOOL)arg1;
-(void)initSubView;
-(void)setRecordingTipsView:(id)arg1;
-(void)setExpressionDoneButton:(id)arg1;
-(void)updateToolViewHeight;
-(void)hideSendCaptrueViewAnimated:(BOOL)arg1;
-(void)OnVoiceInputSendBtnClicked;
-(void)OnVoiceInputKeyboardBtnClicked;
-(void)TextViewDidEnter:(id)arg1;
-(void)updateAttachmentView;
-(void)setExpressionView:(id)arg1;
-(void)onSendCaptrueButtonClicked:(id)arg1;
-(void)onAttachmentModeChangeButtonClicked:(id)arg1;
-(void)setAttachmentButton:(id)arg1;
-(void)onExpressionButtonClicked:(id)arg1;
-(void)setExpressionButton:(id)arg1;
-(void)startRecording:(id)arg1;
-(void)updateRecordButtonDisabled;
-(void)setRecordButton:(id)arg1;
-(void)onInputModeChangeButtonClicked:(id)arg1;
-(void)setInputModeChangeButton:(id)arg1;
-(void)MMGrowTextView:(id)arg1 pasteImage:(id)arg2;
-(BOOL)MMGrowTextView:(id)arg1 shouldPasteImage:(id)arg2;
-(BOOL)TextViewDidDelete;
-(void)setKeyboardAnimationDuration:(float)arg1;
-(void)TextViewHeightDidChanged:(id)arg1;
-(void)didSelectorEmojiArt:(id)arg1;
-(void)deleteEmoticon;
-(void)addSelfDefinedEmoticon;
-(void)didSelectorSelfDefinedEmotcion:(id)arg1;
-(void)didSelectorEmoticon:(id)arg1;
-(void)MMTransparentButton_touchesCancelled:(id)arg1 withEvent:(id)arg2;
-(void)MMTransparentButton_touchesEnded:(id)arg1 withEvent:(id)arg2;
-(void)MMTransparentButton_touchesMoved:(id)arg1 withEvent:(id)arg2;
-(void)MMTransparentButton_touchesBegan:(id)arg1 withEvent:(id)arg2;
-(void)didSelectAttachmentAtIndex:(unsigned long)arg1;
-(void)onAdd3rdApp:(id)arg1;
-(void)onShare3rdAppButtonClicked:(id)arg1;
-(void)onVoiceVoipButtonClicked:(id)arg1;
-(void)onVideoVoipButtonClicked:(id)arg1;
-(void)onShareCardButtonClicked:(id)arg1;
-(void)onLocationButtonClicked:(id)arg1;
-(void)onCameraControllerClicked:(id)arg1;
-(void)onMediaBrowserClicked:(id)arg1;
-(void)onSendButtonClicked;
-(void)OnTextRecoged:(id)arg1;
-(id)GetCurrentText;
-(void)setPositionMode:(int)arg1;
-(void)setM_bPositioning:(BOOL)arg1;
-(void)expressionClicked:(unsigned long)arg1;
-(BOOL)isPointInRecordGarbageView:(CGPoint)arg1;
-(void)onWXTalkButtonClicked:(id)arg1;
-(void)onVoiceInputButtonClicked:(id)arg1;
-(void)keyboardWillHide:(float)arg1;
-(void)setText:(id)arg1;
-(BOOL)resignFirstResponder;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(BOOL)becomeFirstResponder;
-(void)setContentMode:(int)arg1;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2;
-(void)setTextView:(id)arg1;
-(void)keyboardWillShow:(float)arg1;
-(id)init;
-(void)dealloc;
-(void)setInputMode:(int)arg1;
-(void)setDelegate:(id)arg1;
@end