/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:40 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MMService.h>
#import <IMMLanguageMgrExt.h>
#import <IMMFontMgrExt.h>
#import <IContactMgrExt.h>
#import <IMMNewSessionMgrExt.h>

@interface MMMsgLogicManager : MMService <MMService, IMMLanguageMgrExt, IMMFontMgrExt, IContactMgrExt, IMMNewSessionMgrExt> {
	NSMutableArray* _arrLogicControllers; 
	BaseMsgContentLogicController* _topLogicController; 
	BaseMsgContentLogicController* _weixinLogicController; 
	BaseMsgContentLogicController* _roomLogicController; 
}
@property (nonatomic,retain) NSMutableArray* arrLogicControllers; 
@property (nonatomic,retain) BaseMsgContentLogicController* topLogicController; 
-(void)onDeleteContact:(id)arg1;
-(void)onModifyContact:(id)arg1;
-(BOOL)onServiceMemoryWarning;
-(void)onServiceReloadData;
-(void)onServiceInit;
-(void)PushLogicControllerByContact:(id)arg1 navigationController:(id)arg2 animated:(BOOL)arg3;
-(void)PopLogicController:(id)arg1;
-(void)PushSearchLogicControllerByContact:(id)arg1 navigationController:(id)arg2 ForMessageWrap:(id)arg3 animated:(BOOL)arg4;
-(id)GetCurrentLogicController;
-(void)PushLogicController:(id)arg1 navigationController:(id)arg2 animated:(BOOL)arg3;
-(void)onLanguageChange;
-(void)onFontSizeChange;
-(void)setMsgLogicToCache:(id)arg1;
-(id)GetReuseableLogicControllerFromCacheWithContact:(Class)arg1;
-(Class)GetLogicClassByContact:(id)arg1;
-(id)GetLogicControllerFromCacheWithContact:(id)arg1;
-(void)cleanUpLogicByName:(id)arg1;
-(void)onPluginsChanged:(id)arg1;
-(void)setTopLogicController:(id)arg1;
-(void)setArrLogicControllers:(id)arg1;
-(void)PushLBSRoomLogicControllerByContact:(id)arg1 navigationController:(id)arg2 animated:(BOOL)arg3;
-(void)onDeleteSession:(unsigned long)arg1;
-(void)cleanUp;
-(void)dealloc;
@end