/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:05 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMServiceCenter : NSObject {
	NSMutableDictionary* m_dicService; 
	NSRecursiveLock* m_lock; 
}
+(id)defaultCenter;
-(id)getService:(Class)arg1;
-(void)callServiceMemoryWarning;
-(void)callTerminate;
-(void)callEnterBackground;
-(void)callClearData;
-(void)callReloadData;
-(void)removeService:(Class)arg1;
-(id)init;
-(void)dealloc;
@end