/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:20 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMSwithItemView : UIView {
	MMSwitchView* oSwitch; 
	UILabel* oTip; 
}
@property (nonatomic,retain) UILabel* oTip; 
@property (nonatomic,retain) MMSwitchView* oSwitch; 
-(void)setOSwitch:(id)arg1;
-(void)setOTip:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
@end