/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:11 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MMUICommonUtil : NSObject {
}
+(id)getBarButtonWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3 style:(int)arg4;
+(id)getBarButtonWithImage:(id)arg1 target:(id)arg2 action:(SEL)arg3 style:(int)arg4;
+(id)getBackBarButtonWithProssibleTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+(id)getDefaultBackBarButtonWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+(id)getBarButtonWithImage:(id)arg1 highlightedImage:(id)arg2 target:(id)arg3 action:(SEL)arg4 style:(int)arg5;
+(id)getBackBarButtonWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+(id)getBackBarButtonWithImage:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+(id)getBackBarButtonWithImage:(id)arg1 highlightedImage:(id)arg2 target:(id)arg3 action:(SEL)arg4;
+(id)getBarButtonWithTitle:(id)arg1 withBackGroundImage:(id)arg2 withBackGroundImageHL:(id)arg3 target:(id)arg4 action:(SEL)arg5 style:(int)arg6;
+(id)getBarButtonWithImage:(id)arg1 withHighlightedImage:(id)arg2 withBackGroundImage:(id)arg3 withBackGroundImageHL:(id)arg4 target:(id)arg5 action:(SEL)arg6 style:(int)arg7;
@end