/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:43 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MMImageLoaderObserver.h>

@interface MMWebImageButton : UIButton <MMImageLoaderObserver> {
	UIImage* _defaultImage; 
	NSURL* _url; 
}
+(BOOL)CanLoadImage:(id)arg1;
-(void)ImageDidFail;
-(void)ImageDidLoad:(id)arg1;
-(void)setDefaultImage:(id)arg1;
-(BOOL)setImageURL:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
@end