/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:07 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IMMWebOnlineMgrExt.h>

@interface MMWebOnlineController : MMUIViewController <IMMWebOnlineMgrExt> {
}
-(void)onSwitchValueChange:(id)arg1;
-(void)onBack;
-(void)logoutWeb;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(id)init;
-(void)dealloc;
@end