/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:05 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ModDisturbSetting : PBGeneratedMessage {
	unsigned int hasDisturbSetting:1; 
	DisturbSetting* disturbSetting; 
}
@property (retain) DisturbSetting* disturbSetting; 
@property (assign) BOOL hasDisturbSetting; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasDisturbSetting:(BOOL)arg1;
-(id)SetDisturbSetting:(id)arg1;
-(void)setDisturbSetting:(id)arg1;
-(id)init;
-(void)dealloc;
@end