/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:58 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MMImgageBrowseViewDelegate.h>
#import <UIActionSheetDelegate.h>
#import <UIAlertViewDelegate.h>
#import <MessageObserverDelegate.h>

@interface MsgImageBrowseViewController : MMUIViewController <MMImgageBrowseViewDelegate, UIActionSheetDelegate, UIAlertViewDelegate, MessageObserverDelegate> {
	MMImageBrowseView* m_imageView; 
	MMAnimationTipView* m_tipView; 
	CMessageWrap* m_wrapMsg; 
	UIImage* m_image; 
	UIBarButtonItem* m_viewHDBarItem; 
	id<ImageBrowseDelegate> m_delegate; 
	unsigned m_uiEvent; 
	MMLoadingView* m_loadingView; 
	id m_singleTapGesture; 
	id m_doubleTapGesture; 
}
@property (nonatomic,retain) id m_doubleTapGesture; 
@property (nonatomic,retain) id m_singleTapGesture; 
@property (nonatomic,retain) UIImage* m_image; 
-(void)initView;
-(void)initData;
-(void)MessageReturn:(unsigned long)arg1 MessageInfo:(id)arg2 Event:(unsigned long)arg3;
-(void)showStatusBar;
-(void)willAppear;
-(void)initLoadingView;
-(void)hideStatusBar;
-(void)willDisapper;
-(void)initImageView;
-(id)initWithMsgWrap:(id)arg1;
-(void)handleViewWillDisappear;
-(void)handleViewWillAppear;
-(void)initNavigationBar;
-(void)onViewHDImage:(id)arg1;
-(void)onSavedPhotosAlbum:(id)arg1;
-(void)initToolBar;
-(void)addNvGestureRecognizer;
-(void)removeNvGestureRecognizer;
-(BOOL)isShowToolBar;
-(void)onSingleTapOnNavigationBar:(id)arg1;
-(void)startDownloadImg:(BOOL)arg1;
-(void)updateLoadingPercent:(unsigned long)arg1 PartLen:(unsigned long)arg2 DataLen:(unsigned long)arg3;
-(void)setM_image:(id)arg1;
-(void)stopImageLoading;
-(void)startImageLoading;
-(id)genDataLength:(unsigned long)arg1;
-(BOOL)isShowViewHDImage;
-(BOOL)isHDImageDownloaded;
-(void)adjustImageViewRect;
-(void)onOperate;
-(void)onSingleTapImageBrowseView;
-(void)DownloadHDImg;
-(void)UpdateImage;
-(void)UpdateHDImage:(int)arg1;
-(void)GetImage;
-(void)showToolBar;
-(void)hideToolBar;
-(void)setM_singleTapGesture:(id)arg1;
-(void)setM_doubleTapGesture:(id)arg1;
-(void)onDouTapOnNavigationBar:(id)arg1;
-(void)didAppear;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewDidLoad;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)didRotateFromInterfaceOrientation:(int)arg1;
-(void)setFullScreen:(BOOL)arg1;
-(void)exitFullScreen;
-(void)dealloc;
@end