/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:57 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIImagePickerControllerDelegate.h>
#import <UINavigationControllerDelegate.h>
#import <PickedImagePaneDelegate.h>
#import <MMCameraDelegate.h>

@interface MultiImagePickerController : UIImagePickerController <UIImagePickerControllerDelegate, UINavigationControllerDelegate, PickedImagePaneDelegate, MMCameraDelegate> {
	id<MultiImagePickerControllerDelegate> _mpdelegate; 
	PickedImagePane* _imagePane; 
	unsigned _maxSelectNum; 
	NSDictionary* _imageInfo; 
	BOOL _isStatusbarHidden; 
}
@property (assign,nonatomic) unsigned _maxSelectNum; 				//@synthesize maxSelectNum=_maxSelectNum - In the implementation block
@property (assign,nonatomic) id<MultiImagePickerControllerDelegate> _mpdelegate; 				//@synthesize mpdelegate=_mpdelegate - In the implementation block
-(id)getViewController;
-(void)mmCameraDidCancel;
-(void)mmCameraDidNextStep:(id)arg1 withPicture:(id)arg2 andMatteOrder:(int)arg3 choosed:(BOOL)arg4;
-(id)getNavigationController;
-(id)compressImage:(id)arg1;
-(void)set_maxSelectNum:(unsigned long)arg1;
-(void)set_mpdelegate:(id)arg1;
-(void)removeImages;
-(void)writeImageToFile:(id)arg1 withURL:(id)arg2;
-(void)pickedImagePaneDidFinishPickingImages:(id)arg1;
-(void)MultiImagePickerPreviewViewFinishSelectingImages:(id)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
-(void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(BOOL)arg3;
-(void)imagePickerControllerDidCancel:(id)arg1;
-(void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
-(id)init;
-(void)dealloc;
@end