/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:02 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MyWCDB : CBaseDB {
}
-(unsigned long)getUnReadMessageCount;
-(int)getHomepageTotalCount:(id)arg1;
-(void)RegisterTypeOfCol;
-(BOOL)initDB;
-(void)reloadDatabase;
-(BOOL)setWCMessageListRead:(id)arg1;
-(BOOL)setWCMessageRead:(id)arg1;
-(id)getWCMessagesFrom:(id)arg1 maxCount:(unsigned long)arg2;
-(id)getAllWCMessages;
-(id)getUnreadWCMessages;
-(id)getLatestMessage;
-(id)getStrangerMessagesOfItem:(id)arg1 partner:(id)arg2;
-(BOOL)addStrangerMessage:(id)arg1 toItem:(id)arg2;
-(BOOL)addNewWCMessage:(id)arg1;
-(BOOL)updateAllCacheWithDataItem:(id)arg1 useTransaction:(BOOL)arg2;
-(id)tryGetDataItemByItemID:(id)arg1;
-(BOOL)deleteRowInWCIndexForUser:(id)arg1 ByItemID:(id)arg2;
-(BOOL)setHomepageTotalCount:(int)arg1 username:(id)arg2;
-(BOOL)deleteAllIndexDataForUser:(id)arg1;
-(BOOL)updateWCIndexForUser:(id)arg1 WithDatas:(id)arg2 AfterItemID:(id)arg3;
-(id)getWCIndexDataItemListForUser:(id)arg1 AfterItemID:(id)arg2 andMaxCount:(int)arg3;
-(id)getMaxID;
-(void)setBGImgLiked:(id)arg1 username:(id)arg2;
-(BOOL)isBGImgLiked:(id)arg1 username:(id)arg2;
-(id)getWCTimeLineDataItemDictionaryByArrayItemID:(id)arg1;
-(BOOL)deleteRowInTimelineByItemID:(id)arg1;
-(BOOL)deleteAllTimelineTableData;
-(BOOL)updateWCTimeLineTableWithChangedDatas:(id)arg1;
-(BOOL)updateWCTimeLineTableWithDatas:(id)arg1 AfterItemID:(id)arg2;
-(id)getWCTimeLineDataItemListAfterItemID:(id)arg1 andMaxCount:(int)arg2;
-(id)getWCDataItemByItemID:(id)arg1;
-(id)getWCIndexDataItemListForUser:(id)arg1 withItemID:(id)arg2;
-(id)getOwnerByItemID:(id)arg1;
-(id)getWCTimeLineDataItemWithItemID:(id)arg1;
-(BOOL)setWCDataItem:(id)arg1 forItemID:(id)arg2;
-(BOOL)deleteDataItemFromTable:(id)arg1 ByItemID:(id)arg2;
-(BOOL)DelRowsInTable:(id)arg1 Where:(id)arg2;
-(id)getDataItemDictionaryFromTable:(id)arg1 KeyCol:(id)arg2 arrayItemID:(id)arg3;
-(id)getLatestDataItem:(id)arg1;
-(id)getDataItemListFromTable:(id)arg1 KeyCol:(id)arg2 afterItemID:(id)arg3 limit:(id)arg4;
-(BOOL)updateTable:(id)arg1 WithDatas:(id)arg2 keyCol:(id)arg3 AfterItemID:(id)arg4;
-(id)getMaxGroupHintInTable:(id)arg1 Where:(id)arg2;
-(id)getRowDataByItemID:(id)arg1 InTable:(id)arg2 KeyCol:(id)arg3;
-(BOOL)GetRowsInTable:(id)arg1 QryCol:(id)arg2 RetCol:(id)arg3 withWhere:(id)arg4 groupBy:(id)arg5 orderBy:(id)arg6 limit:(id)arg7;
-(id)getStrangerMessagesByCondition:(id)arg1 andGroupBy:(id)arg2 andOrder:(id)arg3 andLimit:(id)arg4;
-(BOOL)GetRowsInStrangerMessageQryCol:(id)arg1 RetCol:(id)arg2 withWhere:(id)arg3 groupBy:(id)arg4 orderBy:(id)arg5 limit:(id)arg6;
-(BOOL)InsertNewRowInStrangerMessage:(id)arg1;
-(BOOL)DelAllMyWCMessage;
-(BOOL)DelRowInMyWCMessage:(id)arg1;
-(BOOL)SetColsValueInMyWCMessageWhere:(id)arg1 ColValue:(id)arg2;
-(BOOL)SetColValueInMyWCMessage:(id)arg1 ColValue:(id)arg2;
-(id)getWCMessagesByCondition:(id)arg1 andGroupBy:(id)arg2 andOrder:(id)arg3 andLimit:(id)arg4;
-(BOOL)GetRowsInMyWCMessageQryCol:(id)arg1 RetCol:(id)arg2 withWhere:(id)arg3 groupBy:(id)arg4 orderBy:(id)arg5 limit:(id)arg6;
-(void)ResetWCAttrTable;
-(BOOL)DelRowInMyWCAttr:(id)arg1;
-(BOOL)InsertOrUpdateRowInMyWCAttr:(id)arg1 ColValue:(id)arg2;
-(BOOL)GetColValueInMyWCAttr:(id)arg1 QryCol:(id)arg2 RetCol:(id)arg3;
-(id)WCIndexTableNameForUser:(id)arg1;
-(BOOL)CreateWCIndexTableForUser:(id)arg1;
-(BOOL)CreateWCTimeLineTable;
-(BOOL)CreateStrangerMessageTable;
-(BOOL)CreateMyWCMessageTable;
-(BOOL)CreateMyWCAttrTable;
-(void)clearAllWCData;
-(BOOL)setAllWCMessagesRead;
-(id)getWCMessage:(id)arg1;
-(BOOL)deleteAllWCDataItem;
-(BOOL)deleteWCDataItemByItemID:(id)arg1;
-(BOOL)UpdateRowsInTable:(id)arg1 ColValue:(id)arg2 Where:(id)arg3;
-(BOOL)deleteAllMessages;
-(BOOL)deleteMessage:(id)arg1;
-(id)init;
-(void)dealloc;
@end