/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:47 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NetworkControl : PBGeneratedMessage {
	unsigned int hasPortList:1; 
	unsigned int hasTimeoutList:1; 
	unsigned int hasMinNoopInterval:1; 
	unsigned int hasMaxNoopInterval:1; 
	NSString* portList; 
	NSString* timeoutList; 
	unsigned minNoopInterval; 
	unsigned maxNoopInterval; 
}
@property (assign) unsigned maxNoopInterval; 
@property (assign) BOOL hasMaxNoopInterval; 
@property (assign) unsigned minNoopInterval; 
@property (assign) BOOL hasMinNoopInterval; 
@property (retain) NSString* timeoutList; 
@property (assign) BOOL hasTimeoutList; 
@property (retain) NSString* portList; 
@property (assign) BOOL hasPortList; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)setPortList:(id)arg1;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasMaxNoopInterval:(BOOL)arg1;
-(void)setHasMinNoopInterval:(BOOL)arg1;
-(void)setHasTimeoutList:(BOOL)arg1;
-(void)setHasPortList:(BOOL)arg1;
-(id)SetMaxNoopInterval:(unsigned)arg1;
-(id)SetMinNoopInterval:(unsigned)arg1;
-(id)SetTimeoutList:(id)arg1;
-(id)SetPortList:(id)arg1;
-(void)setMaxNoopInterval:(unsigned)arg1;
-(void)setMinNoopInterval:(unsigned)arg1;
-(void)setTimeoutList:(id)arg1;
-(id)init;
-(void)dealloc;
@end