/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:59 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NewDelMsg : PBGeneratedMessage {
	unsigned int hasMsgId:1; 
	unsigned int hasFromUserName:1; 
	unsigned int hasToUserName:1; 
	unsigned int hasMsgType:1; 
	int msgId; 
	NSString* fromUserName; 
	NSString* toUserName; 
	unsigned msgType; 
}
@property (assign) unsigned msgType; 
@property (assign) BOOL hasMsgType; 
@property (assign) int msgId; 
@property (assign) BOOL hasMsgId; 
@property (retain) NSString* toUserName; 
@property (assign) BOOL hasToUserName; 
@property (retain) NSString* fromUserName; 
@property (assign) BOOL hasFromUserName; 
+(id)parseFromData:(id)arg1;
-(id)SetToUserName:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasMsgType:(BOOL)arg1;
-(void)setHasToUserName:(BOOL)arg1;
-(void)setHasFromUserName:(BOOL)arg1;
-(void)setHasMsgId:(BOOL)arg1;
-(id)SetMsgType:(unsigned)arg1;
-(id)SetFromUserName:(id)arg1;
-(id)SetMsgId:(int)arg1;
-(void)setMsgType:(unsigned)arg1;
-(void)setMsgId:(int)arg1;
-(void)setToUserName:(id)arg1;
-(void)setFromUserName:(id)arg1;
-(id)init;
-(void)dealloc;
@end