/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:56 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NewSyncRequest : PBGeneratedMessage {
	unsigned int hasOplog:1; 
	unsigned int hasKeyBuf:1; 
	unsigned int hasSelector:1; 
	unsigned int hasScene:1; 
	CmdList* oplog; 
	SKBuiltinBuffer_t* keyBuf; 
	unsigned selector; 
	unsigned scene; 
}
@property (assign) unsigned scene; 
@property (assign) BOOL hasScene; 
@property (retain) SKBuiltinBuffer_t* keyBuf; 
@property (assign) BOOL hasKeyBuf; 
@property (assign) unsigned selector; 
@property (assign) BOOL hasSelector; 
@property (retain) CmdList* oplog; 
@property (assign) BOOL hasOplog; 
+(id)parseFromData:(id)arg1;
-(id)SetScene:(unsigned)arg1;
-(id)SetSelector:(unsigned)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasKeyBuf:(BOOL)arg1;
-(void)setHasSelector:(BOOL)arg1;
-(void)setHasOplog:(BOOL)arg1;
-(id)SetKeyBuf:(id)arg1;
-(id)SetOplog:(id)arg1;
-(void)setKeyBuf:(id)arg1;
-(void)setOplog:(id)arg1;
-(void)setHasScene:(BOOL)arg1;
-(void)setScene:(unsigned)arg1;
-(void)setSelector:(unsigned)arg1;
-(id)init;
-(void)dealloc;
@end