/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:08 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NewSyncResponse : PBGeneratedMessage {
	unsigned int hasRet:1; 
	unsigned int hasCmdList:1; 
	unsigned int hasKeyBuf:1; 
	unsigned int hasContinueFlag:1; 
	unsigned int hasStatus:1; 
	int ret; 
	CmdList* cmdList; 
	SKBuiltinBuffer_t* keyBuf; 
	unsigned continueFlag; 
	unsigned status; 
}
@property (assign) unsigned status; 
@property (assign) BOOL hasStatus; 
@property (retain) SKBuiltinBuffer_t* keyBuf; 
@property (assign) BOOL hasKeyBuf; 
@property (assign) unsigned continueFlag; 
@property (assign) BOOL hasContinueFlag; 
@property (retain) CmdList* cmdList; 
@property (assign) BOOL hasCmdList; 
@property (assign) int ret; 
@property (assign) BOOL hasRet; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(id)SetStatus:(unsigned)arg1;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasContinueFlag:(BOOL)arg1;
-(void)setHasCmdList:(BOOL)arg1;
-(id)SetContinueFlag:(unsigned)arg1;
-(id)SetCmdList:(id)arg1;
-(void)setContinueFlag:(unsigned)arg1;
-(void)setCmdList:(id)arg1;
-(void)setHasKeyBuf:(BOOL)arg1;
-(id)SetKeyBuf:(id)arg1;
-(void)setKeyBuf:(id)arg1;
-(void)setHasRet:(BOOL)arg1;
-(id)SetRet:(int)arg1;
-(void)setRet:(int)arg1;
-(void)setStatus:(unsigned)arg1;
-(void)setHasStatus:(BOOL)arg1;
-(id)init;
-(void)dealloc;
@end