/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:04 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol MMService
@optional
-(void)onServiceClearData;
-(BOOL)onServiceMemoryWarning;
-(void)onServiceTerminate;
-(void)onServiceEnterBackground;
-(void)onServiceReloadData;
-(void)onServiceInit;
@end

@protocol NotifyFromEventDelegate
@optional
-(void)SaveSettingExt;
-(id)GetSettingExt;
-(void)SaveSetting;
-(id)GetSetting;
-(BOOL)IsLogIn;
-(id)GetLocalInfo;
-(void)SaveLocalInfo(BOOL):arg1 ;
-(void)SaveUpdateInfo;
-(BOOL)NotifyToHandleSyncResp(id):arg1 Push(BOOL):arg2 ShowPush(BOOL):arg3 ;
-(BOOL)IsDoingDNS;
-(void)SetLongConnMgr(id):arg1 ;
-(unsigned long)GetNetworkReachabilitySeed;
-(void)NotifyFromEvent(id):arg1 Message(unsigned long):arg2 MessageInfo(id):arg3 ;
-(void)SetSelector(unsigned long):arg1 ;
-(unsigned long)GetSelector;
-(id)GetUpdateInfo;
-(void)SpeedyNotifyFromEvent(id):arg1 Message(unsigned long):arg2 MessageInfo(id):arg3 ;
@end
