/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:32 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol NSCoding
@required
-(id)initWithCoder(id):arg1 ;
-(void)encodeWithCoder(id):arg1 ;
-(id)initWithCoder(id):arg1 ;
-(void)encodeWithCoder(id):arg1 ;
@end
