/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:25 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface OpenAppInfo : PBGeneratedMessage {
	unsigned int hasAppId:1; 
	unsigned int hasAppName:1; 
	unsigned int hasAppDescription:1; 
	unsigned int hasAppIconUrl:1; 
	unsigned int hasAppStoreUrl:1; 
	unsigned int hasAppWatermarkUrl:1; 
	unsigned int hasAndroidPackageName:1; 
	unsigned int hasAndroidSignature:1; 
	unsigned int hasAppName4EnUs:1; 
	unsigned int hasAppDescription4EnUs:1; 
	unsigned int hasAppName4ZhTw:1; 
	unsigned int hasAppDescription4ZhTw:1; 
	unsigned int hasAppVersion:1; 
	NSString* appId; 
	NSString* appName; 
	NSString* appDescription; 
	NSString* appIconUrl; 
	NSString* appStoreUrl; 
	NSString* appWatermarkUrl; 
	NSString* androidPackageName; 
	NSString* androidSignature; 
	NSString* appName4EnUs; 
	NSString* appDescription4EnUs; 
	NSString* appName4ZhTw; 
	NSString* appDescription4ZhTw; 
	unsigned appVersion; 
}
@property (retain) NSString* appDescription4ZhTw; 
@property (assign) BOOL hasAppDescription4ZhTw; 
@property (retain) NSString* appName4ZhTw; 
@property (assign) BOOL hasAppName4ZhTw; 
@property (retain) NSString* appDescription4EnUs; 
@property (assign) BOOL hasAppDescription4EnUs; 
@property (retain) NSString* appName4EnUs; 
@property (assign) BOOL hasAppName4EnUs; 
@property (retain) NSString* androidSignature; 
@property (assign) BOOL hasAndroidSignature; 
@property (retain) NSString* androidPackageName; 
@property (assign) BOOL hasAndroidPackageName; 
@property (retain) NSString* appWatermarkUrl; 
@property (assign) BOOL hasAppWatermarkUrl; 
@property (assign) unsigned appVersion; 
@property (assign) BOOL hasAppVersion; 
@property (retain) NSString* appStoreUrl; 
@property (assign) BOOL hasAppStoreUrl; 
@property (retain) NSString* appIconUrl; 
@property (assign) BOOL hasAppIconUrl; 
@property (retain) NSString* appDescription; 
@property (assign) BOOL hasAppDescription; 
@property (retain) NSString* appName; 
@property (assign) BOOL hasAppName; 
@property (retain) NSString* appId; 
@property (assign) BOOL hasAppId; 
+(id)parseFromData:(id)arg1;
-(id)SetAppId:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasAppDescription4ZhTw:(BOOL)arg1;
-(void)setHasAppName4ZhTw:(BOOL)arg1;
-(void)setHasAppDescription4EnUs:(BOOL)arg1;
-(void)setHasAppName4EnUs:(BOOL)arg1;
-(void)setHasAndroidSignature:(BOOL)arg1;
-(void)setHasAndroidPackageName:(BOOL)arg1;
-(void)setHasAppWatermarkUrl:(BOOL)arg1;
-(void)setHasAppVersion:(BOOL)arg1;
-(void)setHasAppStoreUrl:(BOOL)arg1;
-(void)setHasAppIconUrl:(BOOL)arg1;
-(void)setHasAppDescription:(BOOL)arg1;
-(void)setHasAppName:(BOOL)arg1;
-(id)SetAppDescription4ZhTw:(id)arg1;
-(id)SetAppName4ZhTw:(id)arg1;
-(id)SetAppDescription4EnUs:(id)arg1;
-(id)SetAppName4EnUs:(id)arg1;
-(id)SetAndroidSignature:(id)arg1;
-(id)SetAndroidPackageName:(id)arg1;
-(id)SetAppWatermarkUrl:(id)arg1;
-(id)SetAppVersion:(unsigned)arg1;
-(id)SetAppStoreUrl:(id)arg1;
-(id)SetAppIconUrl:(id)arg1;
-(id)SetAppDescription:(id)arg1;
-(id)SetAppName:(id)arg1;
-(void)setAppDescription4ZhTw:(id)arg1;
-(void)setAppName4ZhTw:(id)arg1;
-(void)setAppDescription4EnUs:(id)arg1;
-(void)setAppName4EnUs:(id)arg1;
-(void)setAndroidSignature:(id)arg1;
-(void)setAndroidPackageName:(id)arg1;
-(void)setAppWatermarkUrl:(id)arg1;
-(void)setAppStoreUrl:(id)arg1;
-(void)setAppIconUrl:(id)arg1;
-(void)setAppDescription:(id)arg1;
-(void)setHasAppId:(BOOL)arg1;
-(void)setAppName:(id)arg1;
-(void)setAppId:(id)arg1;
-(void)setAppVersion:(unsigned)arg1;
-(id)init;
-(void)dealloc;
@end