/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:14 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WCImageScrollViewDelegate.h>

@interface PageScrollView : MMScrollView <WCImageScrollViewDelegate> {
	NSMutableSet* _recycledPages; 
	NSMutableSet* _visiblePages; 
	BOOL _reloading; 
	BOOL _supportOrientation; 
	id<PageScrollViewDataSource> _pageDataSource; 
	id<PageScrollViewDelegate> _pageDelegate; 
}
@property (assign,nonatomic) id<PageScrollViewDelegate> pageDelegate; 				//@synthesize pageDelegate=_pageDelegate - In the implementation block
@property (assign,nonatomic) id<PageScrollViewDataSource> pageDataSource; 				//@synthesize pageDataSource=_pageDataSource - In the implementation block
@property (nonatomic,retain) NSMutableSet* visiblePages; 				//@synthesize visiblePages=_visiblePages - In the implementation block
@property (nonatomic,retain) NSMutableSet* recycledPages; 				//@synthesize recycledPages=_recycledPages - In the implementation block
@property (assign,nonatomic) BOOL supportOrientation; 				//@synthesize supportOrientation=_supportOrientation - In the implementation block
-(void)onDoubleTapWCImageScrollView;
-(void)onSingleTapWCImageScrollView;
-(void)setSupportOrientation:(BOOL)arg1;
-(id)dequeueRecycledPage;
-(void)updatePageAtIndex:(unsigned)arg1;
-(unsigned)getCurrentIndex;
-(id)getViewForItem:(unsigned)arg1;
-(CGRect)frameForPageAtItem:(unsigned)arg1;
-(BOOL)isDisplayingPageForItem:(unsigned)arg1;
-(unsigned)getItemsCount;
-(void)setRecycledPages:(id)arg1;
-(void)setVisiblePages:(id)arg1;
-(void)setPageDataSource:(id)arg1;
-(void)setPageDelegate:(id)arg1;
-(void)removeVisiblePageAtIndex:(unsigned)arg1;
-(void)foreceReloadData;
-(id)initWithFrame:(CGRect)arg1;
-(void)reloadData;
-(void)dealloc;
@end