/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:45 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PBMessage.h>

@interface PBAbstractMessage : NSObject <PBMessage> {
}
-(int)serializedSize;
-(id)builder;
-(id)unknownFields;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)writeToOutputStream:(id)arg1;
-(id)defaultInstance;
-(id)serializedData;
-(id)init;
@end