/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:53 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PBCodedInputStream : NSObject {
	NSMutableData* buffer; 
	int bufferSize; 
	int bufferSizeAfterLimit; 
	int bufferPos; 
	NSInputStream* input; 
	int lastTag; 
	int totalBytesRetired; 
	int currentLimit; 
	int recursionDepth; 
	int recursionLimit; 
	int sizeLimit; 
}
@property (retain) NSInputStream* input; 
@property (retain) NSMutableData* buffer; 
+(id)streamWithData:(id)arg1;
+(id)streamWithInputStream:(id)arg1;
-(void)commonInit;
-(void)readMessage:(id)arg1;
-(int)bytesUntilLimit;
-(void)popLimit:(int)arg1;
-(int)pushLimit:(int)arg1;
-(int)readRawVarint32;
-(BOOL)readBool;
-(int)readUInt32;
-(int)readTag;
-(long long)readUInt64;
-(void)checkLastTagWas:(int)arg1;
-(BOOL)refillBuffer:(BOOL)arg1;
-(void)recomputeBufferSizeAfterLimit;
-(BOOL)readRawByte;
-(id)readRawData:(int)arg1;
-(long long)readRawVarint64;
-(BOOL)skipField:(int)arg1;
-(int)readRawLittleEndian32;
-(void)skipMessage;
-(void)skipRawData:(int)arg1;
-(long long)readRawLittleEndian64;
-(void)resetSizeCounter;
-(int)setSizeLimit:(int)arg1;
-(int)setRecursionLimit:(int)arg1;
-(long long)readSInt64;
-(int)readSInt32;
-(long long)readSFixed64;
-(int)readSFixed32;
-(int)readEnum;
-(void)readUnknownGroup:(int)arg1 builder:(id)arg2;
-(void)readGroup:(int)arg1 builder:(id)arg2;
-(id)initWithData:(id)arg1;
-(id)readString;
-(BOOL)isAtEnd;
-(id)initWithInputStream:(id)arg1;
-(double)readDouble;
-(int)readInt32;
-(long long)readInt64;
-(int)readFixed32;
-(long long)readFixed64;
-(id)readData;
-(void)setBuffer:(id)arg1;
-(void)dealloc;
-(void)setInput:(id)arg1;
-(float)readFloat;
@end