/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:04 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PBCodedOutputStream : NSObject {
	NSMutableData* buffer; 
	int position; 
	NSOutputStream* output; 
}
@property (assign) int position; 
@property (retain) NSMutableData* buffer; 
@property (retain) NSOutputStream* output; 
+(id)streamWithOutputStream:(id)arg1;
+(id)streamWithData:(id)arg1;
+(id)streamWithOutputStream:(id)arg1 bufferSize:(int)arg2;
-(void)writeMessage:(int)arg1 value:(id)arg2;
-(void)writeUInt32NoTag:(int)arg1;
-(void)writeRawVarint32:(int)arg1;
-(void)writeData:(int)arg1 value:(id)arg2;
-(void)writeBool:(int)arg1 value:(BOOL)arg2;
-(void)writeUInt32:(int)arg1 value:(int)arg2;
-(void)writeString:(int)arg1 value:(id)arg2;
-(void)writeInt32NoTag:(int)arg1;
-(void)writeDouble:(int)arg1 value:(double)arg2;
-(void)writeFloat:(int)arg1 value:(float)arg2;
-(void)writeUInt64:(int)arg1 value:(long long)arg2;
-(void)writeInt64:(int)arg1 value:(long long)arg2;
-(void)writeInt32:(int)arg1 value:(int)arg2;
-(void)writeRawData:(id)arg1 offset:(int)arg2 length:(int)arg3;
-(int)spaceLeft;
-(void)refreshBuffer;
-(void)writeSInt64NoTag:(long long)arg1;
-(void)writeSInt32NoTag:(int)arg1;
-(void)writeSFixed64NoTag:(long long)arg1;
-(void)writeSFixed32NoTag:(int)arg1;
-(void)writeEnumNoTag:(int)arg1;
-(void)writeDataNoTag:(id)arg1;
-(void)writeMessageNoTag:(id)arg1;
-(void)writeUnknownGroupNoTag:(int)arg1 value:(id)arg2;
-(void)writeGroupNoTag:(int)arg1 value:(id)arg2;
-(void)writeStringNoTag:(id)arg1;
-(void)writeRawData:(id)arg1;
-(void)writeBoolNoTag:(BOOL)arg1;
-(void)writeRawByte:(unsigned char)arg1;
-(void)writeFixed32NoTag:(int)arg1;
-(void)writeFixed64NoTag:(long long)arg1;
-(void)writeInt64NoTag:(long long)arg1;
-(void)writeUInt64NoTag:(long long)arg1;
-(void)writeRawVarint64:(long long)arg1;
-(void)writeFloatNoTag:(float)arg1;
-(void)writeRawLittleEndian32:(int)arg1;
-(void)writeDoubleNoTag:(double)arg1;
-(void)writeTag:(int)arg1 format:(int)arg2;
-(void)writeRawLittleEndian64:(long long)arg1;
-(id)initWithOutputStream:(id)arg1 data:(id)arg2;
-(void)checkNoSpaceLeft;
-(void)writeRawMessageSetExtension:(int)arg1 value:(id)arg2;
-(void)writeMessageSetExtension:(int)arg1 value:(id)arg2;
-(void)writeSInt64:(int)arg1 value:(long long)arg2;
-(void)writeSInt32:(int)arg1 value:(int)arg2;
-(void)writeSFixed64:(int)arg1 value:(long long)arg2;
-(void)writeSFixed32:(int)arg1 value:(int)arg2;
-(void)writeEnum:(int)arg1 value:(int)arg2;
-(void)writeUnknownGroup:(int)arg1 value:(id)arg2;
-(void)writeGroup:(int)arg1 value:(id)arg2;
-(void)writeFixed32:(int)arg1 value:(int)arg2;
-(void)writeFixed64:(int)arg1 value:(long long)arg2;
-(void)flush;
-(void)setPosition:(int)arg1;
-(void)setBuffer:(id)arg1;
-(void)dealloc;
-(void)setOutput:(id)arg1;
@end