/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:46 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PBExtensionRegistry : NSObject {
	NSDictionary* classMap; 
}
@property (retain) NSDictionary* classMap; 
+(id)emptyRegistry;
+(void)initialize;
-(void)setClassMap:(id)arg1;
@end