/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:37 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PBField : NSObject {
	NSMutableArray* mutableVarintList; 
	NSMutableArray* mutableFixed32List; 
	NSMutableArray* mutableFixed64List; 
	NSMutableArray* mutableLengthDelimitedList; 
	NSMutableArray* mutableGroupList; 
}
@property (retain) NSMutableArray* mutableGroupList; 
@property (retain) NSMutableArray* mutableLengthDelimitedList; 
@property (retain) NSMutableArray* mutableFixed64List; 
@property (retain) NSMutableArray* mutableFixed32List; 
@property (retain) NSMutableArray* mutableVarintList; 
+(id)defaultInstance;
+(void)initialize;
-(id)lengthDelimitedList;
-(id)fixed64List;
-(id)fixed32List;
-(id)varintList;
-(void)setMutableGroupList:(id)arg1;
-(void)setMutableLengthDelimitedList:(id)arg1;
-(void)setMutableFixed64List:(id)arg1;
-(void)setMutableFixed32List:(id)arg1;
-(void)setMutableVarintList:(id)arg1;
-(int)getSerializedSizeAsMessageSetExtension:(int)arg1;
-(void)writeAsMessageSetExtensionTo:(int)arg1 output:(id)arg2;
-(int)getSerializedSize:(int)arg1;
-(void)writeTo:(int)arg1 output:(id)arg2;
-(id)groupList;
-(void)dealloc;
@end