/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:04 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PBGeneratedMessage : PBAbstractMessage {
	PBUnknownFieldSet* unknownFields; 
}
@property (retain) PBUnknownFieldSet* unknownFields; 
-(id)SetBaseRequest:(id)arg1;
-(BOOL)parseUnknownField:(id)arg1 unknownFields:(id)arg2 tag:(int)arg3;
-(id)mergeFromData:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(unsigned long)continueFlag;
-(void)setUnknownFields:(id)arg1;
-(id)init;
-(void)dealloc;
@end