/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:57 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol PBMessage_Builder
@required
-(id)mergeFromData(id):arg1 ;
-(id)mergeFromCodedInputStream(id):arg1 ;
-(id)mergeUnknownFields(id):arg1 ;
-(id)setUnknownFields(id):arg1 ;
-(id)unknownFields;
-(id)build;
-(id)mergeFromData(id):arg1 ;
-(id)mergeFromCodedInputStream(id):arg1 ;
-(id)mergeUnknownFields(id):arg1 ;
-(id)setUnknownFields(id):arg1 ;
-(id)unknownFields;
-(id)build;
@end
