/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:45 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol PBMessage
@required
-(id)mergeFromCodedInputStream(id):arg1 ;
-(id)builder;
-(id)serializedData;
-(void)writeToCodedOutputStream(id):arg1 ;
-(int)serializedSize;
-(id)unknownFields;
-(id)defaultInstance;
-(id)mergeFromCodedInputStream(id):arg1 ;
-(id)builder;
-(id)serializedData;
-(void)writeToCodedOutputStream(id):arg1 ;
-(int)serializedSize;
-(id)unknownFields;
-(id)defaultInstance;
@end
