/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:12 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PBMutableField : PBField {
}
+(id)field;
-(id)addGroup:(id)arg1;
-(id)addLengthDelimited:(id)arg1;
-(id)addFixed64:(long long)arg1;
-(id)addFixed32:(int)arg1;
-(id)addVarint:(long long)arg1;
-(id)mergeFromField:(id)arg1;
-(id)clear;
-(id)init;
-(void)dealloc;
@end