/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:27 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PBTextFormat : NSObject {
}
+(long long)parseInteger:(id)arg1 isSigned:(BOOL)arg2 isLong:(BOOL)arg3;
+(id)unescapeBytes:(id)arg1;
+(long long)parseUInt64:(id)arg1;
+(long long)parseInt64:(id)arg1;
+(int)parseUInt32:(id)arg1;
+(int)parseInt32:(id)arg1;
@end