/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:56 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PBUnknownFieldSet_Builder : NSObject {
	NSMutableDictionary* fields; 
	int lastFieldNumber; 
	PBMutableField* lastField; 
}
@property (retain) PBMutableField* lastField; 
@property (assign) int lastFieldNumber; 
@property (retain) NSMutableDictionary* fields; 
+(id)newBuilder:(id)arg1;
-(id)mergeFromData:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(id)mergeUnknownFields:(id)arg1;
-(BOOL)mergeFieldFrom:(int)arg1 input:(id)arg2;
-(id)mergeFromInputStream:(id)arg1;
-(void)setFields:(id)arg1;
-(BOOL)hasField:(int)arg1;
-(id)mergeField:(id)arg1 forNumber:(int)arg2;
-(id)getFieldBuilder:(int)arg1;
-(id)addField:(id)arg1 forNumber:(int)arg2;
-(void)setLastField:(id)arg1;
-(void)setLastFieldNumber:(int)arg1;
-(id)mergeVarintField:(int)arg1 value:(int)arg2;
-(id)clear;
-(id)build;
-(id)init;
-(void)dealloc;
@end