/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:23 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PBUnknownFieldSet : NSObject {
	NSDictionary* fields; 
}
@property (retain) NSDictionary* fields; 
+(id)parseFromData:(id)arg1;
+(id)builder;
+(id)builderWithUnknownFields:(id)arg1;
+(id)setWithFields:(id)arg1;
+(id)parseFromInputStream:(id)arg1;
+(id)parseFromCodedInputStream:(id)arg1;
+(id)defaultInstance;
+(void)initialize;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(void)writeToOutputStream:(id)arg1;
-(id)initWithFields:(id)arg1;
-(void)setFields:(id)arg1;
-(int)serializedSizeAsMessageSet;
-(void)writeAsMessageSetTo:(id)arg1;
-(id)getField:(int)arg1;
-(BOOL)hasField:(int)arg1;
-(id)serializedData;
-(void)dealloc;
@end