/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:40 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PerformLogInfo : NSObject {
	unsigned eventid; 
	unsigned begin_time; 
	unsigned end_time; 
	unsigned max_duration; 
	unsigned min_duration; 
	unsigned avg_duration; 
	unsigned log_count; 
}
@property (assign,nonatomic) unsigned log_count; 
@property (assign,nonatomic) unsigned avg_duration; 
@property (assign,nonatomic) unsigned min_duration; 
@property (assign,nonatomic) unsigned max_duration; 
@property (assign,nonatomic) unsigned end_time; 
@property (assign,nonatomic) unsigned begin_time; 
@property (assign,nonatomic) unsigned eventid; 
-(void)setMax_duration:(unsigned long)arg1;
-(void)setMin_duration:(unsigned long)arg1;
-(void)setAvg_duration:(unsigned long)arg1;
-(void)setEventid:(unsigned long)arg1;
-(void)setLog_count:(unsigned long)arg1;
-(void)setBegin_time:(unsigned long)arg1;
-(void)setEnd_time:(unsigned long)arg1;
-(id)init;
-(void)dealloc;
@end