/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:09 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PickedImagePane : UIView {
	NSMutableArray* _imageInfos; 
	UIScrollView* _scrollView; 
	unsigned _maxSelectNum; 
	id<PickedImagePaneDelegate> _delegate; 
}
@property (assign,nonatomic) unsigned _maxSelectNum; 				//@synthesize maxSelectNum=_maxSelectNum - In the implementation block
@property (assign,nonatomic) id<PickedImagePaneDelegate> _delegate; 				//@synthesize delegate=_delegate - In the implementation block
-(void)set_delegate:(id)arg1;
-(void)onImageClicked:(id)arg1;
-(void)set_maxSelectNum:(unsigned long)arg1;
-(id)initWithFrame:(CGRect)arg1 andMaxSelectNum:(unsigned long)arg2;
-(void)updateCount:(int)arg1;
-(void)onDoneBtnClicked:(id)arg1;
-(BOOL)addImage:(id)arg1;
-(void)dealloc;
@end