/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:57 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIImagePickerControllerDelegate
@optional
-(void)imagePickerController(id):arg1 didFinishPickingImage(id):arg2 editingInfo(id):arg3 ;
-(void)imagePickerController(id):arg1 didFinishPickingMediaWithInfo(id):arg2 ;
-(void)imagePickerControllerDidCancel(id):arg1 ;
@end

@protocol UINavigationControllerDelegate
@optional
-(void)navigationController(id):arg1 willShowViewController(id):arg2 animated(BOOL):arg3 ;
-(void)navigationController(id):arg1 didShowViewController(id):arg2 animated(BOOL):arg3 ;
@end

@protocol PickedImagePaneDelegate
@required
-(void)pickedImagePaneDidFinishPickingImages(id):arg1 ;
-(void)pickedImagePaneDidFinishPickingImages(id):arg1 ;
@end
