/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:56 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MMImgageBrowseViewDelegate.h>

@interface PickImageForCommonViewController : MMUIViewController <MMImgageBrowseViewDelegate> {
	MMImageBrowseView* m_imageView; 
	UIImage* m_image; 
	id<ImageBrowseDelegate> m_delegate; 
	id m_singleTapOnNav; 
}
@property (assign,nonatomic) id<ImageBrowseDelegate> m_delegate; 
@property (nonatomic,retain) id m_singleTapOnNav; 
-(void)initView;
-(void)setM_delegate:(id)arg1;
-(void)showStatusBar;
-(void)willAppear;
-(void)hideStatusBar;
-(void)willDisapper;
-(void)initImageView;
-(void)onTopBarFrameChanged;
-(void)handleViewWillDisappear;
-(void)handleViewWillAppear;
-(void)initNavigationBar;
-(void)addNvGestureRecognizer;
-(void)removeNvGestureRecognizer;
-(void)onSingleTapOnNavigationBar:(id)arg1;
-(void)doCancel;
-(void)doSelect;
-(void)adjustImageViewRect;
-(void)setM_singleTapOnNav:(id)arg1;
-(void)onSingleTapImageBrowseView;
-(id)initWithImage:(id)arg1;
-(void)viewDidLoad;
-(void)setFullScreen:(BOOL)arg1;
-(void)exitFullScreen;
-(void)dealloc;
@end