/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:59 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MMImgageBrowseViewDelegate.h>
#import <UIActionSheetDelegate.h>
#import <UIAlertViewDelegate.h>
#import <MMCameraDelegate.h>

@interface PickImageForHDViewController : MMUIViewController <MMImgageBrowseViewDelegate, UIActionSheetDelegate, UIAlertViewDelegate, MMCameraDelegate> {
	MMImageBrowseView* m_imageView; 
	MMLoadingView* m_loadingView; 
	UIImage* m_image; 
	NSData* m_dtImg; 
	id<ImageBrowseDelegate> m_delegate; 
	UILabel* m_hdImageSizelabel; 
	id m_singleTapOnNav; 
}
@property (assign,nonatomic) id<ImageBrowseDelegate> m_delegate; 
@property (nonatomic,retain) id m_singleTapOnNav; 
-(void)initView;
-(void)setM_delegate:(id)arg1;
-(id)getViewController;
-(void)initData;
-(void)showStatusBar;
-(void)willAppear;
-(void)initLoadingView;
-(void)hideStatusBar;
-(void)willDisapper;
-(void)mmCameraDidNextStep:(id)arg1 withPicture:(id)arg2 andMatteOrder:(int)arg3 choosed:(BOOL)arg4;
-(id)getNavigationController;
-(void)initImageView;
-(void)onTopBarFrameChanged;
-(void)matteImage:(id)arg1;
-(void)doMatte;
-(BOOL)isCurHDImage;
-(void)startMatte;
-(void)handleViewWillDisappear;
-(void)handleViewWillAppear;
-(void)initNavigationBar;
-(id)genTranItem;
-(id)genHDImageSizeLabel;
-(void)onMatte:(id)arg1;
-(void)changeHDImageSizeLabelStatus;
-(void)initToolBar;
-(void)onSelectPhoto:(id)arg1;
-(void)addNvGestureRecognizer;
-(void)removeNvGestureRecognizer;
-(void)onSingleTapOnNavigationBar:(id)arg1;
-(void)stopImageLoading;
-(void)startImageLoading;
-(void)doSelectPhoto;
-(id)genDataLength:(unsigned long)arg1;
-(id)getImageData;
-(BOOL)isLongImage;
-(BOOL)isShowHDImageAlert;
-(void)doCancel;
-(void)adjustImageViewRect;
-(void)onOperate;
-(void)setM_singleTapOnNav:(id)arg1;
-(void)onSingleTapImageBrowseView;
-(void)showToolBar;
-(void)hideToolBar;
-(void)OnSendHD;
-(id)initWithImage:(id)arg1 Data:(id)arg2;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)setFullScreen:(BOOL)arg1;
-(void)exitFullScreen;
-(void)dealloc;
@end