/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:37 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PLCrashReportSystemInfo : NSObject {
	int _operatingSystem; 
	NSString* _osVersion; 
	int _architecture; 
	NSDate* _timestamp; 
}
@property (nonatomic,copy) NSDate* timestamp; 				//@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,copy) int architecture; 				//@synthesize architecture=_architecture - In the implementation block
@property (nonatomic,copy) NSString* operatingSystemVersion; 				//@synthesize osVersion=_osVersion - In the implementation block
@property (nonatomic,copy) int operatingSystem; 				//@synthesize operatingSystem=_operatingSystem - In the implementation block
-(id)initWithOperatingSystem:(int)arg1 operatingSystemVersion:(id)arg2 architecture:(int)arg3 timestamp:(id)arg4;
-(void)dealloc;
@end