/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:12 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PLCrashReportRegisterInfo : NSObject {
	NSString* _registerName; 
	unsigned long long _registerValue; 
}
@property (nonatomic,copy) unsigned long long registerValue; 				//@synthesize registerValue=_registerValue - In the implementation block
@property (nonatomic,copy) NSString* registerName; 				//@synthesize registerName=_registerName - In the implementation block
-(id)initWithRegisterName:(id)arg1 registerValue:(unsigned long long)arg2;
-(void)dealloc;
@end