/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:45 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PLCrashReportApplicationInfo : NSObject {
	NSString* _applicationIdentifier; 
	NSString* _applicationVersion; 
}
@property (nonatomic,copy) NSString* applicationVersion; 				//@synthesize applicationVersion=_applicationVersion - In the implementation block
@property (nonatomic,copy) NSString* applicationIdentifier; 				//@synthesize applicationIdentifier=_applicationIdentifier - In the implementation block
-(id)initWithApplicationIdentifier:(id)arg1 applicationVersion:(id)arg2;
-(void)dealloc;
@end