/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:53 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PLCrashReporter : NSObject {
	BOOL _enabled; 
	NSString* _applicationIdentifier; 
	NSString* _applicationVersion; 
	NSString* _crashReportDirectory; 
}
+(id)sharedReporter;
+(void)initialize;
-(BOOL)hasPendingCrashReport;
-(BOOL)enableCrashReporterAndReturnError:(id*)arg1;
-(id)loadPendingCrashReportDataAndReturnError:(id*)arg1;
-(BOOL)purgePendingCrashReport;
-(void)setHandleException:(BOOL)arg1;
-(id)queuedCrashReportDirectory;
-(id)crashReportDirectory;
-(id)initWithApplicationIdentifier:(id)arg1 appVersion:(id)arg2;
-(BOOL)populateCrashReportDirectoryAndReturnError:(id*)arg1;
-(BOOL)purgePendingCrashReportAndReturnError:(id*)arg1;
-(id)crashReportPath;
-(BOOL)enableCrashReporter;
-(id)loadPendingCrashReportData;
-(id)initWithBundle:(id)arg1;
-(void)dealloc;
@end