/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:07 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PLCrashReportExceptionInfo : NSObject {
	NSString* _name; 
	NSString* _reason; 
}
@property (nonatomic,copy) NSString* exceptionReason; 				//@synthesize reason=_reason - In the implementation block
@property (nonatomic,copy) NSString* exceptionName; 				//@synthesize name=_name - In the implementation block
-(id)initWithExceptionName:(id)arg1 reason:(id)arg2;
-(void)dealloc;
@end