/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:47 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PLCrashReport : NSObject {
	struct _PLCrashReportDecoder* _decoder; 
	PLCrashReportSystemInfo* _systemInfo; 
	PLCrashReportApplicationInfo* _applicationInfo; 
	PLCrashReportSignalInfo* _signalInfo; 
	NSArray* _threads; 
	NSArray* _images; 
	PLCrashReportExceptionInfo* _exceptionInfo; 
}
@property (nonatomic,copy) BOOL hasExceptionInfo; 
@property (nonatomic,copy) PLCrashReportExceptionInfo* exceptionInfo; 				//@synthesize exceptionInfo=_exceptionInfo - In the implementation block
@property (nonatomic,copy) NSArray* images; 				//@synthesize images=_images - In the implementation block
@property (nonatomic,copy) NSArray* threads; 				//@synthesize threads=_threads - In the implementation block
@property (nonatomic,copy) PLCrashReportSignalInfo* signalInfo; 				//@synthesize signalInfo=_signalInfo - In the implementation block
@property (nonatomic,copy) PLCrashReportApplicationInfo* applicationInfo; 				//@synthesize applicationInfo=_applicationInfo - In the implementation block
@property (nonatomic,copy) PLCrashReportSystemInfo* systemInfo; 				//@synthesize systemInfo=_systemInfo - In the implementation block
-(id)extractExceptionInfo:(struct _Plcrash__CrashReport__Exception*)arg1 error:(id*)arg2;
-(id)extractImageInfo:(struct _Plcrash__CrashReport*)arg1 error:(id*)arg2;
-(id)extractThreadInfo:(struct _Plcrash__CrashReport*)arg1 error:(id*)arg2;
-(id)extractSignalInfo:(struct _Plcrash__CrashReport__Signal*)arg1 error:(id*)arg2;
-(id)extractApplicationInfo:(struct _Plcrash__CrashReport__ApplicationInfo*)arg1 error:(id*)arg2;
-(id)extractSystemInfo:(struct _Plcrash__CrashReport__SystemInfo*)arg1 error:(id*)arg2;
-(struct _Plcrash__CrashReport*)decodeCrashData:(id)arg1 error:(id*)arg2;
-(id)imageForAddress:(unsigned long long)arg1;
-(id)initWithData:(id)arg1 error:(id*)arg2;
-(void)dealloc;
@end