/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:27 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PLCrashSignalHandler : NSObject {
	struct __darwin_sigaltstack _sigstk; 
}
+(id)sharedHandler;
+(void)initialize;
-(BOOL)registerHandlerWithCallback:(?*)arg1 context:(void*)arg2 error:(id*)arg3;
-(void)populateError:(id*)arg1 errorCode:(int)arg2 description:(id)arg3 cause:(id)arg4;
-(BOOL)registerHandlerForSignal:(int)arg1 error:(id*)arg2;
-(void)populateError:(id*)arg1 errnoVal:(int)arg2 description:(id)arg3;
-(id)init;
@end