/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:57 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PLCrashReportBinaryImageInfo : NSObject {
	unsigned long long _baseAddress; 
	unsigned long long _imageSize; 
	NSString* _imageName; 
	BOOL _hasImageUUID; 
	NSString* _imageUUID; 
}
@property (nonatomic,copy) NSString* imageUUID; 				//@synthesize imageUUID=_imageUUID - In the implementation block
@property (nonatomic,copy) BOOL hasImageUUID; 				//@synthesize hasImageUUID=_hasImageUUID - In the implementation block
@property (nonatomic,copy) NSString* imageName; 				//@synthesize imageName=_imageName - In the implementation block
@property (nonatomic,copy) unsigned long long imageSize; 				//@synthesize imageSize=_imageSize - In the implementation block
@property (nonatomic,copy) unsigned long long imageBaseAddress; 				//@synthesize baseAddress=_baseAddress - In the implementation block
-(id)initWithImageBaseAddress:(unsigned long long)arg1 imageSize:(unsigned long long)arg2 imageName:(id)arg3 imageUUID:(id)arg4;
-(void)dealloc;
@end