/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:14 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PLCrashReportThreadInfo : NSObject {
	int _threadNumber; 
	NSArray* _stackFrames; 
	BOOL _crashed; 
	NSArray* _registers; 
}
@property (nonatomic,copy) NSArray* registers; 				//@synthesize registers=_registers - In the implementation block
@property (nonatomic,copy) BOOL crashed; 				//@synthesize crashed=_crashed - In the implementation block
@property (nonatomic,copy) NSArray* stackFrames; 				//@synthesize stackFrames=_stackFrames - In the implementation block
@property (nonatomic,copy) int threadNumber; 				//@synthesize threadNumber=_threadNumber - In the implementation block
-(id)initWithThreadNumber:(int)arg1 stackFrames:(id)arg2 crashed:(BOOL)arg3 registers:(id)arg4;
-(void)dealloc;
@end