/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:04 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PLCrashReportStackFrameInfo : NSObject {
	unsigned long long _instructionPointer; 
}
@property (nonatomic,copy) unsigned long long instructionPointer; 				//@synthesize instructionPointer=_instructionPointer - In the implementation block
-(id)initWithInstructionPointer:(unsigned long long)arg1;
@end