/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:45 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PLCrashReportSignalInfo : NSObject {
	NSString* _name; 
	NSString* _code; 
	unsigned long long _address; 
}
@property (nonatomic,copy) unsigned long long address; 				//@synthesize address=_address - In the implementation block
@property (nonatomic,copy) NSString* code; 				//@synthesize code=_code - In the implementation block
@property (nonatomic,copy) NSString* name; 				//@synthesize name=_name - In the implementation block
-(id)initWithSignalName:(id)arg1 code:(id)arg2 address:(unsigned long long)arg3;
-(void)dealloc;
@end