/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:43 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PluginKey : PBGeneratedMessage {
	unsigned int hasKey:1; 
	unsigned int hasId:1; 
	NSString* key; 
	unsigned id; 
}
@property (assign) unsigned id; 
@property (assign) BOOL hasId; 
@property (retain) NSString* key; 
@property (assign) BOOL hasKey; 
+(id)parseFromData:(id)arg1;
-(id)SetKey:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasId:(BOOL)arg1;
-(void)setHasKey:(BOOL)arg1;
-(id)SetId:(unsigned)arg1;
-(void)setKey:(id)arg1;
-(void)setId:(unsigned)arg1;
-(id)init;
-(void)dealloc;
@end