/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:12 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PluginUtil : NSObject {
}
+(id)getOfficialLocalizedNickName:(id)arg1;
+(_Bool)isOfficialContact:(id)arg1;
+(id)getPluginLocalizedNickName:(int)arg1;
+(int)getPluginContactType:(id)arg1;
+(_Bool)isPluginContact:(id)arg1;
+(_Bool)isPluginInstalled:(int)arg1;
+(id)getPluginUserName:(int)arg1;
+(id)getPluginContact:(int)arg1;
+(int)getPluginUserNameType:(id)arg1;
+(_Bool)isPluginOpened:(int)arg1;
+(_Bool)isPluginUserName:(id)arg1;
+(BOOL)isPluginShow:(int)arg1;
+(void)genericFunctionSwitch:(unsigned long)arg1 statusBit:(unsigned long)arg2 setOpen:(BOOL)arg3;
+(void)newGenericFunctionSwitch:(unsigned long)arg1 statusBit:(unsigned long)arg2 setOpen:(BOOL)arg3;
+(_Bool)isOfficialExpectWeixinContact:(id)arg1;
+(void)unInstallPlugin:(int)arg1;
+(void)closePlugin:(int)arg1;
+(void)clearPluginData:(int)arg1;
+(void)installPlugin:(int)arg1;
+(void)openPlugin:(int)arg1;
+(unsigned long)clearLBSPluginData;
+(unsigned long)closePushMailPlugin;
+(unsigned long)openPushMailPlugin:(id)arg1;
+(void)switchSXPlugin:(BOOL)arg1;
+(unsigned long)opPushMailPlugin:(unsigned long)arg1 pwd:(id)arg2;
+(_Bool)isOfficialExpectWeixinUserNmae:(id)arg1;
+(_Bool)isOfficialUserName:(id)arg1;
+(unsigned long)pluginTypeToUnInstallBit:(int)arg1;
+(unsigned long)getAlbumPrivacyOption;
+(void)setAlbumPrivacyOption:(unsigned long)arg1;
@end