/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:54 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol PopupTextEditViewControllerDelegate
@required
-(void)onEditCancelWithTextEdit(id):arg1 ;
-(void)onEditOk(id):arg1 WithTextEdit(id):arg2 ;
-(void)onEditCancelWithTextEdit(id):arg1 ;
-(void)onEditOk(id):arg1 WithTextEdit(id):arg2 ;
@end
