/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:01 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PushCard : NSObject {
	NSString* m_nsTitle; 
	NSString* m_nsBoldTitle; 
	CContact* m_oContact; 
	NSString* m_nsDescTitle; 
	NSString* m_nsThirdTitle; 
	UIImage* m_oBackgroundImg; 
	UIImage* m_oBackgroundImgHL; 
	UIImage* m_oSmallIcon; 
}
@property (nonatomic,retain) NSString* m_nsThirdTitle; 
@property (nonatomic,retain) NSString* m_nsDescTitle; 
@property (nonatomic,retain) NSString* m_nsBoldTitle; 
@property (nonatomic,retain) CContact* m_oContact; 
@property (nonatomic,retain) NSString* m_nsTitle; 
@property (nonatomic,retain) UIImage* m_oSmallIcon; 
@property (nonatomic,retain) UIImage* m_oBackgroundImgHL; 
@property (nonatomic,retain) UIImage* m_oBackgroundImg; 
-(void)setM_nsTitle:(id)arg1;
-(id)initWithMessageWrap:(id)arg1;
-(id)getFilterString:(id)arg1;
-(void)setM_nsThirdTitle:(id)arg1;
-(void)setM_nsDescTitle:(id)arg1;
-(void)setM_nsBoldTitle:(id)arg1;
-(void)setM_oContact:(id)arg1;
-(void)setM_oSmallIcon:(id)arg1;
-(void)setM_oBackgroundImgHL:(id)arg1;
-(void)setM_oBackgroundImg:(id)arg1;
-(void)parseXMLFromMessage:(id)arg1;
-(void)dealloc;
@end