/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:34 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface QQBlogContactInfoViewController : MMUIViewController {
	CContact* _contact; 
	MMHeadImageView* _headView; 
	MMHDHeadImageView* _HDHeadView; 
	UILabel* _userNameLabel; 
	UILabel* _nickNameLabel; 
	UIButton* _sendMsgBtn; 
	id<contactInfoDelegate> _delegate; 
}
@property (assign,nonatomic) id<contactInfoDelegate> _delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) CContact* _contact; 				//@synthesize contact=_contact - In the implementation block
-(void)initView;
-(id)initWithContact:(id)arg1;
-(void)set_delegate:(id)arg1;
-(void)initHDHeadImage;
-(void)initUserNameLabel;
-(void)initNickNameLabel;
-(void)initHeadImage;
-(void)onNewMessage:(id)arg1;
-(void)updateNickNameLabel;
-(void)jumpToContentViewController:(id)arg1;
-(void)set_contact:(id)arg1;
-(void)initSendMsgBtn;
-(void)viewDidLoad;
-(id)init;
-(void)dealloc;
@end