/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:29 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IQQMailExt.h>

@interface QQMailLogSender : NSObject <IQQMailExt> {
	UIWindow* _window; 
}
+(id)sharedInstance;
-(id)getSelfMailContact;
-(void)OnViewImage:(id)arg1 ErrNo:(int)arg2;
-(void)OnViewCompress:(id)arg1 ErrNo:(int)arg2;
-(void)OnComposeSend:(int)arg1;
-(void)OnUploadData:(id)arg1 filename:(id)arg2 ErrNo:(int)arg3;
-(void)OnSetMailUnread:(int)arg1;
-(void)OnGetMail:(id)arg1 ErrNo:(int)arg2;
-(void)OnGetAllMailContact:(id)arg1 ErrNo:(int)arg2;
-(void)onSuccess;
-(void)onError;
-(void)killQQMailLogSender;
-(void)startSendLog;
-(void)dealloc;
@end