/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:19 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface QQRecentContactView : UIView {
	UILabel* m_displayNameLabel; 
	UILabel* m_lastMessageLabel; 
	UILabel* m_timeLabel; 
	UILabel* m_labelCount; 
	UIImageView* m_unreadCountView; 
	UIImageView* m_statusImageView; 
	MMHeadImageView* m_contactHeadImage; 
	QQSessionInfo* m_sessionInfo; 
}
@property (nonatomic,retain) QQSessionInfo* m_sessionInfo; 
@property (nonatomic,retain) UIImageView* m_unreadCountView; 
@property (nonatomic,retain) UILabel* m_timeLabel; 
@property (nonatomic,retain) UILabel* m_lastMessageLabel; 
@property (nonatomic,retain) MMHeadImageView* m_contactHeadImage; 
@property (nonatomic,retain) UILabel* m_displayNameLabel; 
-(void)initView;
-(void)initDisplayNameLabel;
-(void)initLastMessageLabel;
-(void)initTimeLabel;
-(void)initImage;
-(void)updateLastMessageLabel;
-(void)setM_displayNameLabel:(id)arg1;
-(void)setM_contactHeadImage:(id)arg1;
-(void)setM_lastMessageLabel:(id)arg1;
-(void)setM_timeLabel:(id)arg1;
-(void)setM_unreadCountView:(id)arg1;
-(void)setM_sessionInfo:(id)arg1;
-(void)initUnreadCountView;
-(void)updateUnreadCountView;
-(void)updateHeadImage;
-(void)updateTimeLabel;
-(void)updateDisplayNameLabel;
-(void)hideLabels:(BOOL)arg1;
-(void)dealloc;
@end