/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:38:57 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IMMQRCodeExt.h>
#import <UIActionSheetDelegate.h>

@interface QRCodeViewController : MMUIViewController <IMMQRCodeExt, UIActionSheetDelegate> {
	UIActivityIndicatorView* m_loadingView; 
	UIImageView* m_imageQRView; 
	MMHeadImageView* m_imageHeadView; 
	UILabel* m_labelNickName; 
	UILabel* m_labelUsrName; 
	UILabel* m_labelLacation; 
	UIImageView* m_sexImageView; 
	struct stWeixinEntryRow* m_aryEntryRow; 
	unsigned m_arrEntryRowSize; 
	unsigned m_curOperateType; 
	CContact* m_contact; 
	UIImageView* cardBkg; 
	UIImageView* bkgUp; 
	UIImageView* bkgDown; 
	MMAnimationTipView* m_tipView; 
}
-(void)initView;
-(id)initWithContact:(id)arg1;
-(void)willAppear;
-(void)initRow;
-(void)saveToAlbum;
-(void)getNextQRCode;
-(void)Operate;
-(void)onDownloadQRCodeFinish:(id)arg1;
-(void)adjustSubviewRects;
-(void)shareChatRoomQRCode;
-(void)shareQRCode;
-(void)updateLocation;
-(void)updateUserName;
-(void)updateNickName;
-(void)startLoading;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)viewDidLoad;
-(void)stopLoading;
-(void)dealloc;
@end