/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:42 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface QueryHasPswdRequest : PBGeneratedMessage {
	unsigned int hasScene:1; 
	unsigned int hasBaseRequest:1; 
	int scene; 
	BaseRequest* baseRequest; 
}
@property (assign) int scene; 
@property (assign) BOOL hasScene; 
@property (retain) BaseRequest* baseRequest; 
@property (assign) BOOL hasBaseRequest; 
+(id)parseFromData:(id)arg1;
-(id)SetScene:(int)arg1;
-(id)SetBaseRequest:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasBaseRequest:(BOOL)arg1;
-(void)setBaseRequest:(id)arg1;
-(void)setHasScene:(BOOL)arg1;
-(void)setScene:(int)arg1;
-(id)init;
-(void)dealloc;
@end