/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:17 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface RSACert : PBGeneratedMessage {
	unsigned int hasKeyN:1; 
	unsigned int hasKeyE:1; 
	NSString* keyN; 
	NSString* keyE; 
}
@property (retain) NSString* keyE; 
@property (assign) BOOL hasKeyE; 
@property (retain) NSString* keyN; 
@property (assign) BOOL hasKeyN; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasKeyE:(BOOL)arg1;
-(void)setHasKeyN:(BOOL)arg1;
-(id)SetKeyE:(id)arg1;
-(id)SetKeyN:(id)arg1;
-(void)setKeyE:(id)arg1;
-(void)setKeyN:(id)arg1;
-(id)init;
-(void)dealloc;
@end