/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:31 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SafeDevice : PBGeneratedMessage {
	unsigned int hasName:1; 
	unsigned int hasUuid:1; 
	unsigned int hasDeviceType:1; 
	unsigned int hasCreateTime:1; 
	NSString* name; 
	NSString* uuid; 
	NSString* deviceType; 
	unsigned createTime; 
}
@property (assign) unsigned createTime; 
@property (assign) BOOL hasCreateTime; 
@property (retain) NSString* deviceType; 
@property (assign) BOOL hasDeviceType; 
@property (retain) NSString* uuid; 
@property (assign) BOOL hasUuid; 
@property (retain) NSString* name; 
@property (assign) BOOL hasName; 
+(id)parseFromData:(id)arg1;
-(id)SetDeviceType:(id)arg1;
-(int)serializedSize;
-(void)setCreateTime:(unsigned)arg1;
-(void)setDeviceType:(id)arg1;
-(void)setHasCreateTime:(BOOL)arg1;
-(id)SetCreateTime:(unsigned)arg1;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasUuid:(BOOL)arg1;
-(id)SetUuid:(id)arg1;
-(void)setHasName:(BOOL)arg1;
-(void)setHasDeviceType:(BOOL)arg1;
-(id)SetName:(id)arg1;
-(void)setUuid:(id)arg1;
-(id)init;
-(void)dealloc;
-(void)setName:(id)arg1;
@end