/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:35 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SBJsonWriter.h>

@interface SBJsonWriter : SBJsonBase <SBJsonWriter> {
	BOOL sortKeys; 
	BOOL humanReadable; 
}
@property (assign) BOOL humanReadable; 
@property (assign) BOOL sortKeys; 
+(void)initialize;
-(id)stringWithObject:(id)arg1;
-(id)stringWithFragment:(id)arg1;
-(void)setSortKeys:(BOOL)arg1;
-(void)setHumanReadable:(BOOL)arg1;
-(BOOL)appendString:(id)arg1 into:(id)arg2;
-(BOOL)appendArray:(id)arg1 into:(id)arg2;
-(BOOL)appendDictionary:(id)arg1 into:(id)arg2;
-(BOOL)appendValue:(id)arg1 into:(id)arg2;
-(id)indent;
@end