/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:21 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SBJsonParser.h>

@interface SBJsonParser : SBJsonBase <SBJsonParser> {
	char* c; 
}
+(void)initialize;
-(id)objectWithString:(id)arg1;
-(id)fragmentWithString:(id)arg1;
-(BOOL)scanHexQuad:(unsigned short*)arg1;
-(BOOL)scanUnicodeChar:(unsigned short*)arg1;
-(BOOL)scanNumber:(id*)arg1;
-(BOOL)scanRestOfNull:(id*)arg1;
-(BOOL)scanRestOfTrue:(id*)arg1;
-(BOOL)scanRestOfFalse:(id*)arg1;
-(BOOL)scanRestOfString:(id*)arg1;
-(BOOL)scanRestOfArray:(id*)arg1;
-(BOOL)scanRestOfDictionary:(id*)arg1;
-(BOOL)scanIsAtEnd;
-(BOOL)scanValue:(id*)arg1;
@end