/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:04 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SBJsonBase : NSObject {
	NSMutableArray* errorTrace; 
	unsigned depth; 
	unsigned maxDepth; 
}
@property (assign) unsigned maxDepth; 
@property (copy,copy) NSArray* errorTrace; 
-(void)setMaxDepth:(unsigned)arg1;
-(void)clearErrorTrace;
-(void)addErrorWithCode:(unsigned)arg1 description:(id)arg2;
-(id)init;
-(void)dealloc;
@end