/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:13 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SBJsonParser.h>
#import <SBJsonWriter.h>

@interface SBJSON : SBJsonBase <SBJsonParser, SBJsonWriter> {
	SBJsonParser* jsonParser; 
	SBJsonWriter* jsonWriter; 
}
@property (assign) BOOL sortKeys; 
@property (assign) BOOL humanReadable; 
-(id)objectWithString:(id)arg1;
-(id)stringWithObject:(id)arg1;
-(void)setSortKeys:(BOOL)arg1;
-(void)setHumanReadable:(BOOL)arg1;
-(id)objectWithString:(id)arg1 allowScalar:(BOOL)arg2 error:(id*)arg3;
-(id)stringWithObject:(id)arg1 allowScalar:(BOOL)arg2 error:(id*)arg3;
-(void)setMaxDepth:(unsigned)arg1;
-(id)objectWithString:(id)arg1 error:(id*)arg2;
-(id)fragmentWithString:(id)arg1 error:(id*)arg2;
-(id)stringWithObject:(id)arg1 error:(id*)arg2;
-(id)stringWithFragment:(id)arg1 error:(id*)arg2;
-(id)init;
-(void)dealloc;
-(unsigned)maxDepth;
@end