/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:39 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SearchContactRequest : PBGeneratedMessage {
	unsigned int hasBaseRequest:1; 
	unsigned int hasUserName:1; 
	BaseRequest* baseRequest; 
	SKBuiltinString_t* userName; 
}
@property (retain) SKBuiltinString_t* userName; 
@property (assign) BOOL hasUserName; 
@property (retain) BaseRequest* baseRequest; 
@property (assign) BOOL hasBaseRequest; 
+(id)parseFromData:(id)arg1;
-(id)SetUserName:(id)arg1;
-(id)SetBaseRequest:(id)arg1;
-(int)serializedSize;
-(void)setHasUserName:(BOOL)arg1;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasBaseRequest:(BOOL)arg1;
-(void)setBaseRequest:(id)arg1;
-(void)setUserName:(id)arg1;
-(id)init;
-(void)dealloc;
@end