/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:19 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SendAppMsgResponse : PBGeneratedMessage {
	unsigned int hasAppId:1; 
	unsigned int hasFromUserName:1; 
	unsigned int hasToUserName:1; 
	unsigned int hasClientMsgId:1; 
	unsigned int hasBaseResponse:1; 
	unsigned int hasMsgId:1; 
	unsigned int hasCreateTime:1; 
	unsigned int hasType:1; 
	NSString* appId; 
	NSString* fromUserName; 
	NSString* toUserName; 
	NSString* clientMsgId; 
	BaseResponse* baseResponse; 
	unsigned msgId; 
	unsigned createTime; 
	unsigned type; 
}
@property (assign) unsigned type; 
@property (assign) BOOL hasType; 
@property (assign) unsigned createTime; 
@property (assign) BOOL hasCreateTime; 
@property (retain) NSString* clientMsgId; 
@property (assign) BOOL hasClientMsgId; 
@property (assign) unsigned msgId; 
@property (assign) BOOL hasMsgId; 
@property (retain) NSString* toUserName; 
@property (assign) BOOL hasToUserName; 
@property (retain) NSString* fromUserName; 
@property (assign) BOOL hasFromUserName; 
@property (retain) NSString* appId; 
@property (assign) BOOL hasAppId; 
@property (retain) BaseResponse* baseResponse; 
@property (assign) BOOL hasBaseResponse; 
+(id)parseFromData:(id)arg1;
-(id)SetType:(unsigned)arg1;
-(id)SetAppId:(id)arg1;
-(id)SetToUserName:(id)arg1;
-(int)serializedSize;
-(void)setCreateTime:(unsigned)arg1;
-(void)setHasCreateTime:(BOOL)arg1;
-(id)SetCreateTime:(unsigned)arg1;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasAppId:(BOOL)arg1;
-(void)setHasClientMsgId:(BOOL)arg1;
-(id)SetClientMsgId:(id)arg1;
-(void)setClientMsgId:(id)arg1;
-(void)setHasBaseResponse:(BOOL)arg1;
-(id)SetBaseResponse:(id)arg1;
-(void)setBaseResponse:(id)arg1;
-(void)setHasToUserName:(BOOL)arg1;
-(void)setHasFromUserName:(BOOL)arg1;
-(void)setHasMsgId:(BOOL)arg1;
-(id)SetFromUserName:(id)arg1;
-(id)SetMsgId:(unsigned)arg1;
-(void)setMsgId:(unsigned)arg1;
-(void)setToUserName:(id)arg1;
-(void)setFromUserName:(id)arg1;
-(void)setType:(unsigned)arg1;
-(void)setHasType:(BOOL)arg1;
-(void)setAppId:(id)arg1;
-(id)init;
-(void)dealloc;
@end