/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:30 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SendAppMsgRequest : PBGeneratedMessage {
	unsigned int hasCommentUrl:1; 
	unsigned int hasBaseRequest:1; 
	unsigned int hasMsg:1; 
	NSString* commentUrl; 
	BaseRequest* baseRequest; 
	AppMsg* msg; 
}
@property (retain) NSString* commentUrl; 
@property (assign) BOOL hasCommentUrl; 
@property (retain) AppMsg* msg; 
@property (assign) BOOL hasMsg; 
@property (retain) BaseRequest* baseRequest; 
@property (assign) BOOL hasBaseRequest; 
+(id)parseFromData:(id)arg1;
-(id)SetBaseRequest:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasCommentUrl:(BOOL)arg1;
-(void)setHasMsg:(BOOL)arg1;
-(id)SetCommentUrl:(id)arg1;
-(id)SetMsg:(id)arg1;
-(void)setCommentUrl:(id)arg1;
-(void)setMsg:(id)arg1;
-(void)setHasBaseRequest:(BOOL)arg1;
-(void)setBaseRequest:(id)arg1;
-(id)init;
-(void)dealloc;
@end