/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:22 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SetPushSoundReq : PBGeneratedMessage {
	unsigned int hasSound:1; 
	unsigned int hasBaseRequest:1; 
	unsigned int hasType:1; 
	NSString* sound; 
	BaseRequest* baseRequest; 
	unsigned type; 
}
@property (retain) NSString* sound; 
@property (assign) BOOL hasSound; 
@property (assign) unsigned type; 
@property (assign) BOOL hasType; 
@property (retain) BaseRequest* baseRequest; 
@property (assign) BOOL hasBaseRequest; 
+(id)parseFromData:(id)arg1;
-(id)SetType:(unsigned)arg1;
-(id)SetSound:(id)arg1;
-(id)SetBaseRequest:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasSound:(BOOL)arg1;
-(void)setHasBaseRequest:(BOOL)arg1;
-(void)setBaseRequest:(id)arg1;
-(void)setType:(unsigned)arg1;
-(void)setSound:(id)arg1;
-(void)setHasType:(BOOL)arg1;
-(id)init;
-(void)dealloc;
@end