/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:35 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SetPwdRequest : PBGeneratedMessage {
	unsigned int hasPassword:1; 
	unsigned int hasTicket:1; 
	unsigned int hasBaseRequest:1; 
	NSString* password; 
	NSString* ticket; 
	BaseRequest* baseRequest; 
}
@property (retain) NSString* ticket; 
@property (assign) BOOL hasTicket; 
@property (retain) NSString* password; 
@property (assign) BOOL hasPassword; 
@property (retain) BaseRequest* baseRequest; 
@property (assign) BOOL hasBaseRequest; 
+(id)parseFromData:(id)arg1;
-(id)SetTicket:(id)arg1;
-(id)SetPassword:(id)arg1;
-(id)SetBaseRequest:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasTicket:(BOOL)arg1;
-(void)setHasBaseRequest:(BOOL)arg1;
-(void)setBaseRequest:(id)arg1;
-(void)setPassword:(id)arg1;
-(void)setTicket:(id)arg1;
-(id)init;
-(void)dealloc;
-(void)setHasPassword:(BOOL)arg1;
@end