/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:24 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIActionSheetDelegate.h>
#import <MMCameraDelegate.h>
#import <MessageObserverDelegate.h>

@interface SettingMyAccountExtInfoLogic : NSObject <UIActionSheetDelegate, MMCameraDelegate, MessageObserverDelegate> {
	id<settingMyAccountExtInfoLogicDelegate> m_delegate; 
	UIViewController* m_viewController; 
	MMCamera* m_camera; 
	CUsrInfo* m_usrInfo; 
	unsigned m_uiUploadHeadEventID; 
}
@property (nonatomic,retain) CUsrInfo* m_usrInfo; 
-(id)getViewController;
-(void)MessageReturn:(unsigned long)arg1 MessageInfo:(id)arg2 Event:(unsigned long)arg3;
-(void)showChangeImg;
-(void)showCamera:(int)arg1;
-(void)handleImage:(id)arg1;
-(void)mmCameraDidCancel;
-(void)mmCameraDidTakePicture:(id)arg1;
-(id)getNavigationController;
-(id)initWithViewController:(id)arg1 delegate:(id)arg2;
-(void)resetViewControllerAndDelegate;
-(void)setM_usrInfo:(id)arg1;
-(void)saveInfo;
-(void)reload;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)dealloc;
@end