/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:38:50 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MailReceiverEditViewDelegate.h>
#import <PBMessageObserverDelegate.h>
#import <MailContactFilterViewDelegate.h>
#import <MMMailContactSelectViewDelegate.h>
#import <UIAlertViewDelegate.h>

@interface ShareQRCodeByEmailViewController : MMUIViewController <MailReceiverEditViewDelegate, PBMessageObserverDelegate, MailContactFilterViewDelegate, MMMailContactSelectViewDelegate, UIAlertViewDelegate> {
	MailReceiverEditView* m_receiverView; 
	MailSubjectEditView* m_topicView; 
	UIButton* m_contentView; 
	MailContactFilterView* m_filterView; 
	NSMutableArray* m_arrAllMailContacts; 
	CContact* m_contact; 
	MMTableViewInfo* m_tableViewInfo; 
}
@property (nonatomic,retain) CContact* m_contact; 
-(void)initView;
-(void)setM_contact:(id)arg1;
-(void)doSearch:(id)arg1;
-(void)initData;
-(void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
-(void)reloadTableData;
-(void)onTextFieldChanged:(id)arg1;
-(void)onBack;
-(void)initNotificationObservers;
-(void)removeNotificationObservers;
-(void)contactReturn:(id)arg1;
-(void)filterViewBeginDragging;
-(void)onMailContactSelectDone:(id)arg1 userInfo:(id)arg2;
-(void)onMailContactChanged:(id)arg1;
-(void)onTextFieldNextItem:(id)arg1;
-(void)onTextFieldBeginEdit:(id)arg1;
-(void)onTextFieldFinishEdit:(id)arg1;
-(void)onMailReceiverEditViewHeightChanged:(id)arg1;
-(void)onAddMailContact:(id)arg1;
-(void)onMailContactDoubleClicked:(id)arg1;
-(void)initContentView;
-(void)onReturn;
-(void)hideKeyBoard;
-(void)onShare;
-(void)onSelectCell:(id)arg1;
-(void)makeCell:(id)arg1 :(id)arg2;
-(void)keyboardWillHide:(id)arg1;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)viewDidLoad;
-(void)keyboardDidShow:(id)arg1;
-(void)dealloc;
@end