/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:25 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SimpleImagePreviewViewController : MMUIViewController {
	UIImage* m_image; 
	UIImageView* m_imageView; 
	id<SimpleImagePreviewViewControllerDelegate> m_delegate; 
}
@property (assign,nonatomic) id<SimpleImagePreviewViewControllerDelegate> m_delegate; 
@property (nonatomic,retain) UIImage* m_image; 
-(void)setM_delegate:(id)arg1;
-(void)showStatusBar;
-(void)willAppear;
-(void)hideStatusBar;
-(void)willDisapper;
-(void)onSingleTap:(id)arg1;
-(void)setM_image:(id)arg1;
-(void)doCancel;
-(void)doSelect;
-(void)viewDidLoad;
-(void)dealloc;
@end