/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:32 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SKBuiltinBuffer_t : PBGeneratedMessage {
	unsigned int hasBuffer:1; 
	unsigned int hasILen:1; 
	NSData* buffer; 
	unsigned iLen; 
}
@property (retain) NSData* buffer; 
@property (assign) BOOL hasBuffer; 
@property (assign) unsigned iLen; 
@property (assign) BOOL hasILen; 
+(id)parseFromData:(id)arg1;
-(id)SetILen:(unsigned)arg1;
-(id)SetBuffer:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasBuffer:(BOOL)arg1;
-(void)setHasILen:(BOOL)arg1;
-(void)setILen:(unsigned)arg1;
-(void)setBuffer:(id)arg1;
-(id)init;
-(void)dealloc;
@end