/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:07 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SnsSyncRequest : PBGeneratedMessage {
	unsigned int hasBaseRequest:1; 
	unsigned int hasKeyBuf:1; 
	unsigned int hasSelector:1; 
	BaseRequest* baseRequest; 
	SKBuiltinBuffer_t* keyBuf; 
	unsigned selector; 
}
@property (retain) SKBuiltinBuffer_t* keyBuf; 
@property (assign) BOOL hasKeyBuf; 
@property (assign) unsigned selector; 
@property (assign) BOOL hasSelector; 
@property (retain) BaseRequest* baseRequest; 
@property (assign) BOOL hasBaseRequest; 
+(id)parseFromData:(id)arg1;
-(id)SetSelector:(unsigned)arg1;
-(id)SetBaseRequest:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasBaseRequest:(BOOL)arg1;
-(void)setBaseRequest:(id)arg1;
-(void)setHasKeyBuf:(BOOL)arg1;
-(void)setHasSelector:(BOOL)arg1;
-(id)SetKeyBuf:(id)arg1;
-(void)setKeyBuf:(id)arg1;
-(void)setSelector:(unsigned)arg1;
-(id)init;
-(void)dealloc;
@end