/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:39 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SnsUserInfo : PBGeneratedMessage {
	unsigned int hasSnsBgobjectId:1; 
	unsigned int hasSnsBgimgId:1; 
	unsigned int hasSnsFlag:1; 
	unsigned int hasSnsFlagEx:1; 
	unsigned long long snsBgobjectId; 
	NSString* snsBgimgId; 
	unsigned snsFlag; 
	unsigned snsFlagEx; 
}
@property (assign) unsigned snsFlagEx; 
@property (assign) BOOL hasSnsFlagEx; 
@property (assign) unsigned long long snsBgobjectId; 
@property (assign) BOOL hasSnsBgobjectId; 
@property (retain) NSString* snsBgimgId; 
@property (assign) BOOL hasSnsBgimgId; 
@property (assign) unsigned snsFlag; 
@property (assign) BOOL hasSnsFlag; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasSnsFlagEx:(BOOL)arg1;
-(void)setHasSnsBgobjectId:(BOOL)arg1;
-(void)setHasSnsBgimgId:(BOOL)arg1;
-(void)setHasSnsFlag:(BOOL)arg1;
-(id)SetSnsFlagEx:(unsigned)arg1;
-(id)SetSnsBgobjectId:(unsigned long long)arg1;
-(id)SetSnsBgimgId:(id)arg1;
-(id)SetSnsFlag:(unsigned)arg1;
-(void)setSnsFlagEx:(unsigned)arg1;
-(void)setSnsBgobjectId:(unsigned long long)arg1;
-(void)setSnsFlag:(unsigned)arg1;
-(void)setSnsBgimgId:(id)arg1;
-(id)init;
-(void)dealloc;
@end