/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:58 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PBMessageObserverDelegate.h>

@interface SubUserLogicController : NSObject <PBMessageObserverDelegate> {
	id<SubUserUIDelegate> delegate; 
}
-(void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
-(BOOL)createSubUserEvent:(id)arg1;
-(BOOL)unbindSubUserEvent:(id)arg1;
-(BOOL)getSubUserListEvent;
-(BOOL)updateSubUserEvent:(id)arg1 andAttrItem:(id)arg2;
-(id)init;
-(void)dealloc;
-(id)initWithDelegate:(id)arg1;
@end