/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:23 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SyncPhoneContactsAssist : CBaseContactInfoAssist {
}
-(void)initHeaderView;
-(void)reloadTableView;
-(void)makeCell:(id)arg1 row:(unsigned)arg2 section:(unsigned long)arg3;
-(void)onSwitchChange:(id)arg1;
-(void)onShowAgreement;
-(void)onShowUserInstruction;
-(void)onEnter;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
-(void)dealloc;
@end