/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:50 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol tableViewDelegate
@optional
-(void)didFinishedLoading(id):arg1 ;
-(void)touchesCancelled_TableView(id):arg1 withEvent(id):arg2 ;
-(void)touchesEnded_TableView(id):arg1 withEvent(id):arg2 ;
-(void)touchesMoved_TableView(id):arg1 withEvent(id):arg2 ;
-(void)touchesBegan_TableView(id):arg1 withEvent(id):arg2 ;
@end
