/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:03 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIAlertViewDelegate
@optional
-(void)alertView(id):arg1 clickedButtonAtIndex(int):arg2 ;
-(void)alertViewCancel(id):arg1 ;
-(void)willPresentAlertView(id):arg1 ;
-(void)didPresentAlertView(id):arg1 ;
-(void)alertView(id):arg1 willDismissWithButtonIndex(int):arg2 ;
-(void)alertView(id):arg1 didDismissWithButtonIndex(int):arg2 ;
-(BOOL)alertViewShouldEnableFirstOtherButton(id):arg1 ;
@end
