/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:35 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIHorizontalTableViewDelegate
@required
-(float)horizontalTableView(id):arg1 widthForColumnAtIndex(unsigned):arg2 ;
-(void)horizontalTableView(id):arg1 didSelectColumnAtIndex(unsigned):arg2 ;
-(float)horizontalTableView(id):arg1 widthForColumnAtIndex(unsigned):arg2 ;
-(void)horizontalTableView(id):arg1 didSelectColumnAtIndex(unsigned):arg2 ;
@end

@protocol UIHorizontalTableViewDataSource
@required
-(id)horizontalTableView(id):arg1 viewForColumnAtIndex(unsigned):arg2 ;
-(unsigned)numberOfColumnsInHorizontalTableView(id):arg1 ;
-(id)horizontalTableView(id):arg1 viewForColumnAtIndex(unsigned):arg2 ;
-(unsigned)numberOfColumnsInHorizontalTableView(id):arg1 ;
@end
