/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:23 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UISearchDisplayDelegate
@optional
-(void)searchDisplayControllerWillBeginSearch(id):arg1 ;
-(void)searchDisplayControllerDidBeginSearch(id):arg1 ;
-(void)searchDisplayControllerWillEndSearch(id):arg1 ;
-(void)searchDisplayControllerDidEndSearch(id):arg1 ;
-(void)searchDisplayController(id):arg1 didLoadSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 willUnloadSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 willShowSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 didShowSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 willHideSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 didHideSearchResultsTableView(id):arg2 ;
-(BOOL)searchDisplayController(id):arg1 shouldReloadTableForSearchString(id):arg2 ;
-(BOOL)searchDisplayController(id):arg1 shouldReloadTableForSearchScope(int):arg2 ;
@end
