/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:26 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UITextViewDelegate
@optional
-(BOOL)textViewShouldBeginEditing(id):arg1 ;
-(BOOL)textViewShouldEndEditing(id):arg1 ;
-(void)textViewDidBeginEditing(id):arg1 ;
-(void)textViewDidEndEditing(id):arg1 ;
-(BOOL)textView(id):arg1 shouldChangeTextInRange({):arg2 replacementText(_):arg3 ;
-(void)textViewDidChange(id):arg1 ;
-(void)textViewDidChangeSelection(id):arg1 ;
@end
