/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:38:57 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface UploadImageInfo : NSObject {
	CMessageWrap* m_wrapMsg; 
	unsigned long long m_ui64StartTime; 
	unsigned m_uiTotalLen; 
	int m_nRetCode; 
}
@property (assign,nonatomic) int m_nRetCode; 
@property (assign,nonatomic) unsigned m_uiTotalLen; 
@property (assign,nonatomic) unsigned long long m_ui64StartTime; 
@property (nonatomic,retain) CMessageWrap* m_wrapMsg; 
-(void)setM_wrapMsg:(id)arg1;
-(void)setM_uiTotalLen:(unsigned long)arg1;
-(void)setM_nRetCode:(int)arg1;
-(id)GetStatInfo;
-(void)setM_ui64StartTime:(unsigned long long)arg1;
-(id)init;
-(void)dealloc;
@end