/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:38:54 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface UserInfoExt : PBGeneratedMessage {
	unsigned int hasMyBrandList:1; 
	unsigned int hasMsgPushSound:1; 
	unsigned int hasVoipPushSound:1; 
	unsigned int hasSafeMobile:1; 
	unsigned int hasBigHeadImgUrl:1; 
	unsigned int hasSmallHeadImgUrl:1; 
	unsigned int hasSnsUserInfo:1; 
	unsigned int hasExtXml:1; 
	unsigned int hasSafeDeviceList:1; 
	unsigned int hasBigChatRoomSize:1; 
	unsigned int hasBigChatRoomQuota:1; 
	unsigned int hasBigChatRoomInvite:1; 
	unsigned int hasMainAcctType:1; 
	unsigned int hasSafeDevice:1; 
	unsigned int hasGrayscaleFlag:1; 
	NSString* myBrandList; 
	NSString* msgPushSound; 
	NSString* voipPushSound; 
	NSString* safeMobile; 
	NSString* bigHeadImgUrl; 
	NSString* smallHeadImgUrl; 
	SnsUserInfo* snsUserInfo; 
	SKBuiltinString_t* extXml; 
	SafeDeviceList* safeDeviceList; 
	unsigned bigChatRoomSize; 
	unsigned bigChatRoomQuota; 
	unsigned bigChatRoomInvite; 
	unsigned mainAcctType; 
	unsigned safeDevice; 
	unsigned grayscaleFlag; 
}
@property (assign) unsigned grayscaleFlag; 
@property (assign) BOOL hasGrayscaleFlag; 
@property (assign) unsigned safeDevice; 
@property (assign) BOOL hasSafeDevice; 
@property (retain) SafeDeviceList* safeDeviceList; 
@property (assign) BOOL hasSafeDeviceList; 
@property (retain) SKBuiltinString_t* extXml; 
@property (assign) BOOL hasExtXml; 
@property (assign) unsigned mainAcctType; 
@property (assign) BOOL hasMainAcctType; 
@property (retain) NSString* smallHeadImgUrl; 
@property (assign) BOOL hasSmallHeadImgUrl; 
@property (retain) NSString* bigHeadImgUrl; 
@property (assign) BOOL hasBigHeadImgUrl; 
@property (retain) NSString* safeMobile; 
@property (assign) BOOL hasSafeMobile; 
@property (assign) unsigned bigChatRoomInvite; 
@property (assign) BOOL hasBigChatRoomInvite; 
@property (assign) unsigned bigChatRoomQuota; 
@property (assign) BOOL hasBigChatRoomQuota; 
@property (assign) unsigned bigChatRoomSize; 
@property (assign) BOOL hasBigChatRoomSize; 
@property (retain) NSString* voipPushSound; 
@property (assign) BOOL hasVoipPushSound; 
@property (retain) NSString* msgPushSound; 
@property (assign) BOOL hasMsgPushSound; 
@property (retain) NSString* myBrandList; 
@property (assign) BOOL hasMyBrandList; 
@property (retain) SnsUserInfo* snsUserInfo; 
@property (assign) BOOL hasSnsUserInfo; 
+(id)parseFromData:(id)arg1;
-(id)SetSafeDeviceList:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasGrayscaleFlag:(BOOL)arg1;
-(void)setHasSafeDevice:(BOOL)arg1;
-(void)setHasSafeDeviceList:(BOOL)arg1;
-(void)setHasExtXml:(BOOL)arg1;
-(void)setHasMainAcctType:(BOOL)arg1;
-(void)setHasSafeMobile:(BOOL)arg1;
-(void)setHasBigChatRoomInvite:(BOOL)arg1;
-(void)setHasBigChatRoomQuota:(BOOL)arg1;
-(void)setHasBigChatRoomSize:(BOOL)arg1;
-(void)setHasVoipPushSound:(BOOL)arg1;
-(void)setHasMsgPushSound:(BOOL)arg1;
-(id)SetGrayscaleFlag:(unsigned)arg1;
-(id)SetSafeDevice:(unsigned)arg1;
-(id)SetExtXml:(id)arg1;
-(id)SetMainAcctType:(unsigned)arg1;
-(id)SetSafeMobile:(id)arg1;
-(id)SetBigChatRoomInvite:(unsigned)arg1;
-(id)SetBigChatRoomQuota:(unsigned)arg1;
-(id)SetBigChatRoomSize:(unsigned)arg1;
-(id)SetVoipPushSound:(id)arg1;
-(id)SetMsgPushSound:(id)arg1;
-(void)setGrayscaleFlag:(unsigned)arg1;
-(void)setSafeDevice:(unsigned)arg1;
-(void)setMainAcctType:(unsigned)arg1;
-(void)setBigChatRoomInvite:(unsigned)arg1;
-(void)setBigChatRoomQuota:(unsigned)arg1;
-(void)setBigChatRoomSize:(unsigned)arg1;
-(void)setSafeDeviceList:(id)arg1;
-(void)setExtXml:(id)arg1;
-(void)setSafeMobile:(id)arg1;
-(void)setVoipPushSound:(id)arg1;
-(void)setMsgPushSound:(id)arg1;
-(void)setHasMyBrandList:(BOOL)arg1;
-(void)setHasSmallHeadImgUrl:(BOOL)arg1;
-(void)setHasBigHeadImgUrl:(BOOL)arg1;
-(void)setHasSnsUserInfo:(BOOL)arg1;
-(id)SetMyBrandList:(id)arg1;
-(id)SetSmallHeadImgUrl:(id)arg1;
-(id)SetBigHeadImgUrl:(id)arg1;
-(id)SetSnsUserInfo:(id)arg1;
-(void)setMyBrandList:(id)arg1;
-(void)setSmallHeadImgUrl:(id)arg1;
-(void)setBigHeadImgUrl:(id)arg1;
-(void)setSnsUserInfo:(id)arg1;
-(id)init;
-(void)dealloc;
@end