/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:10 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VerifyPswdResponse : PBGeneratedMessage {
	unsigned int hasTicket:1; 
	unsigned int hasBaseResponse:1; 
	unsigned int hasImgSid:1; 
	unsigned int hasImgBuf:1; 
	unsigned int hasImgEncryptKey:1; 
	unsigned int hasA2Key:1; 
	unsigned int hasKsid:1; 
	NSString* ticket; 
	BaseResponse* baseResponse; 
	SKBuiltinString_t* imgSid; 
	SKBuiltinBuffer_t* imgBuf; 
	SKBuiltinString_t* imgEncryptKey; 
	SKBuiltinBuffer_t* a2Key; 
	SKBuiltinBuffer_t* ksid; 
}
@property (retain) SKBuiltinBuffer_t* ksid; 
@property (assign) BOOL hasKsid; 
@property (retain) SKBuiltinBuffer_t* a2Key; 
@property (assign) BOOL hasA2Key; 
@property (retain) SKBuiltinString_t* imgEncryptKey; 
@property (assign) BOOL hasImgEncryptKey; 
@property (retain) NSString* ticket; 
@property (assign) BOOL hasTicket; 
@property (retain) SKBuiltinBuffer_t* imgBuf; 
@property (assign) BOOL hasImgBuf; 
@property (retain) SKBuiltinString_t* imgSid; 
@property (assign) BOOL hasImgSid; 
@property (retain) BaseResponse* baseResponse; 
@property (assign) BOOL hasBaseResponse; 
+(id)parseFromData:(id)arg1;
-(id)SetA2Key:(id)arg1;
-(id)SetTicket:(id)arg1;
-(id)SetKsid:(id)arg1;
-(id)SetImgEncryptKey:(id)arg1;
-(id)SetImgSid:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasKsid:(BOOL)arg1;
-(void)setHasImgEncryptKey:(BOOL)arg1;
-(void)setKsid:(id)arg1;
-(void)setImgEncryptKey:(id)arg1;
-(void)setHasA2Key:(BOOL)arg1;
-(void)setA2Key:(id)arg1;
-(void)setHasImgSid:(BOOL)arg1;
-(void)setImgSid:(id)arg1;
-(void)setHasTicket:(BOOL)arg1;
-(void)setHasBaseResponse:(BOOL)arg1;
-(id)SetBaseResponse:(id)arg1;
-(void)setBaseResponse:(id)arg1;
-(void)setHasImgBuf:(BOOL)arg1;
-(id)SetImgBuf:(id)arg1;
-(void)setImgBuf:(id)arg1;
-(void)setTicket:(id)arg1;
-(id)init;
-(void)dealloc;
@end