/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:51 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VerifyPswdRequest : PBGeneratedMessage {
	unsigned int hasPwd1:1; 
	unsigned int hasPwd2:1; 
	unsigned int hasBaseRequest:1; 
	unsigned int hasImgSid:1; 
	unsigned int hasImgCode:1; 
	unsigned int hasImgEncryptKey:1; 
	unsigned int hasKsid:1; 
	unsigned int hasOpCode:1; 
	NSString* pwd1; 
	NSString* pwd2; 
	BaseRequest* baseRequest; 
	SKBuiltinString_t* imgSid; 
	SKBuiltinString_t* imgCode; 
	SKBuiltinString_t* imgEncryptKey; 
	SKBuiltinBuffer_t* ksid; 
	unsigned opCode; 
}
@property (retain) SKBuiltinBuffer_t* ksid; 
@property (assign) BOOL hasKsid; 
@property (retain) SKBuiltinString_t* imgEncryptKey; 
@property (assign) BOOL hasImgEncryptKey; 
@property (retain) SKBuiltinString_t* imgCode; 
@property (assign) BOOL hasImgCode; 
@property (retain) SKBuiltinString_t* imgSid; 
@property (assign) BOOL hasImgSid; 
@property (retain) NSString* pwd2; 
@property (assign) BOOL hasPwd2; 
@property (retain) NSString* pwd1; 
@property (assign) BOOL hasPwd1; 
@property (assign) unsigned opCode; 
@property (assign) BOOL hasOpCode; 
@property (retain) BaseRequest* baseRequest; 
@property (assign) BOOL hasBaseRequest; 
+(id)parseFromData:(id)arg1;
-(id)SetOpCode:(unsigned)arg1;
-(id)SetKsid:(id)arg1;
-(id)SetImgEncryptKey:(id)arg1;
-(id)SetImgCode:(id)arg1;
-(id)SetImgSid:(id)arg1;
-(id)SetPwd2:(id)arg1;
-(id)SetPwd1:(id)arg1;
-(id)SetBaseRequest:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasKsid:(BOOL)arg1;
-(void)setHasImgEncryptKey:(BOOL)arg1;
-(void)setHasPwd1:(BOOL)arg1;
-(void)setKsid:(id)arg1;
-(void)setImgEncryptKey:(id)arg1;
-(void)setPwd1:(id)arg1;
-(void)setHasImgCode:(BOOL)arg1;
-(void)setHasImgSid:(BOOL)arg1;
-(void)setHasPwd2:(BOOL)arg1;
-(void)setImgCode:(id)arg1;
-(void)setImgSid:(id)arg1;
-(void)setPwd2:(id)arg1;
-(void)setHasOpCode:(BOOL)arg1;
-(void)setOpCode:(unsigned)arg1;
-(void)setHasBaseRequest:(BOOL)arg1;
-(void)setBaseRequest:(id)arg1;
-(id)init;
-(void)dealloc;
@end