/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:11 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VideoVOIPCallerViewController : VideoVOIPViewController {
	UIButton* _cancelBtn; 
}
-(void)initFooterView;
-(void)OnError:(id)arg1 ErrNo:(int)arg2;
-(void)OnSyncError:(id)arg1 ErrNo:(int)arg2;
-(void)OnTimeOut:(id)arg1;
-(void)OnInterrupt:(id)arg1;
-(void)OnBeginTalk:(id)arg1;
-(void)OnBeginConnect:(id)arg1;
-(void)OnBeHanguped:(id)arg1;
-(void)OnBeRejected:(id)arg1;
-(void)OnBeAccepted:(id)arg1;
-(void)OnCall:(id)arg1 ErrNo:(int)arg2;
-(id)initWithFrame:(CGRect)arg1 andContact:(id)arg2 isEarMode:(BOOL)arg3;
-(void)showAlertTips;
-(void)updateStatusLabel;
-(void)checkAndShowAlertView;
-(void)endCallAfterDelay:(float)arg1;
-(void)initTipsView;
-(void)cancelCall;
-(void)OnNoAnswer:(id)arg1;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)viewDidLoad;
-(void)call;
-(id)init;
-(void)dealloc;
@end