/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:07 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VideoVOIPReceiverViewController : VideoVOIPViewController {
	BOOL isNeedFormSysMsg; 
	UIButton* _acceptBtn; 
	UIButton* _rejectBtn; 
	UIButton* _hangupBtn; 
	UIImageView* _newFooterView; 
}
-(void)initFooterView;
-(void)OnError:(id)arg1 ErrNo:(int)arg2;
-(void)OnSyncError:(id)arg1 ErrNo:(int)arg2;
-(void)OnTimeOut:(id)arg1;
-(void)OnInterrupt:(id)arg1;
-(void)OnBeginTalk:(id)arg1;
-(void)OnBeginConnect:(id)arg1;
-(void)OnBeHanguped:(id)arg1;
-(void)OnAccept:(id)arg1 ErrNo:(int)arg2;
-(void)endCallByCancel;
-(id)initWithFrame:(CGRect)arg1 andContact:(id)arg2 isEarMode:(BOOL)arg3;
-(void)asyncStartNetDetect;
-(void)updateStatusLabel;
-(void)checkAndShowAlertView;
-(void)endCallAfterDelay:(float)arg1;
-(void)initTipsView;
-(void)asyncPlaySoundFromBackgroundToForeground;
-(void)asyncAcceptVideo;
-(void)markLastVoipInfo;
-(void)showNewFooterView;
-(void)asyncPlaySound;
-(void)hangup;
-(void)rejectCall;
-(void)acceptCall;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)viewDidLoad;
-(id)init;
-(void)dealloc;
-(void)updateFooterView;
@end