/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:41 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IVOIPModeSwitchExt.h>
#import <IVOIPExt.h>
#import <AVVideoDeviceDelegate.h>
#import <VoipModeSwitchDelegate.h>
#import <SmallCameraViewDelegate.h>
#import <VoipTalkingViewDelegate.h>

@interface VideoVOIPViewController : UIWindow <IVOIPModeSwitchExt, IVOIPExt, AVVideoDeviceDelegate, VoipModeSwitchDelegate, SmallCameraViewDelegate, VoipTalkingViewDelegate> {
	UIAlertView* _alertView; 
	int _status; 
	CContact* _contact; 
	BOOL _isEndCall; 
	UIView* _profileContainerView; 
	UIView* _containerView; 
	UIImageView* _backgroundView; 
	MMHeadImageView* _HeadImageView; 
	UIView* _footerView; 
	UIImageView* _headFrame; 
	UIButton* _tipsView; 
	UILabel* _statusLabel; 
	CMessageWrap* _msgWrap; 
	BOOL _isConnectOK; 
	AVAudioPlayer* _player; 
	BOOL _isAcceptVoice; 
	VoipModeSwitch* _voipSwitch; 
	BOOL _canUpdateStatusMachine; 
}
@property (nonatomic,retain) CMessageWrap* msgWrap; 				//@synthesize msgWrap=_msgWrap - In the implementation block
@property (nonatomic,retain) CContact* contact; 				//@synthesize contact=_contact - In the implementation block
-(void)initView;
-(void)setContact:(id)arg1;
-(void)initFooterView;
-(void)setMsgWrap:(id)arg1;
-(id)initWithFrame:(CGRect)arg1 andContact:(id)arg2 isEarMode:(BOOL)arg3;
-(void)onConfirm;
-(void)disAppearWithAnimation;
-(void)playEndingSound;
-(void)formVOIPSysMsgView;
-(void)switchToTalkingView;
-(void)stopPlaySound;
-(void)updateStatusLabel;
-(void)appearWithAnimation;
-(void)endCallAfterDelay:(float)arg1;
-(void)playSound:(id)arg1 OfType:(id)arg2 numberOfLoops:(int)arg3;
-(void)initTipsView;
-(void)OnRemoteEarModeFor2G;
-(void)OnLocalEarModeFor2G;
-(void)stopDisAppearWithAnimation;
-(void)initProfileContainerView;
-(void)initBackgroundView;
-(void)updateNetTypeStatus;
-(void)VoipModeSwitchChangeMode:(unsigned long)arg1;
-(void)TalkingViewEndCall;
-(void)endCall;
-(void)updateFooterViewAndShowFlipCameraBtn;
-(void)dealloc;
@end