/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:18 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VoiceRemindInfo : PBGeneratedMessage {
	unsigned int hasRemindId:1; 
	unsigned remindId; 
}
@property (assign) unsigned remindId; 
@property (assign) BOOL hasRemindId; 
+(id)parseFromData:(id)arg1;
-(int)serializedSize;
-(void)writeToCodedOutputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1;
-(void)setHasRemindId:(BOOL)arg1;
-(id)SetRemindId:(unsigned)arg1;
-(void)setRemindId:(unsigned)arg1;
-(id)init;
-(void)dealloc;
@end