/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:47 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IVoiceInputExt.h>

@interface VoiceInputView : UIView <IVoiceInputExt> {
	unsigned mVoiceId; 
	id<NSObject> keyboard_targetor; 
	SEL keyboard_selector; 
	id<NSObject> send_targetor; 
	SEL send_selector; 
	int voiceInputStatus; 
	id<VoiceInputViewDelegate> delegate; 
	VoiceRecogView* mRecogView; 
	UIButton* mKeyboardBtn; 
	UIButton* mSendBtn; 
}
@property (nonatomic,retain) UIButton* mSendBtn; 
@property (nonatomic,retain) UIButton* mKeyboardBtn; 
@property (nonatomic,retain) VoiceRecogView* mRecogView; 
@property (assign,nonatomic) id<VoiceInputViewDelegate> delegate; 
-(void)stopRecord;
-(void)OnLevelMeter:(unsigned long)arg1 Peak:(float)arg2;
-(void)startRecord;
-(void)stopVoiceInput;
-(void)resetView;
-(void)addSendTarget:(id)arg1 action:(SEL)arg2;
-(void)addKeyboardTarget:(id)arg1 action:(SEL)arg2;
-(void)OnEndRecord;
-(void)OnStartRecord;
-(void)changeBkgView;
-(void)updateButtonStatus;
-(void)setMRecogView:(id)arg1;
-(void)OnSendBtnClicked:(id)arg1;
-(void)setMSendBtn:(id)arg1;
-(void)OnKeyboardBtnClicked:(id)arg1;
-(void)setMKeyboardBtn:(id)arg1;
-(void)OnError:(int)arg1 andInputId:(unsigned long)arg2;
-(void)OnGetText:(id)arg1 andInputId:(unsigned long)arg2;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
@end