/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:43 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VOIPUIHelper : NSObject {
}
+(id)FormVoipRemindMessageWithUsrname:(id)arg1 andInviteType:(int)arg2;
+(id)FormVoipMessageWithUsrname:(id)arg1 andInviteType:(int)arg2;
@end