/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:18 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VoipContentNodeView : BaseMessageNodeView {
	UIImageView* m_oBkgImageView; 
	UIImageView* m_oUnreadImageView; 
}
+(BOOL)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
-(void)asyncStartNetDetect;
-(void)onTouchCancel;
-(void)onTouchDownRepeat;
-(void)onTouchDown;
-(void)onTouchUpInside;
-(void)onLongTouch;
-(void)layoutSubviewsInternal;
-(CGSize)sizeForFrame:(CGRect)arg1;
-(void)onMenuItemWillHide;
-(void)onClearResource;
-(void)onDisappear;
-(void)updateBkgImage:(BOOL)arg1;
-(void)onClicked;
-(void)onLongPressed;
-(void)tapVoipNodeView;
-(void)tapVoiceVoipNodeView;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)updateStatus:(id)arg1;
-(void)dealloc;
@end