/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:58 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VoipStatusControlView : UIView {
	VoipStatusControl* voiceControl; 
	VoipStatusControl* videoControl; 
	VoipStatusControl* loudSpeakerControl; 
	id<VoipStatusDelegate> delegate; 
}
@property (assign,nonatomic) id<VoipStatusDelegate> delegate; 
+(int)reverseStatus:(int)arg1;
-(void)setDisable:(int)arg1;
-(void)controlTapped:(id)arg1;
-(id)initWithVoice:(BOOL)arg1 withLoudSpeakerStatus:(int)arg2;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
@end