/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:14 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WCAppInfo : NSObject {
	NSString* appID; 
	NSString* appName; 
	NSString* version; 
	NSString* installUrl; 
	NSString* fromUrl; 
}
@property (nonatomic,retain) NSString* fromUrl; 
@property (nonatomic,retain) NSString* installUrl; 
@property (nonatomic,retain) NSString* version; 
@property (nonatomic,retain) NSString* appName; 
@property (nonatomic,retain) NSString* appID; 
-(void)setFromUrl:(id)arg1;
-(void)setInstallUrl:(id)arg1;
-(void)setAppName:(id)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(BOOL)isValid;
-(void)setVersion:(id)arg1;
-(void)dealloc;
-(void)setAppID:(id)arg1;
@end