/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:52 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MMPackageDownloadMgrExt.h>

@interface WCBGRecommendMgr : NSObject <MMPackageDownloadMgrExt> {
	id<WCBGRecommendMgrDelegate> m_delegate; 
}
@property (assign,nonatomic) id<WCBGRecommendMgrDelegate> m_delegate; 
-(void)setM_delegate:(id)arg1;
-(void)onPackageListUpdated:(id)arg1;
-(void)updateBGStorage;
-(id)getBGStorage;
-(id)bgStorageWithDataList:(id)arg1;
-(id)getPackageDataOfBGStorage;
-(int)packageKey;
-(id)init;
-(void)dealloc;
@end