/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:55 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WCFacadeExt.h>

@interface WCBGImgLogic : NSObject <WCFacadeExt> {
	id<WCBGImgLogicNotity> m_delFacade; 
	WCMediaItem* m_lastUploadItem; 
	NSMutableDictionary* m_bgUserInfoMap; 
	NSString* m_lastDownloadMediaID; 
}
@property (assign,nonatomic) id<WCBGImgLogicNotity> m_delFacade; 
-(void)onDownloadFinish:(id)arg1 downloadType:(int)arg2;
-(void)SetBGImgByMedia:(id)arg1;
-(void)setBGImgLikedForUser:(id)arg1 source:(int)arg2;
-(BOOL)isBGImgLikedForUser:(id)arg1;
-(BOOL)hasBGImg:(id)arg1;
-(id)backgroundImageByContact:(id)arg1;
-(void)SetBGImgByImg:(id)arg1;
-(void)saveSelfWCBackground:(id)arg1;
-(id)tryLoadSelfWCBackground;
-(id)hashForImageUrl:(id)arg1;
-(void)trySaveSelfWCBackground:(id)arg1;
-(id)bgUserInfoMap;
-(void)setM_delFacade:(id)arg1;
-(BOOL)setLocalBGImgForUser:(id)arg1 BGUserInfo:(id)arg2;
-(id)init;
-(void)dealloc;
@end