/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:43 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol WCDataProviderDelegate
@optional
-(void)onReturnShowFlag(unsigned long):arg1 ;
-(void)onReturnBGUserInfo(id):arg1 ;
-(void)onReturnIsAllData(id):arg1 ;
-(void)onNoMoreDataWithRet(int):arg1 ;
-(void)onTotalCountChanged(int):arg1 ;
-(void)onDataUpdated(id):arg1 withChangedTime(unsigned long):arg2 ;
-(void)onDataUpdated(id):arg1 andData(id):arg2 withChangedTime(unsigned long):arg3 ;
@end
