/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:12 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WCDataUploader : WCUploader {
	int currentPos; 
	int uploadResult; 
	WCUploadTask* m_task; 
	id<WCDataUploaderDelegate> m_delegate; 
}
@property (assign,nonatomic) id<WCDataUploaderDelegate> m_delegate; 
@property (nonatomic,retain) WCUploadTask* m_task; 
-(void)setM_delegate:(id)arg1;
-(void)setFinished;
-(id)xmlForUploadTask:(id)arg1;
-(void)setM_task:(id)arg1;
-(void)onResponse:(id)arg1 Event:(unsigned long)arg2;
-(BOOL)onSetRequest:(id)arg1;
-(void)dealloc;
@end