/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:20 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol WCMediaUploaderDelegate
@required
-(void)onMediaUploadFinished(id):arg1 uploadResult(int):arg2 ;
-(void)onMediaUploadFinished(id):arg1 uploadResult(int):arg2 ;
@end

@protocol WCDataUploaderDelegate
@required
-(void)onDataUploadFinished(id):arg1 uploadResult(int):arg2 ;
-(void)onDataUploadFinished(id):arg1 uploadResult(int):arg2 ;
@end
