/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:13 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol WCFacadeExt
@optional
-(void)onHomepageTotalCountChanged(int):arg1 ;
-(void)onHomepageUpdate(int):arg1 withAdded(id):arg2 andChanged(id):arg3 andDeleted(id):arg4 ;
-(void)onCancelDownloadSuccess(id):arg1 downloadType(int):arg2 ;
-(void)onDownloadFinish(id):arg1 downloadType(int):arg2 ;
-(void)onDownloadMediaProcessChange(id):arg1 downloadType(int):arg2 current(int):arg3 total(int):arg4 ;
-(void)onWCPostPrivacyChanged;
-(void)onNotificationShowSettingChanged;
-(void)onDatabaseReloaded;
-(void)onNetworkActivityStatusChanged;
-(void)onBGStorageUpdated;
-(void)onWCBackgroundChanged;
-(void)onDataItemExposeFinisehd(int):arg1 dataItem(id):arg2 ;
-(void)onSetDataItemPublicFinished(int):arg1 dataItemID(id):arg2 ;
-(void)onSetDataItemPrivateFinished(int):arg1 dataItemID(id):arg2 ;
-(void)onDataItemDeleteFinished(int):arg1 dataItemID(id):arg2 ;
-(void)onUpdateDataItemDetailFinisehd(int):arg1 dataItem(id):arg2 ;
-(void)onMessageUnReadCountChanged;
-(void)onReveiceWCMessage(id):arg1 ;
-(void)onLatestWCObjectChanged(id):arg1 ;
-(void)onNoMoreTimelineData;
-(void)onDataChangedWithAdded(id):arg1 andChanged(id):arg2 andDeleted(id):arg3 ;
-(void)onWCLBSContactsUpdated(id):arg1 ;
@end
