/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:27 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MMService.h>
#import <WCBGImgLogicNotity.h>
#import <WCDownloadMgrDelegate.h>
#import <WCTimelineDelegate.h>
#import <WCLbsDelegate.h>
#import <WCCommentUploadMgrDelegate.h>
#import <WCUploadMgrDelegate.h>
#import <WCNotificationCenterMgrDelegate.h>
#import <WCHomepageDelegate.h>
#import <WCLogicMgrDelegate.h>
#import <WCFacadeExt.h>
#import <WCBGRecommendMgrDelegate.h>
#import <WCGroupMgrExt.h>

@interface WCFacade : MMService <MMService, WCBGImgLogicNotity, WCDownloadMgrDelegate, WCTimelineDelegate, WCLbsDelegate, WCCommentUploadMgrDelegate, WCUploadMgrDelegate, WCNotificationCenterMgrDelegate, WCHomepageDelegate, WCLogicMgrDelegate, WCFacadeExt, WCBGRecommendMgrDelegate, WCGroupMgrExt> {
	MyWCDB* m_database; 
	NSMutableArray* m_timelineWithLocalDatas; 
	WCUploadMgr* m_uploadMgr; 
	WCLbsLogic* m_lbslogic; 
	WCBGImgLogic* m_bgImgLogic; 
	WCTimelineMgr* m_timelineMgr; 
	WCDownloadMgr* m_downloadMgr; 
	WCCommentUploadMgr* m_commentUploadMgr; 
	WCNotificationCenterMgr* m_messageMgr; 
	WCLogicMgr* m_logicMgr; 
	WCBGRecommendMgr* m_bgMaster; 
	WCStrangerCommentMgr* m_strangerCommentMgr; 
	WCGroupMgr* m_groupMgr; 
	WCPatternCacheMgr* m_patternCacheMgr; 
	WCClearCacheTask* m_clearCacheTask; 
	NSMutableDictionary* m_homepageMgrDic; 
	NSMutableDictionary* m_networkEventDic; 
	NSMutableSet* m_deletedItemSet; 
}
-(BOOL)onServiceMemoryWarning;
-(void)onServiceTerminate;
-(void)onServiceEnterBackground;
-(void)onServiceReloadData;
-(BOOL)isShowNewTimelineEventNotification;
-(id)getLatestDataItem;
-(unsigned long)getUnReadMessageCount;
-(void)onWCGroupSetMemberToGroupsReturn:(BOOL)arg1 username:(id)arg2 groupIDs:(id)arg3;
-(void)onWCGroupModMemberReturn:(BOOL)arg1 group:(id)arg2;
-(void)onWCGroupRemoveMemberReturn:(BOOL)arg1 group:(id)arg2;
-(void)onWCGroupAddMemberReturn:(BOOL)arg1 group:(id)arg2;
-(void)onWCDeleteGroupReturn:(BOOL)arg1 groupID:(id)arg2;
-(void)onWCChangeGroupNameReturn:(BOOL)arg1 groupID:(id)arg2;
-(void)onWCCreateGroupReturn:(BOOL)arg1 group:(id)arg2;
-(void)onWCGroupUpdatedReturn:(BOOL)arg1;
-(void)onWCGroupRecommendUpdated;
-(void)onWCGroupUpdated;
-(void)onCancelDownloadSuccess:(id)arg1 downloadType:(int)arg2;
-(void)onDownloadFinish:(id)arg1 downloadType:(int)arg2;
-(void)onDownloadMediaProcessChange:(id)arg1 downloadType:(int)arg2 current:(int)arg3 total:(int)arg4;
-(void)onBGStorageUpdated;
-(void)onDataItemExposeFinisehd:(int)arg1 dataItem:(id)arg2;
-(void)onSetDataItemPublicFinished:(int)arg1 dataItemID:(id)arg2;
-(void)onSetDataItemPrivateFinished:(int)arg1 dataItemID:(id)arg2;
-(void)onDataItemDeleteFinished:(int)arg1 dataItemID:(id)arg2;
-(void)onUpdateDataItemDetailFinisehd:(int)arg1 dataItem:(id)arg2;
-(void)onMessageUnReadCountChanged;
-(void)onLatestWCObjectChanged:(id)arg1;
-(void)onNoMoreTimelineData;
-(void)onWCLBSContactsUpdated:(id)arg1;
-(BOOL)isUserInGroup:(id)arg1 GroupID:(id)arg2;
-(void)updateAllGroups;
-(id)getGroupByID:(id)arg1;
-(void)setShowNewTimelineEventNotification:(BOOL)arg1;
-(int)getHomepageTotalCount:(id)arg1;
-(void)forceDownloadMedia:(id)arg1 downloadType:(int)arg2;
-(void)likeObject:(id)arg1 ofUser:(id)arg2 source:(int)arg3;
-(void)unLikeObject:(id)arg1 ofUser:(id)arg2;
-(void)SetBGImgByMedia:(id)arg1;
-(void)setDataItemPublic:(id)arg1;
-(void)setDataItemPrivate:(id)arg1;
-(id)getStrangerDataItemByID:(id)arg1 ofPartner:(id)arg2;
-(id)getDataItemByID:(id)arg1;
-(void)exposeDataItem:(id)arg1;
-(void)deleteDataItem:(id)arg1;
-(void)commentObject:(id)arg1 toStranger:(id)arg2 content:(id)arg3 ref:(id)arg4 source:(int)arg5;
-(void)commentObject:(id)arg1 ofUser:(id)arg2 content:(id)arg3 ref:(id)arg4 source:(int)arg5;
-(void)restartUploadDataItem:(id)arg1;
-(void)unCommentObject:(id)arg1 ofUser:(id)arg2 comment:(id)arg3;
-(void)deleteUploadDataItem:(id)arg1;
-(void)updateDataItemDetail:(id)arg1;
-(id)getMessageFrom:(id)arg1 maxCount:(unsigned long)arg2;
-(id)getUnReadMessages;
-(void)markMessageListRead:(id)arg1;
-(void)setBGImgLikedForUser:(id)arg1 source:(int)arg2;
-(BOOL)isBGImgLikedForUser:(id)arg1;
-(BOOL)hasBGImg:(id)arg1;
-(id)backgroundImageByContact:(id)arg1;
-(BOOL)updateHomePageTail:(id)arg1;
-(BOOL)updateHomePageHead:(id)arg1;
-(BOOL)updateHomePageHead:(id)arg1 source:(int)arg2;
-(id)getHomepageData:(id)arg1;
-(void)endHomepage:(id)arg1;
-(void)beginHomepage:(id)arg1;
-(void)SetBGImgByImg:(id)arg1;
-(void)updateBGStorage;
-(id)getBGStorage;
-(id)getLastUnReadMessage;
-(BOOL)updateTimelineTail;
-(BOOL)updateTimelineHead;
-(void)beginTimeline;
-(void)downloadMedia:(id)arg1 downloadType:(int)arg2;
-(void)tryGetWCDataItemPattern:(id)arg1;
-(id)getTimelineDataItemOfIndex:(int)arg1;
-(id)getFailedUploads;
-(int)countOfTimelineDataItem;
-(void)reloadTimelineDataItems;
-(void)endTimeline;
-(id)GetRecommendUsr;
-(id)uploadDataItem:(id)arg1;
-(id)getLastPostGroups;
-(void)setPostPrivacy:(int)arg1;
-(int)getPostPrivacy;
-(void)forceDownloadMediaWithProcessNotify:(id)arg1 downloadType:(int)arg2;
-(void)setPostPrivacy:(int)arg1 withGroupIDs:(id)arg2;
-(id)getAllGroups;
-(id)getUnReadRecommendsForGroup:(id)arg1;
-(void)deleteGroup:(id)arg1;
-(void)modGroup:(id)arg1 newName:(id)arg2 members:(id)arg3;
-(void)setRecommendReadForGroup:(id)arg1;
-(unsigned long)getTimelineShowFlag;
-(void)applicationWillBecomeActive;
-(void)reloadDatabase;
-(void)onCommentReturn:(id)arg1;
-(void)onReveiceWCMessages:(id)arg1;
-(void)markMessageRead:(id)arg1;
-(id)getAllMessages;
-(void)endNetworkActivity:(int)arg1 cgi:(int)arg2;
-(void)beginNetworkActivity:(int)arg1 cgi:(int)arg2;
-(void)cancelDownloadMedia:(id)arg1 downloadType:(int)arg2;
-(void)downloadMediaWithProcessNotify:(id)arg1 downloadType:(int)arg2;
-(id)getGroupsWithMember:(id)arg1;
-(void)setMember:(id)arg1 toGroups:(id)arg2;
-(void)removeMembers:(id)arg1 fromGroup:(id)arg2;
-(void)addMembers:(id)arg1 toGroup:(id)arg2;
-(void)modifyGroupName:(id)arg1 newName:(id)arg2;
-(void)createGroup:(id)arg1 withGroupName:(id)arg2;
-(void)updateAllRecommends;
-(id)getReadRecommendsForGroup:(id)arg1;
-(void)onHomepage:(id)arg1 BGImgChanged:(id)arg2;
-(void)onHomepage:(id)arg1 totalCountChanged:(int)arg2;
-(void)onHomepageUpdate:(int)arg1 username:(id)arg2 withAdded:(id)arg3 andChanged:(id)arg4 andDeleted:(id)arg5;
-(id)findDataItemInCacheByItemID:(id)arg1;
-(void)modifyDataItem:(id)arg1 notify:(BOOL)arg2;
-(id)strangerCommentMgrWithDB;
-(void)LLComment_onBeforeReturnUnLikeDataItem:(id)arg1;
-(void)LLComment_onBeforeReturnUnCommentDataItem:(id)arg1 comment:(id)arg2;
-(void)LLComment_onBeforeReturnStrangerDataItem:(id)arg1 partner:(id)arg2;
-(void)LLComment_onBeforeReturnDataItem:(id)arg1;
-(void)notifyTotalCountWhenDataItemDeleted:(id)arg1;
-(id)homepageMgr:(id)arg1;
-(id)uploadMgr;
-(void)LLDelete_onAfterDeleteDataItemFinished:(id)arg1;
-(void)LLDelete_onBeforeDeleteDataItem:(id)arg1;
-(void)LLUpload_onAfterUploadTaskRestarted:(id)arg1;
-(void)LLUpload_onAfterUploadTaskFailed:(id)arg1;
-(void)LLUpload_onAfterUploadTaskFinished:(id)arg1;
-(void)LLUpload_onAfterAddUploadTask:(id)arg1;
-(void)LLUpload_onBeforeAddUploadTask:(id)arg1;
-(void)NotifyToUploadWithTask:(id)arg1;
-(void)NotifyBackgroundChanged;
-(void)NotifyToDownloadMedia:(id)arg1 downloadType:(int)arg2;
-(id)getUploadingDataItems;
-(void)onTimelineDataChangedWithAdded:(id)arg1 andChanged:(id)arg2 andDeleted:(id)arg3;
-(void)onUploadFinished:(id)arg1;
-(void)onUploadRestarted:(id)arg1;
-(void)onUploadFailed:(id)arg1;
-(id)groupMgr;
-(id)networkEventDic;
-(void)markDataItemDeleted:(id)arg1;
-(id)messageMgrWithDB;
-(id)logicMgr;
-(id)bgMaster;
-(void)likeObject:(id)arg1 toStranger:(id)arg2 source:(int)arg3;
-(id)lbslogic;
-(id)downloadMgr;
-(id)patternCacheMgr;
-(id)getDataItemByID:(id)arg1 addLocal:(BOOL)arg2;
-(id)bgImgLogic;
-(id)getCurrentUserHomepage;
-(BOOL)isDataItemDeleted:(id)arg1;
-(id)innerGetHomepage:(id)arg1;
-(BOOL)LL_onBeforeReturnDataItem:(id)arg1;
-(id)timelineMgr;
-(id)deletedItemSet;
-(void)onReveiceStrangerMessage:(id)arg1;
-(void)deleteAllMessages;
-(void)deleteMessage:(id)arg1;
-(id)database;
-(id)init;
-(void)dealloc;
-(BOOL)isNetworkActive;
@end