/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:32 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PBMessageObserverDelegate.h>

@interface WCGroupMgr : NSObject <PBMessageObserverDelegate> {
	BOOL m_bMemCacheNeedReload; 
	NSMutableDictionary* m_groups; 
	NSMutableDictionary* m_recommends; 
	NSMutableDictionary* m_readRecommends; 
	id<WCGroupMgrExt> m_delegate; 
}
@property (assign,nonatomic) id<WCGroupMgrExt> m_delegate; 
-(void)setM_delegate:(id)arg1;
-(void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
-(void)updateAllGroups;
-(id)getGroupByID:(id)arg1;
-(id)getAllGroups;
-(id)getUnReadRecommendsForGroup:(id)arg1;
-(void)deleteGroup:(id)arg1;
-(void)modGroup:(id)arg1 newName:(id)arg2 members:(id)arg3;
-(void)setRecommendReadForGroup:(id)arg1;
-(void)clearMemoryCache;
-(void)saveData;
-(void)tryLoadData;
-(void)onSetMemberToGroupsReturn:(id)arg1 Event:(unsigned long)arg2;
-(void)onGroupListReturn:(id)arg1 Event:(unsigned long)arg2;
-(void)onGroupMemberOpReturn:(id)arg1 Event:(unsigned long)arg2;
-(void)onGroupOpReturn:(id)arg1 Event:(unsigned long)arg2;
-(BOOL)tryFuzzDefaultGroup;
-(void)clearMD5;
-(void)doGroupOp:(unsigned long)arg1 onGroup:(id)arg2 withGroupName:(id)arg3;
-(void)doGroupMemberOp:(unsigned long)arg1 onGroup:(id)arg2 withGroupName:(id)arg3 withMemberList:(id)arg4;
-(void)doGroupListOp:(unsigned long)arg1 withMD5:(id)arg2;
-(id)pathForReadRecommendData;
-(id)pathForRecommendData;
-(id)pathForGroupData;
-(id)getGroupsWithMember:(id)arg1;
-(void)setMember:(id)arg1 toGroups:(id)arg2;
-(void)removeMembers:(id)arg1 fromGroup:(id)arg2;
-(void)addMembers:(id)arg1 toGroup:(id)arg2;
-(void)modifyGroupName:(id)arg1 newName:(id)arg2;
-(void)createGroup:(id)arg1 withGroupName:(id)arg2;
-(void)updateAllRecommends;
-(id)getReadRecommendsForGroup:(id)arg1;
-(id)init;
-(void)dealloc;
@end