/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:45 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WCHomepageDataProvider_Sns : WCHomepageDataProvider {
	NSString* fpHash; 
	BOOL isWorking; 
}
-(void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
-(void)forceUpdateWithReferID:(id)arg1;
-(void)updateHeadWithSource:(int)arg1;
-(void)updateWithReferID:(id)arg1;
-(void)requestForSnsHomepageRequest:(id)arg1 source:(int)arg2;
-(BOOL)responseForSnsUserPageResponse:(id)arg1 Event:(unsigned long)arg2;
-(void)saveResponseListForFutureList:(id)arg1;
-(id)converListToList:(id)arg1;
-(void)internalSaveResponseListForFutureList:(id)arg1;
-(void)dealloc;
@end