/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:17 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PBMessageObserverDelegate.h>

@interface WCHomepageDataProvider : NSObject <PBMessageObserverDelegate> {
	NSString* username; 
	id<WCDataProviderDelegate> delegate; 
}
@property (nonatomic,retain) NSString* username; 
@property (assign,nonatomic) id<WCDataProviderDelegate> delegate; 
-(void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
-(void)forceUpdateWithReferID:(id)arg1;
-(void)updateHeadWithSource:(int)arg1;
-(void)updateWithReferID:(id)arg1;
-(void)setUsername:(id)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
@end