/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:45 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WCLbsLogic : NSObject {
	id<WCLbsDelegate> m_delegate; 
	NSMutableSet* m_setNotifyUsr; 
	NSMutableArray* m_lastRecommandContactList; 
}
@property (nonatomic,retain) NSMutableArray* m_lastRecommandContactList; 
@property (nonatomic,retain) NSMutableSet* m_setNotifyUsr; 
@property (assign,nonatomic) id<WCLbsDelegate> m_delegate; 
-(void)setM_delegate:(id)arg1;
-(id)GetRecommendUsr;
-(BOOL)isValidRecommendUsr:(id)arg1;
-(void)setM_lastRecommandContactList:(id)arg1;
-(void)setM_setNotifyUsr:(id)arg1;
-(id)init;
-(void)dealloc;
@end