/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:05 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PBMessageObserverDelegate.h>

@interface WCLogicMgr : NSObject <PBMessageObserverDelegate> {
	id<WCLogicMgrDelegate> m_delegate; 
}
@property (assign,nonatomic) id<WCLogicMgrDelegate> m_delegate; 
-(void)setM_delegate:(id)arg1;
-(void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
-(void)setDataItemPublic:(id)arg1;
-(void)setDataItemPrivate:(id)arg1;
-(void)exposeDataItem:(id)arg1;
-(void)deleteDataItem:(id)arg1;
-(void)updateDataItemDetail:(id)arg1;
-(void)requestForSnsObjectDetailRequest:(id)arg1;
-(void)requestForExposeRequest:(id)arg1;
-(void)requestForSnsObjectOpRequest:(id)arg1;
-(void)onOperation:(id)arg1 Finished:(int)arg2;
-(BOOL)responseForSnsObjectOpResponse:(id)arg1 Event:(unsigned long)arg2;
-(BOOL)responseForExposeResponse:(id)arg1 Event:(unsigned long)arg2;
-(BOOL)responseForSnsObjectDetailResponse:(id)arg1 Event:(unsigned long)arg2;
-(void)unLikeDataItem:(id)arg1;
-(void)unCommentDataItem:(id)arg1 commentID:(id)arg2;
-(id)init;
-(void)dealloc;
@end