/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:03 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WCMediaUploader : WCUploader {
	int currentPos; 
	int uploadResult; 
	WCUploadMedia* m_media; 
	id<WCMediaUploaderDelegate> m_delegate; 
}
@property (assign,nonatomic) id<WCMediaUploaderDelegate> m_delegate; 
@property (nonatomic,retain) WCUploadMedia* m_media; 
-(void)setM_delegate:(id)arg1;
-(void)setFinished;
-(void)onResponse:(id)arg1 Event:(unsigned long)arg2;
-(BOOL)onSetRequest:(id)arg1;
-(void)tryNextRequest;
-(void)setM_media:(id)arg1;
-(id)init;
-(void)dealloc;
@end