/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:43:08 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>

@interface WCMediaItem : NSObject <NSCoding> {
	NSString* mid; 
	int type; 
	NSString* title; 
	NSString* desc; 
	NSString* titlePattern; 
	NSString* descPattern; 
	NSString* source; 
	NSMutableArray* previewUrls; 
	WCUrl* dataUrl; 
	WCUrl* lowBandUrl; 
	CGSize imgSize; 
	BOOL likeFlag; 
	int likeCount; 
	NSMutableArray* likeUsers; 
	int commentCount; 
	NSMutableArray* commentUsers; 
	int withCount; 
	NSMutableArray* withUsers; 
}
@property (nonatomic,retain) NSMutableArray* withUsers; 
@property (assign,nonatomic) int withCount; 
@property (nonatomic,retain) NSMutableArray* commentUsers; 
@property (assign,nonatomic) int commentCount; 
@property (nonatomic,retain) NSMutableArray* likeUsers; 
@property (assign,nonatomic) int likeCount; 
@property (assign,nonatomic) BOOL likeFlag; 
@property (assign,nonatomic) CGSize imgSize; 
@property (nonatomic,retain) WCUrl* lowBandUrl; 
@property (nonatomic,retain) WCUrl* dataUrl; 
@property (nonatomic,retain) NSMutableArray* previewUrls; 
@property (nonatomic,retain) NSString* source; 
@property (nonatomic,retain) NSString* descPattern; 
@property (nonatomic,retain) NSString* titlePattern; 
@property (nonatomic,retain) NSString* desc; 
@property (nonatomic,retain) NSString* title; 
@property (assign,nonatomic) int type; 
@property (nonatomic,retain) NSString* mid; 
-(void)setLikeFlag:(BOOL)arg1;
-(void)setPreviewUrls:(id)arg1;
-(void)setMid:(id)arg1;
-(BOOL)hasPreview;
-(void)setImgSize:(CGSize)arg1;
-(void)setLowBandUrl:(id)arg1;
-(void)setDesc:(id)arg1;
-(id)imageOfSizeNoAutoRelease:(int)arg1;
-(id)pathForPreview;
-(id)pathForData;
-(void)setLikeCount:(int)arg1;
-(id)mediaID;
-(void)saveDataFromData:(id)arg1;
-(void)savePreviewFromData:(id)arg1;
-(void)savePreviewFromPath:(id)arg1;
-(void)saveDataFromPath:(id)arg1;
-(id)hashPathForString:(id)arg1;
-(void)setWithCount:(int)arg1;
-(void)setDescPattern:(id)arg1;
-(void)setTitlePattern:(id)arg1;
-(void)setWithUsers:(id)arg1;
-(void)setCommentUsers:(id)arg1;
-(void)setLikeUsers:(id)arg1;
-(void)setDataUrl:(id)arg1;
-(void)savePreviewFromMedia:(id)arg1;
-(void)saveDataFromMedia:(id)arg1;
-(id)imageOfSize:(int)arg1;
-(struct)locationForData;
-(id)cityForData;
-(id)videoStreamForData;
-(id)voiceStreamForData;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)setTitle:(id)arg1;
-(BOOL)isValid;
-(void)setType:(int)arg1;
-(void)setSource:(id)arg1;
-(int)mediaType;
-(void)setCommentCount:(int)arg1;
-(BOOL)hasData;
-(void)dealloc;
@end