/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:36 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIScrollViewDelegate.h>
#import <PageScrollViewDelegate.h>
#import <PageScrollViewDataSource.h>

@interface WCMultiImageScannerController : MMFullScreenViewController <UIScrollViewDelegate, PageScrollViewDelegate, PageScrollViewDataSource> {
	PageScrollView* _pageScrollView; 
	UIButton* _deleteButton; 
	NSMutableArray* _arrViewItem; 
	unsigned _currentIndex; 
	id<WCMultiImageScannerDelegate> _scannerDelegate; 
}
@property (assign,nonatomic) id<WCMultiImageScannerDelegate> scannerDelegate; 				//@synthesize scannerDelegate=_scannerDelegate - In the implementation block
@property (nonatomic,retain) NSMutableArray* arrViewItem; 				//@synthesize arrViewItem=_arrViewItem - In the implementation block
@property (nonatomic,retain) UIButton* deleteButton; 				//@synthesize deleteButton=_deleteButton - In the implementation block
@property (nonatomic,retain) PageScrollView* pageScrollView; 				//@synthesize pageScrollView=_pageScrollView - In the implementation block
-(void)initScrollView;
-(void)onTopBarFrameChanged;
-(void)initNavigationBar;
-(void)onMainWindowFrameChanged;
-(void)hideFullScreen;
-(void)showFullScreen;
-(id)pageScrollView:(id)arg1 viewForItem:(unsigned)arg2;
-(unsigned)numberOfItems:(id)arg1;
-(unsigned)currentIndex:(id)arg1;
-(void)onChangedWithCurrentIndex:(int)arg1;
-(CGRect)frameForPageAtItem:(unsigned)arg1;
-(void)onSingleClicked;
-(CGPoint)contentOffsetForPageScrollView;
-(CGSize)contentSizeForPageScrollView;
-(CGRect)frameForPageScrollView;
-(void)showAlert;
-(void)deleteCurrentItem;
-(void)setDeleteButton:(id)arg1;
-(void)setPageScrollView:(id)arg1;
-(void)setArrViewItem:(id)arg1;
-(void)setScannerDelegate:(id)arg1;
-(id)initWithViewItems:(id)arg1 currentIndex:(unsigned)arg2;
-(void)updateTitle;
-(void)scrollViewDidScroll:(id)arg1;
-(void)scrollViewDidEndDecelerating:(id)arg1;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)handleSingleTap;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)dealloc;
@end