/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:12 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WCPatternCacheMgr : NSObject {
	NSMutableDictionary* m_cache; 
	BOOL m_needWriteBack; 
	BOOL m_needLoadData; 
}
-(void)onServiceMemoryWarning;
-(void)onServiceTerminate;
-(void)onServiceEnterBackground;
-(void)tryGetWCDataItemPattern:(id)arg1;
-(id)pathForData;
-(void)tryLoadData;
-(void)trySaveData;
-(id)init;
-(void)dealloc;
@end