/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:14 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>

@interface WCPattern : NSObject <NSCoding> {
	WCDataItem* dataItem; 
	double lastAccessTime; 
}
@property (assign,nonatomic) double lastAccessTime; 
@property (nonatomic,retain) WCDataItem* dataItem; 
-(void)setDataItem:(id)arg1;
-(void)setLastAccessTime:(double)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)dealloc;
@end