/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:21 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>

@interface WCSetting : NSObject <NSCoding> {
	NSString* groupListMD5; 
	NSString* groupRecommendListMD5; 
	int postPrivacy; 
	NSMutableArray* lastPostGroupIDs; 
	unsigned lastShareOptions; 
	WCDataItem* lastDataItem; 
	int unReadCount; 
	unsigned timelineShowFlag; 
}
@property (assign,nonatomic) unsigned timelineShowFlag; 
@property (assign,nonatomic) int unReadCount; 
@property (nonatomic,retain) WCDataItem* lastDataItem; 
@property (assign,nonatomic) unsigned lastShareOptions; 
@property (nonatomic,retain) NSMutableArray* lastPostGroupIDs; 
@property (assign,nonatomic) int postPrivacy; 
@property (nonatomic,retain) NSString* groupRecommendListMD5; 
@property (nonatomic,retain) NSString* groupListMD5; 
-(void)setPostPrivacy:(int)arg1;
-(void)setLastShareOptions:(unsigned long)arg1;
-(void)setUnReadCount:(int)arg1;
-(void)setLastDataItem:(id)arg1;
-(void)setTimelineShowFlag:(unsigned long)arg1;
-(void)setLastPostGroupIDs:(id)arg1;
-(void)setGroupRecommendListMD5:(id)arg1;
-(void)setGroupListMD5:(id)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)dealloc;
@end