/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:18 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol WCTaskUploaderDelegate
@required
-(void)onUploadFinished(id):arg1 ;
-(void)onMediaUploadFinished(id):arg1 task(id):arg2 ;
-(void)onUploadFinished(id):arg1 ;
-(void)onMediaUploadFinished(id):arg1 task(id):arg2 ;
@end
