/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:20 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WCMediaUploaderDelegate.h>
#import <WCDataUploaderDelegate.h>

@interface WCTaskUploader : NSObject <WCMediaUploaderDelegate, WCDataUploaderDelegate> {
	WCUploadTask* _uploadTask; 
	WCUploader* _uploader; 
	NSMutableSet* _runnedSubTask; 
	int _runningState; 
	id<WCTaskUploaderDelegate> _delegate; 
}
-(void)tryStartNextTask;
-(void)onDataUploadFinished:(id)arg1 uploadResult:(int)arg2;
-(void)onMediaUploadFinished:(id)arg1 uploadResult:(int)arg2;
-(void)handleError;
-(id)initWithTask:(id)arg1 withDelegate:(id)arg2;
-(void)run;
-(void)dealloc;
@end