/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:33 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WCUploadMedia : NSObject {
	int type; 
	NSData* buffer; 
	NSString* clientID; 
	int failCount; 
	BOOL isFinished; 
	WCUrl* bufferUrl; 
	WCUrl* lowBandUrl; 
	WCUrl* bufferDataUrl; 
	WCUrl* lowBandDataUrl; 
	NSMutableArray* thumbUrlsList; 
	NSString* serverID; 
	int outType; 
	int imageFilterID; 
	CGSize imgSize; 
	BOOL isSyncToWeibo; 
	BOOL isSyncToFacebook; 
	BOOL isSyncToTwitter; 
	BOOL isSyncToQZone; 
	NSString* title; 
	NSString* desc; 
	BOOL isThumbForPrevMeida; 
	int imageFrom; 
	NSString* twitterOAuthToken; 
	NSString* twitterOAuthTokenSecret; 
}
@property (nonatomic,retain) NSString* twitterOAuthTokenSecret; 
@property (nonatomic,retain) NSString* twitterOAuthToken; 
@property (assign,nonatomic) int imageFrom; 
@property (assign,nonatomic) BOOL isThumbForPrevMeida; 
@property (nonatomic,retain) NSString* title; 
@property (nonatomic,retain) NSString* desc; 
@property (assign,nonatomic) BOOL isSyncToQZone; 
@property (assign,nonatomic) BOOL isSyncToTwitter; 
@property (assign,nonatomic) BOOL isSyncToFacebook; 
@property (assign,nonatomic) BOOL isSyncToWeibo; 
@property (assign,nonatomic) CGSize imgSize; 
@property (assign,nonatomic) int imageFilterID; 
@property (assign,nonatomic) int outType; 
@property (nonatomic,retain) NSString* serverID; 
@property (nonatomic,retain) NSMutableArray* thumbUrlsList; 
@property (nonatomic,retain) WCUrl* lowBandDataUrl; 
@property (nonatomic,retain) WCUrl* bufferDataUrl; 
@property (nonatomic,retain) WCUrl* lowBandUrl; 
@property (nonatomic,retain) WCUrl* bufferUrl; 
@property (assign,nonatomic) BOOL isFinished; 
@property (nonatomic,retain) NSString* clientID; 
@property (nonatomic,retain) NSData* buffer; 
@property (assign,nonatomic) int type; 
-(void)setImageFrom:(int)arg1;
-(void)setTwitterOAuthTokenSecret:(id)arg1;
-(void)setTwitterOAuthToken:(id)arg1;
-(void)setIsSyncToQZone:(BOOL)arg1;
-(void)setIsSyncToTwitter:(BOOL)arg1;
-(void)setIsSyncToFacebook:(BOOL)arg1;
-(void)setIsSyncToWeibo:(BOOL)arg1;
-(void)setImgSize:(CGSize)arg1;
-(void)setImageFilterID:(int)arg1;
-(void)setLowBandUrl:(id)arg1;
-(void)setThumbUrlsList:(id)arg1;
-(void)setBufferUrl:(id)arg1;
-(void)setDesc:(id)arg1;
-(void)setIsThumbForPrevMeida:(BOOL)arg1;
-(id)getTypeName;
-(void)setOutType:(int)arg1;
-(id)mediaBuffer;
-(void)setLowBandDataUrl:(id)arg1;
-(void)setBufferDataUrl:(id)arg1;
-(void)removeMediaBuffer;
-(void)saveMediaBuffer;
-(void)clearMediaBuffer;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)setTitle:(id)arg1;
-(void)setType:(int)arg1;
-(void)setServerID:(id)arg1;
-(void)setClientID:(id)arg1;
-(void)setBuffer:(id)arg1;
-(void)dealloc;
-(void)setIsFinished:(BOOL)arg1;
@end