/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:39:18 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WCTaskUploaderDelegate.h>
#import <INetworkStatusMgrExt.h>

@interface WCUploadMgr : NSObject <WCTaskUploaderDelegate, INetworkStatusMgrExt> {
	FIFOFileQueue* m_taskQueue; 
	NSMutableArray* m_failedQueue; 
	NSMutableArray* m_succeedItems; 
	id<WCUploadMgrDelegate> m_delegate; 
	BOOL m_taskRunning; 
	WCTaskUploader* m_taskUploader; 
}
@property (assign,nonatomic) id<WCUploadMgrDelegate> m_delegate; 
-(void)setM_delegate:(id)arg1;
-(void)onNetworkStatusChange:(unsigned long)arg1;
-(id)getFailedUploads;
-(void)deleteHomepageSucceedUploads:(id)arg1;
-(void)deleteTimelineSucceedUploads:(id)arg1;
-(void)addSucceedUpload:(id)arg1;
-(void)onMediaUploadFinished:(id)arg1 task:(id)arg2;
-(void)onUploadFinished:(id)arg1;
-(void)notifyUploadFinished:(id)arg1;
-(void)saveCurrentTask;
-(void)cleanUpForTask:(id)arg1;
-(void)setClientIDForMedia:(id)arg1;
-(void)notifyUploadFailed:(id)arg1;
-(void)notifyUploadRestart:(id)arg1;
-(void)setTaskFail:(id)arg1;
-(void)notifyUploadFailStatusChanged:(id)arg1;
-(BOOL)saveFailedQueue;
-(void)doDeleteSucceedUploads:(id)arg1 from:(id)arg2;
-(BOOL)saveSucceedItems;
-(void)TryStartTask;
-(BOOL)loadSucceedItems;
-(BOOL)loadFailedQueue;
-(void)addUploadTask:(id)arg1;
-(void)deleteUploadTaskWithDataIem:(id)arg1;
-(void)restartUploadTaskWithDataIem:(id)arg1;
-(id)getHomepageSucceedUploads;
-(id)getTimelineSucceedUploads;
-(id)getInQueueUploads;
-(id)init;
-(void)dealloc;
@end