/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:40:27 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>

@interface WCUploadTask : NSObject <NSCoding> {
	NSString* serverID; 
	NSString* clientID; 
	int type; 
	BOOL isPrivate; 
	NSMutableArray* sharedGroupIDs; 
	BOOL isSyncToWeibo; 
	BOOL isSyncToFacebook; 
	BOOL isSyncToTwitter; 
	BOOL isSyncToQZone; 
	struct {
		double latitude;
		double longitude;
	} location; 
	float scale; 
	NSString* linkUrl; 
	NSString* title; 
	NSString* desc; 
	NSString* contentDesc; 
	WCAppInfo* appInfo; 
	NSString* sourceUserName; 
	NSString* sourceNickName; 
	NSMutableArray* withUserList; 
	NSMutableArray* mediaList; 
	SnsObject* snsObj; 
	WCDataItem* dataItem; 
	NSDate* createTime; 
	int uploadResult; 
	int BGImgSetType; 
	BOOL isUploadFailed; 
	int postSource; 
	NSString* twitterOAuthToken; 
	NSString* twitterOAuthTokenSecret; 
}
@property (nonatomic,retain) NSString* twitterOAuthTokenSecret; 
@property (nonatomic,retain) NSString* twitterOAuthToken; 
@property (assign,nonatomic) int postSource; 
@property (nonatomic,retain) NSMutableArray* sharedGroupIDs; 
@property (assign,nonatomic) BOOL isUploadFailed; 
@property (assign,nonatomic) int BGImgSetType; 
@property (nonatomic,retain) NSString* contentDesc; 
@property (nonatomic,retain) NSString* sourceNickName; 
@property (nonatomic,retain) NSString* sourceUserName; 
@property (nonatomic,retain) WCAppInfo* appInfo; 
@property (nonatomic,retain) NSString* linkUrl; 
@property (nonatomic,retain) WCDataItem* dataItem; 
@property (assign,nonatomic) int uploadResult; 
@property (nonatomic,retain) NSDate* createTime; 
@property (nonatomic,retain) SnsObject* snsObj; 
@property (nonatomic,retain) NSMutableArray* mediaList; 
@property (nonatomic,retain) NSMutableArray* withUserList; 
@property (nonatomic,retain) NSString* desc; 
@property (nonatomic,retain) NSString* title; 
@property (assign,nonatomic) float scale; 
@property (assign,nonatomic) struct location; 
@property (assign,nonatomic) BOOL isSyncToQZone; 
@property (assign,nonatomic) BOOL isSyncToTwitter; 
@property (assign,nonatomic) BOOL isSyncToFacebook; 
@property (assign,nonatomic) BOOL isSyncToWeibo; 
@property (assign,nonatomic) BOOL isPrivate; 
@property (assign,nonatomic) int type; 
@property (nonatomic,retain) NSString* clientID; 
@property (nonatomic,retain) NSString* serverID; 
-(void)setDataItem:(id)arg1;
-(void)setMediaList:(id)arg1;
-(void)setWithUserList:(id)arg1;
-(void)setContentDesc:(id)arg1;
-(void)setTwitterOAuthTokenSecret:(id)arg1;
-(void)setTwitterOAuthToken:(id)arg1;
-(void)setIsSyncToQZone:(BOOL)arg1;
-(void)setIsSyncToTwitter:(BOOL)arg1;
-(void)setIsSyncToFacebook:(BOOL)arg1;
-(void)setIsSyncToWeibo:(BOOL)arg1;
-(void)setSharedGroupIDs:(id)arg1;
-(void)setIsPrivate:(BOOL)arg1;
-(void)setLinkUrl:(id)arg1;
-(void)setSourceNickName:(id)arg1;
-(void)setSourceUserName:(id)arg1;
-(void)setPostSource:(int)arg1;
-(void)setDesc:(id)arg1;
-(void)setAppInfo:(id)arg1;
-(void)setCreateTime:(id)arg1;
-(void)setIsUploadFailed:(BOOL)arg1;
-(BOOL)isLocationValide;
-(void)setBGImgSetType:(int)arg1;
-(void)setSnsObj:(id)arg1;
-(void)setUploadResult:(int)arg1;
-(void)setUploadFailedStatus:(BOOL)arg1;
-(void)addThumbForPrevMedia:(id)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)setTitle:(id)arg1;
-(void)setType:(int)arg1;
-(void)setScale:(float)arg1;
-(void)setServerID:(id)arg1;
-(void)setClientID:(id)arg1;
-(void)dealloc;
-(id)description;
-(void)setLocation:(struct )arg1;
@end