/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:38:53 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PBMessageObserverDelegate.h>

@interface WCUploader : NSObject <PBMessageObserverDelegate> {
	int eventID; 
}
-(void)MessageReturn:(id)arg1 Event:(unsigned long)arg2;
-(void)setFinished;
-(void)onResponse:(id)arg1 Event:(unsigned long)arg2;
-(BOOL)onSetRequest:(id)arg1;
-(void)run;
-(BOOL)startRequest;
-(void)dealloc;
@end