/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:28 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WCUtil : NSObject {
}
+(id)getUserWCRootDir;
+(void)saveWCSetting:(id)arg1;
+(id)getWCSetting;
+(BOOL)isExistGroupName:(id)arg1 exceptGroup:(id)arg2;
+(void)endNetworkEvent:(int)arg1 event:(int)arg2;
+(void)beginNetworkEvent:(int)arg1 event:(int)arg2;
+(id)getUserWCMediaDir;
+(id)pathForWCSetting;
+(id)pathForBGImgDir;
+(id)getUserWCMediaUploadDir;
+(id)getUserWCDBRootDir;
+(id)mergeTimeline:(id)arg1 Left:(id)arg2 Right:(id)arg3 Added:(id)arg4 Changed:(id)arg5 Deleted:(id)arg6;
+(id)pathForSelfHomepageFPBackup;
+(id)pathForTimelineFPBackup;
+(id)pathForCurUserBGImg;
+(id)pathForBGImg:(id)arg1;
+(int)serverUrlTypeToLocalType:(int)arg1;
+(int)localUrlTypeToServerType:(int)arg1;
+(int)serverContentTypeToLocalType:(int)arg1;
+(int)localContentTypeToServerType:(int)arg1;
+(int)serverMediaTypeToLocalType:(int)arg1;
+(int)localMediaTypeToServerType:(int)arg1;
+(id)getUserWCSucceedItemPath;
+(id)getUserWCFailedQueuePath;
+(id)uploadPathForUploadMedia:(id)arg1;
+(id)getWCDBPath;
+(id)getUserWCMediaDownloadDir;
@end