/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:36 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WXTalkTipsView : UIView {
	id<WXTalkTipsViewDelegate> _delegate; 
	CContact* _contact; 
	BOOL _isUnfold; 
	UIImageView* _bgView; 
	UIImageView* _iconView; 
	UILabel* _foldTipsLabel; 
	UIImageView* _arrowView; 
	UILabel* _unfoldTipsLabel; 
	UIButton* _enterButton; 
	UIButton* _cancelButton; 
}
@property (assign,nonatomic) id<WXTalkTipsViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
+(id)showTalkRoomTips:(id)arg1 withDelegate:(id)arg2;
-(id)initWithContact:(id)arg1;
-(BOOL)checkTouchPoint:(CGPoint)arg1 IfInView:(id)arg2;
-(void)unfold;
-(void)setTipsTitle:(id)arg1;
-(void)doFadeOutAnimation;
-(void)resetTipsView;
-(void)doFoldAnimation;
-(void)doUnfoldAnimation;
-(void)unfoldAnimationFinish;
-(void)onEnterButtonPress;
-(void)onCancelButtonPress;
-(void)updateFoldTipsLabel:(id)arg1;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
@end