/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:41:06 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IWXTalkExt.h>

@interface WXTalkGlobalButton : UIWindow <IWXTalkExt> {
	UIImageView* _iconView; 
	UILabel* _memberCountLabel; 
	UIActivityIndicatorView* _actIndicView; 
	BOOL _isPrepared; 
}
-(void)initView;
-(void)initLoadingView;
-(void)onRemoteControlCheckShouldStop;
-(void)onRemoteControlCheckShouldPlay;
-(void)OnNobodyTalking;
-(void)OnError:(id)arg1 ErrNo:(int)arg2;
-(void)OnRoomMemberChange:(id)arg1;
-(void)OnSomeoneTalking:(id)arg1;
-(void)OnOpenWXTalkModeOK:(id)arg1;
-(void)showWithAnimation;
-(void)stopEnteringAnimation;
-(void)doEnteringAnimation;
-(void)initMemberCountView;
-(void)initIconView;
-(void)initBackgroudView;
-(void)onIconClick;
-(void)openNewMode;
-(void)hideWithAnimation;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
@end