/*
 * This header is generated by weak_classdump 0.2
 * on Friday, May 10, 2013, 3:42:20 PM China Standard Time
 * Operating System: Version 6.1.2 (Build 10B146)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WXTalkHeadImageListView : UIView {
	UILabel* _titleLabel; 
	UILabel* _tipsLabel; 
	UIButton* _arrowButton; 
	UIButton* _closeButton; 
	UIImageView* _iconView; 
	id<WXTalkHeadImageListViewDelegate> _delegate; 
}
@property (assign,nonatomic) id<WXTalkHeadImageListViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
-(void)setTips:(id)arg1;
-(void)onCloseButtonPress;
-(void)onArrowBtnClicked;
-(void)hideArrowButtonAndShowCloseButton;
-(void)showArrowButtonAndHideCloseButton;
-(id)initWithFrame:(CGRect)arg1 AndTitle:(id)arg2;
-(void)setTitle:(id)arg1;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
@end